### ISSUE TITLE
Look into providing low level uGNI communication layer on Crays

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#102]
On Cray XK machines, it has been shown that CPU and GPU code scales much better when using uGNI instead of using full blown MPI.  This is placeholder to discuss the merits and implementation of this.

NAMD GPU strong scaling has been shown to improve by 50%.  I would suspect that QUDA could similarly benefit.

**Comment by mathiaswagner** [comment]
Still a thing???

**Comment by maddyscientist** [comment]
Not a thing.
