### ISSUE TITLE
Register optimization for each dslash kernel

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#103]
The current mechanism for generating code does not allow for per kernel specification of the register usage.  Ideally each dslash kernel (dslash_type, precision, reconstruct, dagger) would have a separate declaration of launch_bounds which could be optimized per kernel per architecture.  

On GK110, tuning for register allocation has improved performance as much as 20% in double-precision clover code.  Exhaustive studies for all kernels and precision combinations across architectures are impractical.

Constructing an auto-tuning approach to this is difficult, but is something that should be implemented.  Note this is compile-time optimization and with the current build system, this would require a lot of wall-clock time.  How one would implement such an auto-tuning approach is certainly open for discussion: should we use a bash or python script, or something else completely?

Implementing such a scheme will likely first require the re-engineering of all of the dslash and pack face kernels to be template driven and not macro driven.  This is already desirable anyway to allow the dslash kernels to be more modular and allow for single struct argument kernels (which is fairly impossible currently).

**Comment by mathiaswagner** [comment]
Is this still a thing with the new dslash framework / newer architectures?

**Comment by maddyscientist** [comment]
This can be closed.  The only practical way of doing this would be to do it with Jitify (whence this becomes trivial).  In general I don't foresee us doing this for off-line compilation.
