### ISSUE TITLE
Implement one-sided communication MPI back end

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#105]
We should achieve better strong scaling if we use one-sided MPI communication instead of the current two-sided approach.  This has shown to improve strong scaling on a variety of machines.

The only thing to discuss is whether to use the current one-sided interface that is possible with MPI 2, or to use MPI 3 which updates and expands.  I guess this is a question of compatibility: is there any reason not to target MPI 3?

**Comment by mathiaswagner** [comment]
Guess this has been superseded by NVSHMEM?

**Comment by maddyscientist** [comment]
Indeed.  Closing.
