### ISSUE TITLE
Remove explicit copy constructors from accessors

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#1108]
In gauge_field_order.h `FloatNOrder` and `Reconstruct` copy constructors should be default.

@jcosborn please add any more issues here

**Comment by jcosborn** [comment]
quda::blas::ReductionArg<double, 2, double, 2, double, 2, quda::blas::Norm1<double, double>>

not sure where the offending copy constructor is yet

**Comment by jcosborn** [comment]
blas_helper.cuh: Spinor and SpinorNorm

**Comment by jcosborn** [comment]
Also virtual functions in reduce_core.cuh: ReduceFunctor
makes it non-trivially copy constructible
http://www.cplusplus.com/reference/type_traits/is_trivially_copy_constructible/
Is that necessary?

**Comment by maddyscientist** [comment]
@jcosborn latest commits to the generic-kernel branch remove the explicit copy constructors from `Spinor` and `SpinorNorm` from blas_helper.cuh and also make `ReduceFunctor::pre` and `ReduceFunctor::post` non-virtual methods.  (As noted on slack, the gauge_field_order.h copy constructors were already removed). Let me know if there are any other copy constructors you find that need to be removed.

**Comment by maddyscientist** [comment]
Closing this issue, as this has all been achieve in #1056 already
