### ISSUE TITLE
Stategy to extend TwistClover to two flavours

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#1122]
`ApplyTwistClover` of `dslash_quda.cu` has already been provisioned to support two flavours (via the `epsilon` parameter). However, the underlying `TwistCloverApply` kernel does not take this into account yet (working on it).

As we're working to add support for non-degenerate twisted clover, I was also surprised to see no dependence of the sign of mu on `dagger` or `inverse`, where `inverse = false` should apply `Clover + i gamma5 a` while `inverse = true` should apply `(Clover - i gamma5 a)/(Clover^2 + mu^2)`.

https://github.com/lattice/quda/blob/9fc7f749f5c0fa6773a06d81a4d62a72d3cf2949/include/kernels/dslash_misc.cuh#L242

Going up the call graph, I don't see a point where the sign of mu is changed for the inverse call either, but maybe I haven't looked sufficiently carfeully.

**Comment by kostrzewa** [comment]
Would you agree @urbach @maddyscientist ?

**Comment by kostrzewa** [comment]
Oh, wait, I see that this is taken care of in `CloverArg`!

**Comment by kostrzewa** [comment]
Since the initial question has resolved itself, I wanted to use the opportunity to ask if extending `CloverArg` to two flavours would be your preferred way for me to proceed to provide two-flavour support for this part.

I would add another kernel, `NdegTwistCloverApply`, to provide the counterpart to `TwistCloverApply` for a two-flavour spinor and add some logic to the `apply()` function of `TwistClover`:

```
308     void apply(const qudaStream_t &stream)
309     {
310       TuneParam tp = tuneLaunch(*this, getTuning(), getVerbosity());
311       if (inverse) {
312         CloverArg<Float, nColor, true> arg(out, in, clover, parity, kappa, mu, epsilon, dagger, twist);
313         if(in.TwistFlavor() == QUDA_TWIST_SINGLET){
314           launch<TwistCloverApply>(tp, stream, arg);                                                                                   
315         } else {
316           launch<NdegTwistCloverApply>(tp, stream, arg);
317         }
318       } else {
319         CloverArg<Float, nColor, false> arg(out, in, clover, parity, kappa, mu, epsilon, dagger, twist);
320         if(in.TwistFlavor() == QUDA_TWIST_SINGLET){
321           launch<TwistCloverApply>(tp, stream, arg);
322         } else {
323           launch<NdegTwistCloverApply>(tp, stream, arg);
324         }
325       }
326     }
```

**Comment by kostrzewa** [comment]
In the kernel itself, I'm afraid I'm not quite sure how to get to the second flavour. In the Dslash it's easy:

```
 78           Vector x0 = arg.x(coord.x_cb + 0 * arg.dc.volume_4d_cb, my_spinor_parity);
 79           Vector x1 = arg.x(coord.x_cb + 1 * arg.dc.volume_4d_cb, my_spinor_parity);
```

as I have access to `flavor` and `arg.dc.volume_4d_cb`. In the `TwistCloverApply` kernel, however, I get an index on a checkerboard (`x_cb`) and a parity and via `CloverArg` I have access to `volumeCB`. Would the latter give the right offset to get to the second flavour?

**Comment by maddyscientist** [comment]
Why not just add another member to the `CloverArg` that explicitly only includes the 4-d volume?  E.g., something like `volume_4d_cb = volumeCB / X[4]`?

**Comment by kostrzewa** [comment]
> Why not just add another member to the CloverArg that explicitly only includes the 4-d volume? E.g., something like volume_4d_cb = volumeCB / X[4]?

perfect, thanks!

**Comment by kostrzewa** [comment]
>>  Why not just add another member to the CloverArg that explicitly only includes the 4-d volume? E.g., something like volume_4d_cb = volumeCB / X[4]?

> perfect, thanks!

Actually, you've already taken care of that by constructing `volumeCB` as `in.volumeCB()/2` in the case of `doublet == true`.

**Comment by maddyscientist** [comment]
😉
