### ISSUE TITLE
Optimize multi-shift CG solver

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#113]
The multi-shift CG solver can be optimized through using kernel fusion across the shifts for the p[j] and x[j] updates
````c++
	//beta[0] = r2[0] / r2_old;	
	beta[0] = zn / r2_old;
	// update p[0] and x[0]
	axpyZpbxCuda(alpha[0], *p[0], *x_sloppy[0], *r_sloppy, beta[0]);	

	for (int j=1; j<num_offset_now; j++) {
	  beta[j] = beta[j_low] * zeta[j] * alpha[j] / (zeta_old[j] * alpha[j_low]);
	  // update p[i] and x[i]
	  axpyBzpcxCuda(alpha[j], *p[j], *x_sloppy[j], zeta[j], *r_sloppy, beta[j]);
	}
````

Here if we merge this into a single kernel we get the advantage of reusing r_sloppy across all shifts giving a 20% reduction in memory traffic.  Additionally we would have the advantage of only paying for a single kernel launch, hence it would scale better with volume.

Further optimization of multi-shift CG could also be obtained through using a pipelined variant like is already implemented for CG.

**Comment by mathiaswagner** [comment]
Just have been looking into the multi-shift and thought that I could take care of this. However, it seems that this kind of Kernel is not supported by the framework for the blas Kernels.
Should we extend the framework or just implement a Kernel for that not using the framework. I am inclined to go with the first option but that is probably more work.

**Comment by maddyscientist** [comment]
Moving to 0.9.  I plan on revamping the blas framework a lot in 0.9, and these changes will make this task trivial.
