### ISSUE TITLE
[HIP][O1] Multigrid test fails with hipOutOfMemory when Tuning

### ISSUE THREAD

**Issue by CRobeck** [lattice/quda#1131]
export META="--unit-gauge 0 --dim 16 16 16 16 --Lsdim 1 --gridsize 1 1 1 1 --solve-type direct-pc --dslash-type clover --mass 0 --clover-coeff 0.01 --compute-clover 1 --anisotropy 1 --inv-multigrid true"
export SOLVER_PARAM="--prec single --prec-sloppy single --prec-precondition single --tol 5e-7"
export MG_PARAM="--mg-levels 3 --mg-generate-nullspace true"
export LEVEL0_PARAM="--mg-nu-pre 0 0 --mg-nu-post 0 8 --mg-block-size 0 4 4 4 4 --mg-nvec 0 24 --mg-setup-inv 0 cg --mg-smoother 0 ca-gcr"
export LEVEL1_PARAM="--mg-nu-pre 1 0 --mg-nu-post 1 8 --mg-block-size 1 2 2 2 2 --mg-nvec 1 32 --mg-setup-inv 1 cg --mg-smoother 1 ca-gcr"
export LEVEL2_PARAM="--mg-coarse-solver 2 ca-gcr --mg-coarse-solver-maxiter 2 8"
./invert_test $META $SOLVER_PARAM $MG_PARAM $LEVEL0_PARAM $LEVEL1_PARAM $LEVEL2_PARAM

**Comment by CRobeck** [comment]
QUDA_ENABLE_TUNING=0 passes

**Comment by bjoo** [comment]
Issue appears fixed by reducing shared memory size to 32000. After that it behaved like #1134. That issue was fixed by commit f03dd39
