### ISSUE TITLE
[HIP][O2][dslash-clover tests hang/take very long]

### ISSUE THREAD

**Issue by bjoo** [lattice/quda#1132]
Using ROCm-4.1.0 RC2 we see hangs in CTest Tests 7,8 (dslash_clover-[a]sym-policytune  when compiling  BuildConfiguration DEVEL with -O2.

Test passes with -O1

**Comment by CRobeck** [comment]
./dslash_ctest "--dslash-type" "clover" "--test" "MatPCDagMatPC" "--matpc" "even-even" "--dim" "2" "4" "6" "8" "--gtest_output=xml:dslash_clover_test_poltune.xml"

**Comment by bjoo** [comment]
Fixed in adbb3d27 -- apparent compiler bug.
