### ISSUE TITLE
Remove GPUDirect=no functionality

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#124]
Given that sharing pinned buffers between IB and CUDA has been part of CUDA for over two years now, and we've had no complaints of it not working for over a year, I propose that we remove all #ifdef GPUDIRECT macros from QUDA and delete all non-GPUDirect functionality from the library.

This will clean up the communications interfaces as well and will mean that when gpu-aware MPI functionality is supported in QUDA, the GPUDirect name overload will not occur.  I would suggest at that point in fact that we simply use GPUDirect to designate that GPU-aware mpi is being used.

Any objections to this clean up?

**Comment by mathiaswagner** [comment]
@maddyscientist Move this to the big clean-up for 0.9?
