### ISSUE TITLE
2.8 * M_PI, is it a typo?

### ISSUE THREAD

**Issue by jxy** [lattice/quda#1273]
https://github.com/lattice/quda/blob/6d16d9e06ac1aca084638db116b0dd1a0ab035b6/include/targets/cuda/math_helper.cuh#L96

**Comment by maddyscientist** [comment]
That is a typo.  Thanks for the catch.  It's a harmless one, since `a < 2 π`, but good to fix

**Comment by maddyscientist** [comment]
Bug fix pushed, will close then when the branch in question is merged in.
