### ISSUE TITLE
Potential multigrid regression due to two-stage tuning

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#1291]
While trying to understand the regression reported #1287 I have found a potentially related regression that I don't understand.  This was introduced as part of the two-stage tuning (#1260).  This regression concerns the VUV kernel, and it is ~33% slower with the two-stage tuning.  What is especially perplexing is that the regression isn't apparent in the first sweep to find the candidates, it seems to appear in the second stage of the tuning.

E.g., VUV kernel, half precision, 16^4 volume, 4^4 blocking on a Quadro GV100 (prior to #1260) reports performance around ~1800-1900 GFLOPS.  This performance is observed in the first stage of autotuning:
```
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16384 aux=(2,1,1)
MG level 0 (GPU): C   block=(128,1,1), grid=(256,2,4), shared_bytes=16384, aux=(2,1,1,1) gives 1833.42 Gflop/s, 923.87 GB/s
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16385 aux=(2,1,1)
MG level 0 (GPU): C   block=(128,1,1), grid=(256,2,4), shared_bytes=16385, aux=(2,1,1,1) gives 1835.08 Gflop/s, 924.71 GB/s
```
However, when these are re-run in the second step, the kernels are significantly slower
```
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16384 aux=(2,1,1)
MG level 0 (GPU): T   block=(128,1,1), grid=(256,2,4), shared_bytes=16384, aux=(2,1,1,1) gives 1292.92 Gflop/s, 651.51 GB/s
MG level 0 (GPU): About to call tunable.apply block=(128,1,1) grid=(256,2,4) shared_bytes=16385 aux=(2,1,1)
MG level 0 (GPU): T   block=(128,1,1), grid=(256,2,4), shared_bytes=16385, aux=(2,1,1,1) gives 1288.45 Gflop/s, 649.26 GB/s
```

I don't understand how this can be happening.  If anything, the increased iteration count in the second step of tuning should lead to faster performance since there is less host induced latency.

@mathiaswagner thoughts?

**Comment by mathiaswagner** [comment]
That is very weird. Not sure how that would be happening. Just thinking out loud but we could play with the iteration counts in both tuning stages. How long is the kernel running?

**Comment by maddyscientist** [comment]
One really weird thing I noticed is that if we increase the candidates from 10 to 100, for example, the apparent regression is a factor of two greater again.  I'm mainly confused.

Kernel is running ~milliseconds.
