### ISSUE TITLE
quda 1.0.0 release does not build correctly 

### ISSUE THREAD

**Issue by twobombs** [lattice/quda#1302]
The URL in the CMakeLists.txt of QUDA 1.0.0 is dead. Link gives off a zerobyte file that fails the build
I suggest a change in the CMakeLists.txt at these two lines
![Screenshot from 2022-07-26 16-37-38](https://user-images.githubusercontent.com/12692227/181062566-bc896a7b-0452-4e6f-b1ea-bce1a9aca960.png)
Then the build will commence

**Comment by maddyscientist** [comment]
Thanks for the report @twobombs.  As you probably realize, this issue is fixed in the develop version of QUDA.  We don't plan on making an update to the 1.0 release, but we could apply this patch to the `release/1.0.x` branch if you want to stick to the 1.0 branch.  If so, please feel free to file such a PR.

**Comment by twobombs** [comment]
Thank you @maddyscientist . Just happened to find this one out whists building the legacy version for < sm_60 
Also running into some CUDA 11.x issues at compile time. If I get this going I'll file a PR. tnx.

**Comment by maddyscientist** [comment]
Which architecture are you building for?  It's been a while since I tried to compile for Kepler, but I can't think of any reason off the top of my head why Kepler is explicitly broken with the develop branch or the 1.1 branch using CUDA 11.x.

Also, we have already applied some fixes to the 1.0 branch, so it may be worth testing using `release/1.0.x` as opposed to the to the 1.0 tarball.

**Comment by twobombs** [comment]
I'm looking at this error causing a lot of the stuff to not compile
![Screenshot from 2022-07-26 16-59-11](https://user-images.githubusercontent.com/12692227/181066275-d08d1673-9c3f-4534-bace-7370d30a938b.png)

But I'll check out the release/1.0.x , suspect a lot of that regression has been care of already :)
edit: looking at K80 and M40 Tesla's that do not compile/run the binaries succefull because < sm_60

**Comment by maddyscientist** [comment]
And just checking: since I am curious who are users are, I looked you up.  From your twitter profile, I see you're interested in quantum computing.  Just checking you're not looking for [QODA](https://developer.nvidia.com/qoda), as opposed to QUDA?  😄

**Comment by twobombs** [comment]
Both :)

**Comment by maddyscientist** [comment]
I remember that thrust issue now.  We have actually removed thrust entirely from QUDA now, so I know that issue is gone from develop.  The issue should be fixed the `release/1.1.x` branch as well.

**Comment by twobombs** [comment]
yes, building straight from main (1.1.0+) with 0 problems. but I'm interested in Tesla K80/M40 action. The 1.1.0 main does not build the examples when < sm_60. So, there I came on the idea to use 1.0. ATM everything is building in the docker barn, so when the images are baked and ready I'll give 'em a spin. Thank you very much for your help ! :)

**Comment by maddyscientist** [comment]
@twobombs I've just checked the develop build of QUDA when compiling for Kepler (sm_35).  It does still compile fine, but you need to specify the cmake flag `-DQUDA_HETEROGENOUS_ATOMICS=OFF` (also visible using `ccmake` on the advanced option screen).

**Background**: by default QUDA uses libcu++'s `std::atomic` functionality for signaling and synchronization in the reduction kernels, however these require Pascal GPUs or above.  For earlier GPUs when you disable this, it will revert to using CUDA legacy `atomicAdd` and CUDA events for synchronization and things should compile and run fine on sm_35 and sm_52 GPUs.

**Comment by twobombs** [comment]
![Screenshot from 2022-07-27 13-31-38](https://user-images.githubusercontent.com/12692227/181246219-a3779115-2447-4424-b1c4-55bd0b1493b7.png)
and
![Screenshot from 2022-07-27 14-27-36](https://user-images.githubusercontent.com/12692227/181246579-51dd55a5-90fe-4a37-9317-2fe53d616b97.png)

can't see the setting, also not in ccmake
[edit]
Found it:
![Screenshot from 2022-07-27 14-49-27](https://user-images.githubusercontent.com/12692227/181251128-b3253126-5e74-4da8-a132-7557e938ce35.png)
[edit=edit]
Still sm related errors visible; atomic supports was in the make overview above still ON
![Screenshot from 2022-07-27 14-54-04](https://user-images.githubusercontent.com/12692227/181251781-28444db2-c618-4336-92ba-d17c155312b7.png)

**Comment by maddyscientist** [comment]
Apologies: there no S at the end.  It’s just `-DQUDA_HETEROGENEOUS_ATOMIC=OFF`

**Comment by twobombs** [comment]
![Screenshot from 2022-07-27 15-32-58](https://user-images.githubusercontent.com/12692227/181259844-ae5522a6-a6cc-465f-9441-a9b9a731b313.png)

It's ignored by cmake. Feature remains on ON

**Comment by maddyscientist** [comment]
Check the entry in the CMakeCache.txt file.  Might be worth just nuking the cache file.

Note the console is reporting whether the feature option is enabled, not the feature itself is on.

**Comment by maddyscientist** [comment]
Typo above: heterogenous isn’t spelt correctly.  That’s the problem.  Sorry, should have seen that quicker (on my phone here 😀)

**Comment by twobombs** [comment]
yes, it completed the build. tnx :)
