### ISSUE TITLE
The normal distribution is not standard in gaugeGauss.

### ISSUE THREAD

**Issue by SaltyChiang** [lattice/quda#1319]
In https://github.com/lattice/quda/blob/develop/include/kernels/gauge_random.cuh#L45, QUDA attempts to generate some normally distributed random variables by applying the Box-Muller transform.

Comparing the implementation with the one on Wikipedia, it seems that these variables are distributed with $\mathcal{N}(0,\frac{1}{\sqrt{2}})$ instead of the standard normal distribution $\mathcal{N}(0,1)$, because the line `radius[i] = sqrt(-log(rand2[i]))` lacks a `2` before `log`.

Is it by design or a bug? The meaning of `sigma` parameter for `gaugeGaussQuda` (which is called `sigma` in the docstring but `epsilon` as the actual arg name) should be modified if it is by design.

**Comment by jxy** [comment]
NO.  I believe that is by design such that the su(3) matrix has an expectation value of norm squared equal to 8.

**Comment by maddyscientist** [comment]
Thanks @jxy.  What are your thoughts @SaltyChiang?  Do you need the factor of two to match some other code?  If so, I wonder if we should make this a parameter to support different conventions.

**Comment by SaltyChiang** [comment]
@jxy Thank you for your information. The problem is that there exists a parameter to adjust the expectation value, instead of just returning the result.

In spinor_noise.cuh#L29, we have no chance to change the sigma of the distribution, but for su3 field, we do have the parameter. If this is by design, I think some comments should be there to point out that the sigma is not the one in the normal distribution.

**Comment by jxy** [comment]
This is su(3).  We are not talking about Normal distribution in R.  We are talking about Normal distribution in su(3), which has dimension 8.  So 8 is the correct normalization.  The comment about sigma being the width is not wrong.

**Comment by SaltyChiang** [comment]
I see. That sounds reasonable and I will revert the commit. Thank you for the comment.

Also, this issue should be closed as there is no problem in the current code.
