### ISSUE TITLE
Plenty of time was wasted when calculating the propagators

### ISSUE THREAD

**Issue by wittscien** [lattice/quda#1335]
I use Chroma with QUDA 1.1.0 to perform the invertion of a light quark from a 24^3*72 lattice using QUDA_MULTIGRID_CLOVER_INVERTER with a V100 card. While each of the 12 sectors of a propagator costs only 1.33s, the propagator used a total of 167s. (This is not the first grid-setting inversion task of the run.) I speculate this is because OMP_NUM_THREADS is not working. Since no matter how many cores are allocated or how to set parameters, the consumption does not change much. Also, there is no `QDP use OpenMP threading. We have x threads` line at the beginning of the log.

I have used another Chroma binary installed by others (older versions). No such problem occurs -- there is one line where QDP reports the information of the thread, and with OMP_NUM_THREADS set higher, the time decreases from 142s to some 50~60s. 

I use the latest versions: QMP 2-5-4, QDP++ 1-46-0, QUDA 1.1.0, and Chroma 3-44-0 (also checked out to their development branch). I have performed the installation and test running on two clusters. The problem can be reproduced.

This is a piece of the log:
```
Initialize done
Initializing QUDA with initQuda(-1)
QUDA 1.1.0 (git 1.1.0-e2415ef-sm_70)
CUDA Driver version = 11060
CUDA Runtime version = 11010
Found device 0: Tesla V100-SXM2-32GB
Using device 0: Tesla V100-SXM2-32GB
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
Loaded 167 sets of cached parameters from ./tunes/beta6.20_mu-0.2770_ms-0.2400_L24x72/tunecache.tsv
Loaded 167 sets of cached parameters from ./tunes/beta6.20_mu-0.2770_ms-0.2400_L24x72/tunecache.tsv
WARNING: Using device memory pool allocator
WARNING: Using pinned memory pool allocator
cublasCreated successfully
Linkage = bool Chroma::MapObjectDiskEnv::registerAll(): registering map obj key colorvec
0
...
GCR:    25 iterations, <r,r> = 1.144442e-20, |r|/|b| = 4.809308e-10
GCR:    26 iterations, <r,r> = 2.572360e-21, |r|/|b| = 2.280088e-10
GCR (restart):     8 iterations, <r,r> = 2.572379e-21, |r|/|b| = 2.280096e-10
GCR:    27 iterations, <r,r> = 5.652392e-22, |r|/|b| = 1.068813e-10
GCR:    28 iterations, <r,r> = 1.233897e-22, |r|/|b| = 4.993733e-11
GCR:    29 iterations, <r,r> = 2.762165e-23, |r|/|b| = 2.362711e-11
GCR:    30 iterations, <r,r> = 6.221997e-24, |r|/|b| = 1.121374e-11
GCR (restart):     9 iterations, <r,r> = 6.222041e-24, |r|/|b| = 1.121378e-11
GCR:    31 iterations, <r,r> = 1.376198e-24, |r|/|b| = 5.273832e-12
GCR: number of restarts = 9
GCR: Convergence at 31 iterations, L2 relative residual: iterated = 5.273833e-12, true = 5.273833e-12 (requested = 1.000000e-11)
Solution = 0.153708
Reconstructed solution: 0.153708
QUDA_MULTIGRID_CLOVER_LINOP_SOLVER( quda_mg_subspace_l ): time=1.334754 s	Performance=992.487664585384 GFLOPS	Total Time (incl. load gauge)=1.379107 s
QUDA_MULTIGRID_CLOVER_LINOP_SOLVER( quda_mg_subspace_l ): 31 iterations. Rsd = 3.96081801501177e-12 Relative Rsd = 4.89693909947036e-12
Exiting quarkProp4
QUDA_MULTIGRID_CLOVER_LINOP_SOLVER( quda_mg_subspace_l ): Destructing
CLOV_LINOP: Time spent in clov deriv (total) = 0
CLOV_LINOP: Time spent in clov apply/invapply (total) = 1.714698
CLOV_LINOP: Time spent in clov deriv (total) = 0
CLOV_LINOP: Time spent in clov apply/invapply (total) = 3.607942
Propagator computed: time= 139.420626 secs
Start writing propagator info
Propagator successfully updated
PROPAGATOR: total time = 167.755017 secs
PROPAGATOR: ran successfully
...
```

The end of the log shows a very low invertQuda / initQuda-endQuda ratio:
```
...
             invertQuda Total time =   115.365 secs
                 download     =     2.490 secs (  2.158%),	 with      120 calls at 2.075e+04 us per call
                   upload     =     2.277 secs (  1.974%),	 with      120 calls at 1.898e+04 us per call
                     init     =    14.053 secs ( 12.181%),	 with      122 calls at 1.152e+05 us per call
                 preamble     =    10.822 secs (  9.381%),	 with      248 calls at 4.364e+04 us per call
                  compute     =    85.311 secs ( 73.949%),	 with      120 calls at 7.109e+05 us per call
                 epilogue     =     0.377 secs (  0.327%),	 with      360 calls at 1.048e+03 us per call
                     free     =     0.011 secs (  0.010%),	 with      360 calls at 3.160e+01 us per call
        total accounted       =   115.341 secs ( 99.979%)
        total missing         =     0.024 secs (  0.021%)

                endQuda Total time =     0.025 secs

       initQuda-endQuda Total time =  3506.357 secs
...
```

**Comment by mathiaswagner** [comment]
Not sure whether this is a QUDA issue then. @bjoo thoughts?

**Comment by SaltyChiang** [comment]
It seems more likely to be an issue from Chroma instead of QUDA. Low `invertQuda / (initQuda - endQuda)` means that Chroma takes too much time to run.
Maybe you could check if you have set `--enable-openmp` while configuring QDPXX.

**Comment by wittscien** [comment]
Thanks for the comments. I did set `-DQDP_USE_OPENMP=ON` when CMaking QDPXX.

**Comment by SaltyChiang** [comment]
The `CMakeLists.txt` in qdpxx/devel branch has something wrong. `QDP_USE_OMP_THREADS` macro is not actually set. Using autoconf to do the configuration should be fine.
If you want CMake to work, you could add `set(QDP_USE_OMP_THREADS ${QDP_USE_OPENMP})` just under this [line](https://github.com/usqcd-software/qdpxx/blob/5be4523296529f62e5b11323f3d3dc4e6f0dada6/CMakeLists.txt#L172).

**Comment by bjoo** [comment]
Hi All,
 Just catching up with this.
 I think one also neede to set a -DCHROMA_ENABLE_OPENMP=ON or some such, however there will always be an issue when using QDP++ (and not QDP-JIT) since reconstruction and error checking is done on the host. This does take up a lot of hidden time.  A refactoring for QUDA to do the reconstruction instead of Chroma in this case, is on our to-do. I am not sure how we can turn off Host side Residuum checking in a nice way. That will always take time.

Best,
 B

--
Balint Joo,  Oak Ridge Leadership Computing Facility,
Oak Ridge National Laboratory
P.O. Box 2008, 1 Bethel Valley Road, Oak Ridge, TN 37831, USA
email: joob AT ornl.gov.  Tel: +1-757-912-0566 (cell, remote)

From: Haobo Yan ***@***.***>
Reply-To: lattice/quda ***@***.***>
Date: Tuesday, November 15, 2022 at 9:52 AM
To: lattice/quda ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lattice/quda] Plenty of time was wasted when calculating the propagators (Issue #1335)
Resent-From: ***@***.***>
Resent-Date: Tuesday, November 15, 2022 at 9:52 AM


Thanks for the comments. I did set -DQDP_USE_OPENMP=ON when CMaking QDPXX.

**Comment by wittscien** [comment]
Thank @SaltyChiang and @bjoo for the valuable advice. I have taken some time and tried the change. Adding the `QDP_USE_OMP_THREADS` setting in qdpxx/devel `CMakeLists.txt` solve the problem. I can see `QDP use OpenMP threading` and improvement of efficiency. Although the default `-DCHROMA_ENABLE_OPENMP` is OFF, `OMP` still works. I think I should mention this issue in qdpxx project later.

**Comment by mathiaswagner** [comment]
Closing this here as not a QUDA issue. @wittscien if you create a follow-up issue for QDPXX or Chroma feel free to link it here.

**Comment by bjoo** [comment]
I think if you do not enable OpenMP in Chroma, you will not get clover and stouting to be threaded.

Best,
 B

--
Balint Joo,  Oak Ridge Leadership Computing Facility,
Oak Ridge National Laboratory
P.O. Box 2008, 1 Bethel Valley Road, Oak Ridge, TN 37831, USA
email: joob AT ornl.gov.  Tel: +1-757-912-0566 (cell, remote)

From: Haobo Yan ***@***.***>
Reply-To: lattice/quda ***@***.***>
Date: Wednesday, November 16, 2022 at 9:51 AM
To: lattice/quda ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lattice/quda] Plenty of time was wasted when calculating the propagators (Issue #1335)
Resent-From: ***@***.***>
Resent-Date: Wednesday, November 16, 2022 at 9:51 AM


Thank @SaltyChiang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SaltyChiang&d=DwMFaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=WG01dcOd8ZFLFFNkrpbj6A&m=B8nKxTLipoN207WBn0SxtHeA6ftuXIDGonrhrT_PoVqYu3seHYNv8dlA8yxrEyMK&s=PEJ0eg5xSO1zN8KEnOxgTcGDCulaJoh5aiSH9nCDAv4&e=> and @bjoo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bjoo&d=DwMFaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=WG01dcOd8ZFLFFNkrpbj6A&m=B8nKxTLipoN207WBn0SxtHeA6ftuXIDGonrhrT_PoVqYu3seHYNv8dlA8yxrEyMK&s=uvucDixWWOSzU3nHd9u4zhsYuZrUByzSkDzqjgADlUU&e=> for the valuable advice. I have taken some time and tried the change. Adding the QDP_USE_OMP_THREADS setting in qdpxx/devel CMakeLists.txt solve the problem. I can see QDP use OpenMP threading and improvement of efficiency. Although the default -DCHROMA_ENABLE_OPENMP is OFF, OMP still works. I think I should mention this issue in qdpxx project later.

**Comment by wittscien** [comment]
I see, thanks @bjoo.

**Comment by wittscien** [comment]
@SaltyChiang A follow-up -- while I find one of the machines works fine (great improvement in efficiency) after adding `QDP_USE_OMP_THREADS` setting in qdpxx/devel `CMakeLists.txt`, there is no improvement in efficiency on another machine (The log now prints `QDP use OpenMP threading` though). I installed them in the same way and used the same sbatch script. Do you know any possible issues that cause the problem?

**Comment by maddyscientist** [comment]
@wittscien could the issue be related to binding?  Are the threads being allocated to their own cores?  We have instructions for creating job binding scripts [here](https://github.com/lattice/quda/wiki/Multi-GPU-Support/#gpu-direct-rdma-and-cuda-aware-mpi) in case this helps.  (Look at how we use the `CPU_REORDER` variable to set `numactl`.)

**Comment by wittscien** [comment]
@maddyscientist Looks like setting `numactl` does not improve the efficiency. And OMP_NUM_THREADS has not a bit of help. I use only one V100 card. Seems very weird.

**Comment by SaltyChiang** [comment]
@wittscien No idea now. Maybe you should write a simple program to check if the machine could handle OpenMP normally.

**Comment by bjoo** [comment]
Hmmm… Did you set environment variables (OMP_NUM_THREADS? Etc?)
Best,
B

--
Balint Joo,  Oak Ridge Leadership Computing Facility,
Oak Ridge National Laboratory
P.O. Box 2008, 1 Bethel Valley Road, Oak Ridge, TN 37831, USA
email: joob AT ornl.gov.  Tel: +1-757-912-0566 (cell, remote)

From: Haobo Yan ***@***.***>
Reply-To: lattice/quda ***@***.***>
Date: Wednesday, November 16, 2022 at 11:45 PM
To: lattice/quda ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lattice/quda] Plenty of time was wasted when calculating the propagators (Issue #1335)
Resent-From: ***@***.***>
Resent-Date: Wednesday, November 16, 2022 at 11:44 PM


@SaltyChiang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SaltyChiang&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=WG01dcOd8ZFLFFNkrpbj6A&m=TimN29T9eZjTjjqJ3zlgn5d8J5tJIhqsCA4n6hRgN6qEibZDB6hfR53MU8qnaaoq&s=Hn8WfdyLrqaivXTzttSo9tvv82T_zp5goP9I_VkdB6w&e=> A follow-up -- while I find one of the machines works fine (great improvement in efficiency) after adding QDP_USE_OMP_THREADS setting in qdpxx/devel CMakeLists.txt, there is no improvement in efficiency on another machine (The log now prints QDP use OpenMP threading though). I installed them in the same way and used the same sbatch script. Do you know any possible issues that cause the problem?

**Comment by wittscien** [comment]
Thank you for the comments. Yes, I have exported `OMP_NUM_THREADS`, and the output of a Chroma program prints on the first line `QDP use OpenMP threading. We have x threads` as expected  @bjoo. But it just does not do it honestly -- if I use `top` to show the processes, I see only one thread with 100% CPU usage. I wrote a simple code and it does allocate the specified threads @maddyscientist.
