### ISSUE TITLE
Use Kahan summation to accumulate (high-precision) solution in CG 

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#135]
The precision of the accumulator seems to be crucial for the stability of the CG with reliable updates.
Instead of setting xsloppy to zero after reliable update store the 'lost' digits as used in Kahan summation in xsloppy.
See also http://en.wikipedia.org/wiki/Kahan_summation_algorithm

**Comment by maddyscientist** [comment]
For posterity: we have a robust solver now simply using a high precision accumulator vector that seem robust.  Other, unrelated efforts, to improve mixed precision CG, and other solver, robustness are ongoing.
