### ISSUE TITLE
CPS staggered phase in QUDA is different from CPS and Chroma's convention.

### ISSUE THREAD

**Issue by SaltyChiang** [lattice/quda#1408]
We can choose three different conventions while using `staggeredPhaseQuda` to apply the staggered phase to a gauge field. `QUDA_STAGGERED_PHASE_CPS` should apply the CPS software's staggered phase, which is also chosen as default by Chroma.

[CPS](https://github.com/RBC-UKQCD/CPS_public/blob/aa71becd7f0f020092391909de2dc75ef065aab2/cps_pp/src/util/lattice/convert/convert_func.C#L84)' and [Chroma](https://github.com/JeffersonLab/chroma/blob/78c0ecff623e38d86ac8f9bf7af93dd6cf841fd5/lib/util/gauge/stag_phases_s.cc#L40)'s implementations can be found here, and I believe they are applying phases like $\psi^\prime(x,y,z,t)=\gamma_1^{x}\gamma_2^{y}\gamma_3^{z}\gamma_4^{t}\psi(x,y,z,t)$.

But in [QUDA](https://github.com/lattice/quda/blob/08a5a9b4f761bfb9cc07e49bd2d3e17bb1434b86/include/kernels/gauge_phase.cuh#L66) with `QUDA_STAGGERED_PHASE_CPS`, it looks like the phases are $\psi^\prime(x,y,z,t)=\gamma_1^{x+1}\gamma_2^{y}\gamma_3^{z}\gamma_4^{t}\psi(x,y,z,t)$,  and are different from the implementations above.

**Comment by maddyscientist** [comment]
@SaltyChiang this is likely just a bug that I introduced.  There's no current users of the `QUDA_STAGGERED_PHASE_CPS` when interfacing with QUDA, so we likely just missed this.

While you could just file a PR with the fix (not including the changes in #1409 while discussion is ongoing there)?

**Comment by SaltyChiang** [comment]
#1409 closes the issue as it removes `QUDA_STAGGERED_PHASE_CPS` enum.
