### ISSUE TITLE
Constrain the tuning space for host <-> device MILCSiteOrder gauge field copies

### ISSUE THREAD

**Issue by weinbe2** [lattice/quda#1451]
At larger local volumes, the host <-> device MILCSiteOrder tuning can take a long time since at best it's constrained by raw PCIe bandwidth. Trimming the tuning space would give a non-negligible boost to autotuning time.

**Comment by maddyscientist** [comment]
#1441 will fix this (disable shared memory tuning for the copy gauge kernels)

**Comment by weinbe2** [comment]
Closed by #1441
