### ISSUE TITLE
ApplyLaplace no longer supports nSpin=4

### ISSUE THREAD

**Issue by aniketsen** [lattice/quda#1475]
While preparing a pull request for an interface for Yang--Mills gradient flow (https://arxiv.org/abs/1302.5246), I realized that the support for nSpin=4 in the `ApplyLaplace` interface was removed in the commit a127fcc97ca2e074fe60595f6dd2389100763637. This breaks the implementation for our test case (Twisted Fermion). But if I understand correctly, other existing interfaces such as `performWuppertalnStep` would also break for any discretization other than Staggered. Is there an intended work around for this issue?

**Comment by maddyscientist** [comment]
Apologies for this oversight @aniketsen.  I will fix this shortly.  Thanks in advance for the upcoming PR 😄

**Comment by aniketsen** [comment]
Thank you @maddyscientist

**Comment by kostrzewa** [comment]
Fixed by https://github.com/lattice/quda/commit/e67a767b1b741444582b79e3e63fdcb1fd30d589 I guess, right?

**Comment by maddyscientist** [comment]
Yes, this is fixed.  We can close this issue.

**Comment by kostrzewa** [comment]
Thanks @maddyscientist !
