### ISSUE TITLE
Is there supposed to be a `}` at the end of this test name?

### ISSUE THREAD

**Issue by dmcdougall** [lattice/quda#1492]
https://github.com/lattice/quda/blob/4d3236eddfeba114b1a4c892d76b2f382c9fd78a/tests/CMakeLists.txt#L1035

I don't think it's causing any harm.  It just caught my eye.

**Comment by maddyscientist** [comment]
Thanks for the catch @dmcdougall.  I don't know what effect this has, but I guess not good.  I'll fix it in my dev branch.

**Comment by dmcdougall** [comment]
No problem.  Like I said, I'm running tests locally and it doesn't look to be causing harm.  Looks to be a spurious `}` printed to the screen as part of the test name.

I have no intent or desire to fuzz `ctest` with test names that contain unicode characters :)
