### ISSUE TITLE
This file doesn't run well

### ISSUE THREAD

**Issue by fwinter** [lattice/quda#1499]
Maybe I'm doing something wrong here, but the attached input XML for Chroma/HMC (Nf=2+1, Clover) hits the following problem with Quda/develop (commit 882179286bf):

[test.xml.zip](https://github.com/user-attachments/files/17282923/test.xml.zip)

QUDA_MULTIGRID_CLOVER_MDAGM_SOLVER( Mass = -0.187 , Id = subspace_2416 ):  subspace_update_time = 0.096466 sec. 
QUDA_MULTIGRID_CLOVER_MDAGM_SOLVER( Mass = -0.187 , Id = subspace_2416 ):  init_time = 0.162971 sec. 
QUDA_MULTIGRID_CLOVER_MDAGM_SOLVER( Mass = -0.187 , Id = subspace_2416 ): Two Step Solve
Two Step Solve using QUDA predictor: (Y_index,X_index) = ( 9 , 8 ) 
Setting Default Chrono precision of 8
ERROR: Mismatched sizes a=2 b=1 (rank 0, host desktop, blas_helper.cuh:542 in void quda::check_size(const A&, const B&) [with A = vector_ref<const ColorSpinorField>; B = vector_ref<ColorSpinorField>]())
       last kernel called was (name=N4quda15CopyColorSpinorILi4ELi3ENS_11colorspinor11FloatNOrderIdLi4ELi3ELi2ELb0ELb0ELb0EEES3_St5tupleIJRNS_16ColorSpinorFieldERKS5_19QudaFieldLocation_sPdPKdEEEE,volume=8x16x16x32,aux=GPU-offline,vol=65536,parity=1,precision=8,order=2,Ns=4,Nc=3vol=65536,parity=1,precision=8,order=2,Ns=4,Nc=3)

**Comment by maddyscientist** [comment]
Hi Frank.  Could you send me the entire output of the run?  

This looks a bit like an issue we had some months ago that got fixed, so I'm a bit confused that it's reared its ugly head.  @bjoo has been testing Chroma with a recent version of QUDA, with success.

**Comment by fwinter** [comment]
Hey Kate! Sure, here's the output:

[out.zip](https://github.com/user-attachments/files/17297378/out.zip)

**Comment by fwinter** [comment]
Okay, with the updated branch feature/mrhs-mg and the updated Chroma code this works fine now!

**Comment by bjoo** [comment]
[like]  Balint Joo reacted to your message:
________________________________
