### ISSUE TITLE
Use of bool in quda.h

### ISSUE THREAD

**Issue by V3-vvv** [lattice/quda#1521]
I noticed that `use_smeared_gauge` is declared as a bool in quda.h. This is the first time I've encountered a bool variable in quda.h. However, bool is not a C99 keyword. Could you clarify if this was an intentional choice or if it might require adjustment for C99 compatibility?
https://github.com/lattice/quda/blob/1efcbeb845398d9c963e8191c7cf9c01005eb124/include/quda.h#L508-L510
[https://en.cppreference.com/w/c/keyword/bool](url)

**Comment by maddyscientist** [comment]
This was intentional.  We are moving to the use of `bool` to replace `QudaBoolean`.  Since `quda.h` now includes the  `stdbool.h` header (which was introduced with C99), this is fully C99 compliant.
