### ISSUE TITLE
Covariant derivative gives wrong result after applying an Wilson/Clover-Wilson matrix.

### ISSUE THREAD

**Issue by SaltyChiang** [lattice/quda#1527]
Wilson-like matrix requires the `spin_project`, while covariant derivate and Laplacian operations don't require this. All Dslash kernels use `ColorSpinorField::create_comms_batch` to allocate the halo field, and it actually uses `FieldTmp` in order to reuse these fields. After calling the Wilson-like matrix multiplication, the halo will be allocated with `spin_project=true`. This causes the wrong halo size for covariant derivate and Laplacian.

Fixed in #1523 by commit https://github.com/lattice/quda/pull/1523/commits/ab4d96876118304f982f6a3242d115d2e6458edc.

This issue is only for logging.

**Comment by maddyscientist** [comment]
Closed by #1523
