### ISSUE TITLE
Stout link fattening

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#156]
We should support stout-link creation.  This should be fairly straightforward to implement, using the same approach that APE smearing has been done.

**Comment by maddyscientist** [comment]
Moving this to 0.9.

@bjoo can you add the Chroma file reference for Stout smearing to this bug so I have a reference point to work from?

There's no pressing need to implement this from an application point of view, but having this support in place would make testing the QUDA multigrid solver much easier.

@AlexVaq given you've implemented APE smearing already, I don't support you fancy implementing this as well? :wink:

**Comment by cpviolator** [comment]
@AlexVaq, I have written some Stout smearing routines in CPS for operator smearing. The routine starts at line 959 [here](https://github.com/cpviolator/QUDA-CPS/blob/7afa752496e9e01983b4aba9ce2ca7dd9e16089e/QUDA-CPS_v5_0_26/src/alg/alg_smear/alg_smear.C) and the exponentiation of the matrix Q is written at line 74 [here](https://github.com/cpviolator/QUDA-CPS/blob/7afa752496e9e01983b4aba9ce2ca7dd9e16089e/QUDA-CPS_v5_0_26/src/util/vector/comsrc/vector.C) with a simple sinc(x) function at line 215 in the same file.

I assume that the APE  routine you wrote calculates a three-staple. The STOUT routine can use that to construct the staple \Omega. Everything after that is just algebra. I'll take a look at your APE code and try to transpose my STOUT routine into QUDA. If I fail miserably, my code will at least serve as a C++ guide.

**Comment by maddyscientist** [comment]
That would be fantastic if you can take a look.  I think the APE smearing should be fairly easy to understand as it's written in fairly high-level C++ that abstracts away much of the GPU details.  I'm happy to help if needed.

**Comment by cpviolator** [comment]
Will do. Most of the effort has already been done in writing the CPS code. I'll take a look this afternoon.

**Comment by AlexVaq** [comment]
Yes, I use a simple 3-staple, but going further than that is more of the same. Just look at the field-stress tensor code, for instance.

You might want to check the linkIndex and linkIndexShift functions which allow you to retrieve the index associated to some coordinates, so you can access the gauge field in neighbouring points. And you also need to understand how the extended gauge fields work.

I'll be glad to help, so bother me if you need some guidance to understand the code or to write something specific.

**Comment by cpviolator** [comment]
@AlexVaq Thank you. If I get stuck I'll be sure to ask for help! 👍

**Comment by cpviolator** [comment]
@AlexVaq I have the routine written but I don't know how to test it. Also, which branch of QUDA should I fork to make a pull request?

**Comment by maddyscientist** [comment]
Branch from develop.  If you issue the pull request we can review and decide what to do from there.

If you're using stout smearing in the cps could you use this as the reference to check correctness?

Fast work!

**Comment by cpviolator** [comment]
OK, I think I did that pull request correctly.

I know that the stout smearing works perfectly in CPS. The code I submitted is just a transposition, in that some data types were changed and some matrix operations were shuffled around to account for the new operators. No major changes were needed in the algorithm itself.

**Comment by AlexVaq** [comment]
Sorry for the late reply, Dean. It was 3am here when I got your message.

Even if the code is just a transcription of the CPU routines, I'd suggest that you tested it for correctness. You can, for instance, check the plaquette as the level of smearing increases, and compare it with you CPU code. CUDA and QUDA can be very tricky sometimes.

Also, when testing, be careful with the boundary conditions.

**Comment by cpviolator** [comment]
@AlexVaq I was wondering how this test could be done, checking the plaquette seems like a good idea.

**Comment by AlexVaq** [comment]
It is not the perfect check, but it is what I used for APE. If you get an agreement for ~7 significant figures for an arbitrary number of smearing steps, you can be fairly sure the code is correct.

Mind you, the current interface plaquette routines read directly the gaugePrecise field (maybe we should change this in the future???). I suppose you store your smeared field in gaugeSmeared, so you might want to call quda::plaquette directly, passing gaugeSmeared (which should be an extended gauge field, the plaquette routine requires the gauge field to be extended in multiGPU).

**Comment by cpviolator** [comment]
I think that the method you used for APE will work just as well for STOUT. A 7 sig. fig. agreement should be good enough for anyone! The pull request is [here](https://github.com/lattice/quda/pull/418). Though I made a new file gauge_stout.cu, everything therein is a copy of your APE code. Can you please send me your scripts for APE testing and I will try to do the same testing for STOUT?

**Comment by AlexVaq** [comment]
Uf... I used a custom routine to load custom gauge fields that I generated with a custom HMC program I developed during my PhD... You have writen interfaces so you can just copy su3_test.cpp as a template, load your gauge configuration, and just run the smearing. If you set the verbosity to QUDA_VERBOSE, at the end of the run, you'll get the plaquette (according to your code).

So, I would just add "performSTOUTnStep(XXXXX);" at line 130 of su3_test.cpp. You'll need to load the same gauge-conf that in your CPU code, though.

I sent you a sample code that just adds two lines to su3_text.cpp: one to set the verbosity level, and another one to add the smearing at the end. You should be able to check the output and see if it matches your CPU routines for the same input.

**Comment by cpviolator** [comment]
@maddyscientist Close this now with #540 merged?

**Comment by maddyscientist** [comment]
Yes, we can close it.
