### ISSUE TITLE
Chiral gamma basis and unitarity transformation

### ISSUE THREAD

**Issue by m-schroeck** [lattice/quda#157]
I'd like to implement the optional usage of a third gamma basis and I would be glad to get some help in finding the unitary transformation which performs the basis change. I'm talking about the chiral basis as used by e.g. Martin Lüscher, "Implementation of the lattice Dirac operator", 2006 (unpublished notes, for details see doc/dirac.ps page 11 in the DD-HMC code package: http://luscher.web.cern.ch/luscher/DD-HMC/).

The chiral basis as used by Lüscher has gamma^C_0,...,gamma^C_3 (0 is time, 'C' to refers to chiral) while QUDA (UKQCD) uses gamma^Q_1,...,gamma^Q_4 (4 is time). 

Now, one possibility is to simply convert as

gamma^C_0 -> gamma^Q_4
gamma^C_1 -> gamma^Q_1
gamma^C_2 -> gamma^Q_2
gamma^C_3 -> gamma^Q_3

Therefor I was able to find the corresponding unitary transformation which carries out the basis change. For completeness, that symmetric transformation reads (cp. to copy_color_spinor.cu):

```
int s1[4] = {0, 1, 0, 1};
int s2[4] = {2, 3, 2, 3};
RegTypeOut K1[4] = {-kP, -kP, kP, kP};
RegTypeOut K2[4] = { kP,  kP, kP, kP};
for (int s=0; s<Ns; s++) {
  for (int c=0; c<Nc; c++) {
    for (int z=0; z<2; z++) {
      out[(s*Nc+c)*2+z] = K1[s]*in[(s1[s]*Nc+c)*2+z] + K2[s]*in[(s2[s]*Nc+c)*2+z];
```

Doing it in that way has one problem: gamma_5 collects a minus sign due to the three permutations needed to bring gamma_t (gamma_4 in QUDA) to the front (gamma_0 in the chiral basis). For my personal use (twisted mass) it is sufficient to switch the twisted mass flavor type from plus to minus and vice versa to account for the minus sign. But that's a hack of course.

Possibility number two, which should be the preferred one, aims at transforming like

gamma^C_0 -> gamma^Q_4
gamma^C_1 -> gamma^Q_3
gamma^C_2 -> gamma^Q_2
gamma^C_3 -> gamma^Q_1

i.e. the spatial components are reordered. Then there is no additional minus sign in gamma_5. The problem here is, until now I was not able to find the corresponding unitary transformation. I'm not sure from a theoretical point of view, if there must exist a corresponding transformation, and if yes how to find it.

If you have any idea how to find that transformation, please let me know!

**Comment by kostrzewa** [comment]
This is a problem which may surface again, as far as I can tell. When QUDA (or another library, QPhiX, say) is used to do HMC using a **red-black preconditioned effective action** with a code which has a different gamma convention AND a different ordering of dimensions.

For exchanging between the chiral and the DeGrand-Rossi basis, while exchanging, at the same time, Q_1 and Q_3:

gamma^C_0 -> gamma^Q_4 = V^dagger gamma^C_0 V
gamma^C_1 -> gamma^Q_3 = V^dagger gamma^C_1 V
gamma^C_2 -> gamma^Q_2 = V^dagger gamma^C_2 V
gamma^C_3 -> gamma^Q_1 = V^dagger gamma^C_3 V

The required similarity transformation is, as far as I can tell:

```
       1/      1 -1 0  0
V =  sqrt(2)   0  0 1  1
               0  0 1 -1
               1  1 0  0 
             
```

where it might be that the rows need to be reordered.

However, if one now also exchanges the X and Z dimensions in the Dirac operator, even with the above transformation, the action of the Dirac operator is not preserved, of course...
