### ISSUE TITLE
computeAsqtadForceQuda and computeStaggeredOprodQuda are hard-coded to use QDP field ordering

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#160]
In interface_quda.cpp, computeAsqtadForceQuda and computeStaggeredOprodQuda are hard-coded to use QDP field ordering for cpu fields.  I have no idea why, but it appears that this is the order the routines are expecting the CPU fields to come in, which isconfusing since I would have thought MILC would have used a consistent ordering.

This should be avoided, since 1.) we should be not be hard-coding field orderings, they should be interface options, and 2.) forcing the user to use MILC + QDP field ordering makes the compile time completely unwieldy.

Assigning to Justin.

**Comment by mathiaswagner** [comment]
With my confusion in #301:

Until we have a fix of that we might throw an error using `#error` if `GPU_STAGGERED_OPROD` is defined and `BUILD_QDP_INTERFACE` is not defined like we do e.g. for the asqtad force and Multi GPU runs. I hope I remembered that correctly.

**Comment by mathiaswagner** [comment]
Guess the compilation warning should make it into 0.7.2 and the proper fix then into 0.8

**Comment by mikeaclark** [comment]
Sounds like a plan.

**Comment by maddyscientist** [comment]
Closing issue.  This was fixed when we fused the HISQ path force and outer product computation into a single interface call.
