### ISSUE TITLE
Automated regression testing

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#165]
It's time we put together automated nightly regression testing for QUDA.  Doing so is critical to the health of QUDA and sanity of the developers.  This issue is to track this.  We should automate the building of QUDA across a few different configure options (single, MPI and QMP) and run all unit tests across a wide spectrum of tests.

Does anyone have any suggestions on this?  This could be done with some scripting, though I'm happy to hear any suggestions.

**Comment by weinbe2** [comment]
Closed by https://github.com/lattice/quda/issues/371 along with the more recent automatic correctness runs enabled through github actions
