### ISSUE TITLE
Complete merge of cudaColorSpinorField ghost+norm data

### ISSUE THREAD

**Issue by jpfoley** [lattice/quda#172]
In most branches of quda, including quda-0.7, the ghost (halo) quark-field data needed in the multi-GPU dslash kernels are stored in the same arrays as the interior data. Hence, in single and double precision,  ghost data are stored in the array pointed to by the "v" member in cudaColorSpinorField. Similarly, in the half-precision path, ghost-norm data are stored in the "norm" array. The fact that half-precision ghost and ghost-norm data are stored in different arrays has significant performance implications since it means that the number of MPI Comms calls/Host-device copies needed in half precision is double the number needed in the single- and double-precision build.

In the gpu_comms_debug branch, I have added a separate ghost_field array to cudaColorSpinorField, such that the ghost and ghost-norm data needed to apply dslash to a single boundary region (the front/back boundary in a given space-time dimension) are stored contiguously. Hence, the number of MPI calls/Host-device copies needed for half precision should be the same as single/double precision. 

To facilitate this, I modified the int ghostOffset[QUDA_MAX_DIM] array in cudaColorSpinorField to be int ghostOffset[QUDA_MAX_DIM][2], where the right-most index selects between offsets for the front/back boundary regions. I also modified the getter method GhostOffset(dim) -> GhostOffset(dim,front/back), etc. 

I have tested this feature in various dslash operators on a K40 with texture objects enabled and GPU Comms disabled, and all the multi-GPU dslash operators appear to work, EXCEPT for non-degenerate twisted mass. I haven't had much time to look at this, and I fully expected the half-precision code to fail, but it seems that single- and double-precision are also incorrect.

My feeling is that the quickest way to get twisted-mass working would be for Alexei to take a look. 
Also, I know that my changes to the ghost pointers and data layout has likely broken Alexei's eigenvector code, but I haven't looked at that either.

The staggered outer-product code is also affected by the changes to the ghost storage. Over the weekend, I implemented a new ghostLoad method for the Spinor class used in the outer-product kernel, which compiles but hasn't been tested. 

Also, at the moment, textures need to be enabled for the code to work. Extending support to the direct-access path should be straightforward. It just requires some tweaking of the kernel arguments.

Before this can be merged into quda-0.7, the following has to be done:

The twisted-mass/eigenvector issues must be resolved
The staggered outer-prod must be verified 
Direct access needs to be enabled and verified
Texture references (pre-Kepler) need to be verified
Performance tests need to be performed to ensure my changes to the dslash kernels haven't adversely affected performance

**Comment by maddyscientist** [comment]
Closing issue, since this is long since completed.
