### ISSUE TITLE
FloatNOrder load and save performance issues

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#176]
Last tests that I made to the load and save from FloatNOrder<...,...,...> seems that these functions adds too much register pressure, also these functions does not take also in account the best way to access GPU memory.

for example, defining the following way the load and save, at least in the gauge fixing code with overrelaxation, I notice around 25% increase in performance for double precision.
I think with some more little tweaks and more specializations, perhaps, we can get more performance.

template<>
__device__ __host__ inline void FloatNOrder<double, 18, 2, 18>::load(RegType v[18], int x, int dir, int parity) const {
        const int M = 9;
        RegType tmp[18];
        double2 **gaugein = (double2**)gauge;
        for (int i=0; i<M; i++) 
            ((double2*)tmp)[i] = gaugein[parity][x + dir*stride*9 + stride*i];
        /*for (int i=0; i<M; i++) {
          for (int j=0; j<2; j++) {
            int intIdx = i*2 + j; // internal dof index
            int padIdx = intIdx / 2;
            copy(tmp[i*2+j], gauge[parity][dir*stride*18 + (padIdx*stride + x)*2 + intIdx%2]);
          }
        }*/
        RegType phase = 0.;
#if __COMPUTE_CAPABILITY__ >= 200
        if(hasPhase) copy(phase, gauge[parity][phaseOffset/sizeof(double) + stride*dir + x]);
        // The phases come after the ghost matrices
#endif
        reconstruct.Unpack(v, tmp, x, dir, 2.*M_PI*phase);
      }

template<>
__device__ __host__ inline void FloatNOrder<double, 18, 2, 18>::save(const RegType v[18], int x, int dir, int parity) {
        const int M = 9;
        RegType tmp[18];
        reconstruct.Pack(tmp, v, x);
        double2 **gaugeout = (double2**)gauge;
        for (int i=0; i<M; i++) 
            gaugeout[parity][x + dir*stride*9 + stride*i] = ((double2*)tmp)[i];

        /*for (int i=0; i<9; i++) {
          for (int j=0; j<2; j++) {
            int intIdx = i*2 + j;
            int padIdx = intIdx / 2;
            copy(gauge[parity][dir*stride*18 + (padIdx*stride + x)*2 + intIdx%2], tmp[i*2+j]);
          }
        }*/
#if __COMPUTE_CAPABILITY__ >= 200
        if(hasPhase){
          RegType phase;
          reconstruct.getPhase(&phase,v);
          copy(gauge[parity][phaseOffset/sizeof(double) + dir*stride + x], static_cast<RegType>(phase/(2.*M_PI))); 
        }        
#endif
      }

**Comment by mikeaclark** [comment]
This was closed with 7a91e92e1ecd4083cf15eb4c9b9e9ac2105b830b
