### ISSUE TITLE
Reproducibility of multi-GPU half precision

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#180]
The half precision dslash will not give exact reproducible results due to the change in normalization between 24 and 12 numbers.  We should work out a way to fix this.

**Comment by weinbe2** [comment]
@maddyscientist is this still relevant? If not, can you close it?

**Comment by maddyscientist** [comment]
Good call @weinbe2.  This has long since been addressed thought removing the pure copy engine path for handling the T-dimension boundary exchange (taken care of around generic kernels rewrite I think).
