### ISSUE TITLE
FloatNOrder performance issues

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#181]
using for example FloatNOrder<double, 18, 2, 18> and looking at ptx file, shows loading/saving 64bit 
which should be loading/saving 128bit

also
Float *gauge[2];
worse than declare
Float *gaugeeven;
Float *gaugeodd;

This was tested in a Tesla Fermi GPU for the gauge fixing overrelaxation code.

**Comment by mikeaclark** [comment]
Closing this bug, as it is taken care of in pull #253.
