### ISSUE TITLE
Add texture support for field accessors

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#186]
The present field accessors, in particular the gauge, colorspinor and clover accessors, do not utilize textures for loading and instead uses only direct loading.  This can cause sub-optimal performance, since on Kepler this will mean a lack of caching of these variables.  We can add this using texture objects only, since there is less need to have Fermi support for this since Fermi is unlikely to be used for mass production and Fermi has an L1 cache which minimizes the performance loss.  In the short-term we could add __ldg support that would give caching and more loads in flight, though this would not help half-precision performance.

**Comment by mathiaswagner** [comment]
I have not checked but with Nuno's work and the default use of `__ldg` is that still an issue? Of course there is still a lot of old code that doesn't use Nuno'  accessors.

**Comment by maddyscientist** [comment]
Closing, since texture supprt in the accessors has long since been implemented.
