### ISSUE TITLE
Optimize mobius dslash kernels and strong scaling

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#193]
The present Mobius Dslash kernels are not optimal in either raw performance or with respect to strong scaling.  The current implementation of the asymmetrically preconditioned Mobius matrix-vector application looks like this:

```
    Dslash4pre(*tmp1, in, QUDA_ODD_PARITY);
    Dslash4(out, *tmp1, QUDA_EVEN_PARITY);
    Dslash5inv(*tmp1, out, QUDA_ODD_PARITY, kappa5);
    Dslash4pre(out, *tmp1, QUDA_EVEN_PARITY);
    Dslash4(*tmp1, out, QUDA_ODD_PARITY);
    Dslash5Xpay(out, in, QUDA_EVEN_PARITY, *tmp1, 1.0);
```

where Dslash4 is the 4-d dslash, Dslash4pre and Dslash5 are variations on the dslash on the fifth dimension only and Dslash5inv is the analytically inverted fifth dimension dslash.  In general, the fifth dimension is kept local to a GPU, and communication only occurs over the four space-time dimensions.  There exists multiple opportunities for optimization here:

**Multi-GPU communication**: this only occurs in Dslash4, with all other kernels being local to a GPU.  However, when we try to hide the communication for dslash4, we only attempt to overlap it with the computation on the interior of dslash4.  We could just as well overlap this communication with the computation of Dslash4pre, Dslash5inv and Dslash5 since all these kernels use only local computation.  This optimization would drastically increase the amount of local-computation with which we can overlap with giving significantly better strong scaling.  This refactoring is much easier if we are able to do kernel fusion, since there it essentially comes for free.  If not, we may have to introduce a new dslash policy, since the present multi-GPU strategies rely on a single kernel for the interior region with which to overlap with.

**Optimization of Dslash4pre and Dslash5**: these kernels currently sustain just a bit north of 120 Gflops on a K40, and are the slowest kernels being completely memory bandwidth bound.  This is easy to see with some back-of-the-envelope modeling: Dslash4pre does 168 flops per site, and requires the loading of 3 spinors and saving of 1.  This gives an arithmetic intensity of 0.44, and given a sustained memory bandwidth of 220 GB/s we get 100 Gflops.  We see a bit more performance because the texture cache gives us some caching across Ls.  However, this caching is highly limited because of texture cache size:  The smallest extent of the space-time dimension is 32 sites (minimum thread block x-size of a warp), so for Ls=16, we would need 48 KiB to get perfect caching (in single precision).  On Kepler each individual the texture cache pool is 12 KiB, of which there are four per SM (on Maxwell it is 2x 24 KiB per SM): neither give enough to give perfect caching.  If we had perfect caching over Ls, the arithmetic intensity increases to 0.9 (one spinor load and spinor save), and the performance would increase to 200 Gflops.  

There are a couple of options to get better caching across Ls here:
1. Decrease the thread block x dimension to 8 or 16.  This will reduce the width of the block, allowing for a greater height to be cached.  This is not necessarily a win since the x dimension will have less threads than a warp, but it should not affect memory coalescing since 128-bit memory transaction occur at quarter-warp granularity.
2. Utilize shared memory to cache across the Ls dimension.  This is motivated by the fact that the shared memory pool is 48 KiB, thus it could store space-time width of 32 and the full Ls=16 height.  This could be used in congestion with decreased x thread block size as well.

**Kernel fusion**: there exists a lot of scope for kernel fusion in these kernels since Dslash4 is the only kernel that has space-time dependence.  For a given space-time volume, if we are able to keep the entire extent of the Ls dimension local to a thread block, then we could in principle merge Dslash4pre / Dslash4 / Dslash5inv and Dslash4pre / Dslash4 / Dslash5Xpay into a single kernel.  We would use the shared memory to easily facilitate this fusion.  With this optimization in place, we would be relying on L2 cache for doing all space-time locality caching.

For how best to approach these optimizations we should discuss as to what the expected sizes of Ls are for Mobius dwf in the near future.  For example if Ls <= 16 then we could utilize extremely aggressive optimizations.  For larger Ls, some of the optimizations will become much trickier.

If we are able to implement all of these optimizations, especially kernel fusion, we obtain an estimated doubling in performance of the overall matrix-vector operation, which would likely see a single K40 achieve 1 Tflops in single precision, as well as having superior strong scaling.  Due to the high amount of locality in the Mobius operator, it may turn out to be the ideal operator for GPUs.

**Comment by mikeaclark** [comment]
I've noticed that there is a lot of unnecessary integer division occurring in the 4-d dslash operator.  The fact that this indexing overhead has an impact on performance can be seen by the fact that the regular Wilson dslash is 5% faster than the 4-d dslash as Ls=1.  At larger Ls when we are less memory bandwidth this will have a bigger effect on performance.
