### ISSUE TITLE
provide support for half precision eigCG

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#194]

**Comment by maddyscientist** [comment]
@alexstrel with your mixed-precision eigCG, has this been completed?

**Comment by alexstrel** [comment]
I think it's still a valid issue. We discussed this point in the context of the low mode computing for multigrid. (current mixed precision is designed for single precision eigCG, with half precision reserved for cg corrections). on the other hand I believe gmresdr might be more relevant for this purpose.

**Comment by alexstrel** [comment]
resolved in https://github.com/lattice/quda/pull/612
