### ISSUE TITLE
problem with staggered_dslash_test

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#200]
Rich has requested a weak scaling study, so I am trying staggered_dslash_test.  I am having trouble running multiple gpu jobs.  I compiled QUDA for multi-gpu.  Here is how I launch a job on a cray:
aprun -n 4 -N 1 /N/u/sg/BigRed2/quda-0.7.0/tests//staggered_dslash_test --prec double --xdi
m $nx --ydim $ny --zdim $nz --tdim $nt --xgridsize 1 --ygridsize 1 --zgridsize 2 --tgridsiz
e 2 >>out_4procs.$ns

Here is what shows up in output:
Tue Dec 16 09:11:07 EST 2014
-rwxr-xr-x 1 sg phys 192887697 Dec  4 02:25 /N/u/sg/BigRed2/quda-0.7.0/tests/staggered_dsla
sh_test
running the following test:
prec recon   test_type     dagger   S_dim         T_dimension
double   18       0           0       24/24/48        48 
Grid partition info:     X  Y  Z  T
                         0  0  1  1
Found device 0: Tesla K20
Using device 0: Tesla K20
Setting NUMA affinity for device 0 to CPU core 0
WARNING: Environment variable QUDA_RESOURCE_PATH is not set.
WARNING: Caching of tuned parameters will be disabled.
Randomizing fields ...

**Comment by mikeaclark** [comment]
Closing.
