### ISSUE TITLE
Mixed precision (staggered) multi shift: Bad true residual of higher shifts without refinement

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#205]
I tried running the staggered mixed-precision multi shift solver (actually for use with the HQ residual so without QUDA internal refinement). I noticed that the higher shifts show a very bad residual after the multi shift (no refinement).

For a pure double precision solver I see:

```
 ./staggered_invert_test --test 3 --prec double --prec_sloppy double
[...]
MultiShift CG: Converged after 17819 iterations
 shift=0, relative residual: iterated = 9.979375e-08, true = 9.979375e-08
 shift=1, relative residual: iterated = 9.969635e-08, true = 9.969635e-08
 shift=2, relative residual: iterated = 9.955073e-08, true = 9.955073e-08
 shift=3, relative residual: iterated = 9.773965e-08, true = 9.773965e-08
 shift=4, relative residual: iterated = 9.826791e-08, true = 9.826791e-08
 shift=5, relative residual: iterated = 9.635956e-08, true = 9.635956e-08
 shift=6, relative residual: iterated = 9.523719e-08, true = 9.523719e-08
 shift=7, relative residual: iterated = 9.861741e-08, true = 9.861741e-08
 shift=8, relative residual: iterated = 9.768502e-08, true = 9.768502e-08
 shift=9, relative residual: iterated = 9.816970e-08, true = 9.816970e-08
 shift=10, relative residual: iterated = 9.439289e-08, true = 9.439289e-08
 shift=11, relative residual: iterated = 9.679432e-08, true = 9.679432e-08
[...]
```

but for double-single I see

```
./staggered_invert_test --test 3 --prec double --prec_sloppy single
[...]
MultiShift CG: Converged after 17890 iterations
 shift=0, relative residual: iterated = 9.959490e-08, true = 9.959490e-08
 shift=1, relative residual: iterated = 9.962611e-08, true = 7.459438e-03  <-- this goes particularly wrong
 shift=2, relative residual: iterated = 9.940093e-08, true = 9.162059e-04 
 shift=3, relative residual: iterated = 9.805886e-08, true = 7.841102e-06
 shift=4, relative residual: iterated = 9.922683e-08, true = 6.400741e-06
 shift=5, relative residual: iterated = 9.667337e-08, true = 5.854922e-06
 shift=6, relative residual: iterated = 9.897065e-08, true = 3.811663e-06
 shift=7, relative residual: iterated = 9.783382e-08, true = 3.149529e-06
 shift=8, relative residual: iterated = 9.628420e-08, true = 2.622094e-06
 shift=9, relative residual: iterated = 9.650005e-08, true = 2.232050e-06
 shift=10, relative residual: iterated = 9.857203e-08, true = 1.924465e-06
 shift=11, relative residual: iterated = 9.760398e-08, true = 9.032575e-07
[...]
```

The true residuals are nowhere close to the iterated ones. This requires a lot of refinement iterations and probably eats up a lot of the performance increase over a pure double solver. (No timings here but I believe we can do better here).

I am not yet sure why this happens but things to look at include my ideas mentioned in #204.

Apart from that I can think of
- We do not use  Polak–Ribière here. But that would probably already show up in the zeroth shift and should be more relevant for half precision.
- Do we need to feed back the recalculated residual in the calculation of the multi shift coefficients? Don't know whether we have to but right now it looks like we don't.

I don't think it is an issue with using reliable updates. When only using one precision (i.e. double / double) turning the reliable updates on and off did not cause any significant change for the higher shifts.

**Comment by mikeaclark** [comment]
Yes, I'm aware of this issue.  I did a thorough exploration of this previously, and could not get the first shift to converge better.  Note that this is significantly better than it used to be.  I'd be delighted if you work out how to improve this better :)

- Indeed, we should add the Polak–Ribière to the multi-shift solver, but as you note this won't fix this issue.
- On recalculating the multi-shift coefficients some improvement may be possible.  It's been a while since I looked at this.
- One improvement would be when doing the refinement stage after the multi-shift solver, would be to form to reuse the other solutions as initial guesses in a minimum residual extrapolation.
- It wouldn't surprise me if the only way to fix this is to keep more vector in high precision, and just do the matrix-vector product in low precision.

Note that if Alexei gets GMRES-DR working, this might be a good replacement.  I understand that GMRES-DR allows for a multi-shift formulation with restarts.

**Comment by mathiaswagner** [comment]
Do you remember if there was anything you tried that did not improve shift 1? Just so I don't replicate the things that don't help.

**Comment by mathiaswagner** [comment]
Just to keep the idea: For the refinement use the multi shift and drop the lowest shift. I.e. for the first refinement use a multi shift on the shifts (1,...,n). Then refine shift 2 with a multi shift (2,...n). 
No idea who that does in terms of performance but it *might* reduce the number of iterations needed to work on the higher shifts.

**Comment by mikeaclark** [comment]
If I understand correctly, you want to use multi-shift for the refinement of the remaining shifts that have not converged?  This won't work, or at least it won't work well I think.  The multi-shift solver requires that all residuals of the shifted systems are co-linear, for which the trivial solution is to set the initial guess to zero.

This means that the multi-shift solver cannot be applied to the restarted system because all shifts will have a different initial guess that will lead to different residuals that are not co-linear.

For some background on reading about restarting the multi-shift paper, check out James Osborn's proceedings where he played with this: http://arxiv.org/abs/0810.1081

**Comment by mathiaswagner** [comment]
Obviously true. Should have thought of that right away.

**Comment by mathiaswagner** [comment]
A little bit more insight: I have recalculated the true residuals in the reliable update (only for reference whether the shifted residual is still accurate, it does not enter in the solver). Here is what I get for shift 1 in each of the reliable updates for above example (double/single).

```
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.221458e+05  ,  3.221458e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.304458e+05  ,  3.304457e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.226115e+05  ,  3.226116e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.317614e+05  ,  3.317616e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.270335e+05  ,  3.270338e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.225397e+05  ,  3.225392e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.136755e+05  ,  3.136762e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 3.231398e+05  ,  3.231385e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.990884e+05  ,  2.990878e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.996623e+05  ,  2.996597e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.898558e+05  ,  2.898538e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.692438e+05  ,  2.692391e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.511281e+05  ,  2.511351e+05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 8.914206e+04  ,  8.913639e+04
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.180786e+04  ,  2.178387e+04
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 5.077261e+03  ,  5.058047e+03
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.143973e+03  ,  1.125351e+03
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 2.763163e+02  ,  2.590397e+02
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 7.406093e+01  ,  5.558624e+01
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.880156e+01  ,  6.025257e-01
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.820940e+01  ,  6.209528e-03
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.820546e+01  ,  6.307407e-05
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.820502e+01  ,  6.528759e-07
MultiShiftCG Reliable update Shift 1 (true_res, multishift_res) 1.820505e+01  ,  6.673349e-09
```

Note that the true residual seems to be stuck at 1.8 while the shifted residual still goes on.

Not yet sure what to make with that ...

**Comment by mathiaswagner** [comment]
I have done some more investigating and turned off the reliable updates but still use mixed precision (well, it is more like doing just single precision ..., anyway what I did was `reliable = false`).
The results after the multi shift is
```
MultiShift CG: Reliable updates = 0
MultiShift CG: Converged after 17887 iterations
 shift=0, relative residual: iterated = 9.870553e-08, true = 1.206450e-04, requested = 1.000000e-07
 shift=1, relative residual: iterated = 9.995064e-08, true = 7.399396e-03, requested = 1.000000e-07
 shift=2, relative residual: iterated = 9.979693e-08, true = 8.823036e-04, requested = 1.000000e-07
 shift=3, relative residual: iterated = 9.883701e-08, true = 7.676612e-06, requested = 1.000000e-07
 shift=4, relative residual: iterated = 9.926020e-08, true = 6.326678e-06, requested = 1.000000e-07
 shift=5, relative residual: iterated = 9.960939e-08, true = 5.752897e-06, requested = 1.000000e-07
 shift=6, relative residual: iterated = 9.893516e-08, true = 3.775052e-06, requested = 1.000000e-07
 shift=7, relative residual: iterated = 9.608154e-08, true = 3.136919e-06, requested = 1.000000e-07
 shift=8, relative residual: iterated = 9.650913e-08, true = 2.619575e-06, requested = 1.000000e-07
 shift=9, relative residual: iterated = 9.642115e-08, true = 2.239486e-06, requested = 1.000000e-07
 shift=10, relative residual: iterated = 9.696037e-08, true = 1.931043e-06, requested = 1.000000e-07
 shift=11, relative residual: iterated = 9.760398e-08, true = 9.086576e-07, requested = 1.000000e-07
```

Obviously there is a large difference to the run with reliable updates for shift 0. But for the higher shifts it does not really matter (see my original report).
E.g. for shift 1 **with reliable updates**
``` 
 shift=1, relative residual: iterated = 9.962611e-08, true = 7.459438e-03
```
and **without reliable updates**
```
 shift=1, relative residual: iterated = 9.995064e-08, true = 7.399396e-03, requested = 1.000000e-07
```

So conclusion so far is that it seems like the reliable update does not significantly alter what we do for the higher shifts. Stating it a bit bolder: We seem to run mixed precision with reliable updates for shift 0 and basically sloppy precision for higher shifts.

Fix still unknown.

**Comment by mathiaswagner** [comment]
So, still another observation. I calculated the reliable update for each shift just to check how that behaves. Here I observe an increasing deviation between the reliable update that is directly calculated as `rtrue[i] = b - A x[i]` and the one calculated as `r[i] = zeta[i]*r[0]`. Obviously `rtrue[0]=r[0]`. When I take the dot product <rtrue[i],r[0]> I observe that starting with the higher shifts the colinearity of the shifts decreases to a quite significant amount. 

Fix remains unknown.

**Comment by mikeaclark** [comment]
Only easy suggestion at the moment, and something I didn't try is to promote the p[] array to being in high precision.  Keeping this in high precision will likely help keep `zeta[i]*r[0]` closer to `rtrue[i]`.  Having said that, I suspect this will not completely fix the issue.

You probably have to hack this since with additional temporaries since mixed-precision routines are likely not all present, e.g.
```
      pAp = reDotProductCuda(*p[0], *Ap);
```
replace with
```
      cudaColorSpinorField temp(p[0]);
      copy(temp,*Ap);
      pAp = reDotProductCuda(*p[0], temp);
```

**Comment by mathiaswagner** [comment]
Yes, that might help. Then on the other hand we only keep r as a sloppy vector and other then x and p this is only a single vector and not an `[nShift]` array. Anyhow, I will probably give it a try later.

**Comment by mikeaclark** [comment]
The other thing to try of course is to keep r_sloppy in high precision.  Since it is the relation `r[i] = z[i] r_sloppy` that is breaking down, keeping r_sloppy in high precision will likely help a lot.  In fact I have more faith in this than in keeping the p array in high precision.

**Comment by mathiaswagner** [comment]
While I somewhat expected that keeping `r_sloopy` in high precision does not seem to change anything. But I will have to check my code again as there is a lot of copying back and forth to make the blas Kernels accept the precision of the vectors (basically only `p[Nshift]` is still sloppy precision so I copy that to high precision for the blas kernel calls).

Just to add: I did not expect `r_sloppy` in high precision to dramatically change things as `r_sloppy` is anyway replaced with the reliable `r` in every reliable update. Does that sound reasonable?

**Comment by mathiaswagner** [comment]
High precision p (and also still high precision r in the first test) seems to be better:
```
MultiShift CG: Converged after 17899 iterations
 shift=0, relative residual: iterated = 9.973076e-08, true = 9.973076e-08, requested = 1.000000e-07
 shift=1, relative residual: iterated = 9.930850e-08, true = 3.808742e-06, requested = 1.000000e-07
 shift=2, relative residual: iterated = 9.951682e-08, true = 6.762869e-06, requested = 1.000000e-07
 shift=3, relative residual: iterated = 9.953048e-08, true = 2.790128e-07, requested = 1.000000e-07
 shift=4, relative residual: iterated = 9.929501e-08, true = 2.711213e-07, requested = 1.000000e-07
 shift=5, relative residual: iterated = 9.859809e-08, true = 2.675978e-07, requested = 1.000000e-07
 shift=6, relative residual: iterated = 9.893701e-08, true = 2.551286e-07, requested = 1.000000e-07
 shift=7, relative residual: iterated = 9.560197e-08, true = 2.490175e-07, requested = 1.000000e-07
 shift=8, relative residual: iterated = 9.627789e-08, true = 2.442794e-07, requested = 1.000000e-07
 shift=9, relative residual: iterated = 9.666806e-08, true = 2.395976e-07, requested = 1.000000e-07
 shift=10, relative residual: iterated = 9.674850e-08, true = 2.348632e-07, requested = 1.000000e-07
 shift=11, relative residual: iterated = 9.760405e-08, true = 2.070865e-07, requested = 1.000000e-07
```
But of course this run effectively was a double precision run with a single precision Dslash and reliable updates. Question remains whether the reliable update does help here or a run without any reliable updates would give comparable results.
No performance measured as there is still a lot of copying involved.

Still, this is something that seems somewhat promising. (Might also help us if we ever add quad precision vectors and keep the Dslash in double precision).

**Comment by mikeaclark** [comment]
This does seem like a promising result.  I assume it's easy to do the run without the reliable update to see what you get?

The overhead of keeping the `p[Nshift]` array in high precision won't be that bad, and it can be improved since there is still some scope for kernel fusion over the shift loops to minimize the `rSloppy` reads.

Still, it isn't the most satisfactory result given that keeping p[0] in low precision works absolutely fine.  It's just the shifted gradient vectors that need to be in high precision.

**Comment by mathiaswagner** [comment]
I just did without reliable updates and I get (still the code might be somewhat buggy but I hope not):

```
MultiShift CG: Converged after 17885 iterations
 shift=0, relative residual: iterated = 9.925970e-08, true = 1.209246e-04, requested = 1.000000e-07
 shift=1, relative residual: iterated = 9.961117e-08, true = 1.124547e-04, requested = 1.000000e-07
 shift=2, relative residual: iterated = 9.858440e-08, true = 2.150081e-05, requested = 1.000000e-07
 shift=3, relative residual: iterated = 9.983333e-08, true = 7.194906e-07, requested = 1.000000e-07
 shift=4, relative residual: iterated = 9.941376e-08, true = 6.402937e-07, requested = 1.000000e-07
 shift=5, relative residual: iterated = 9.944023e-08, true = 6.028030e-07, requested = 1.000000e-07
 shift=6, relative residual: iterated = 9.892616e-08, true = 4.733687e-07, requested = 1.000000e-07
 shift=7, relative residual: iterated = 9.564410e-08, true = 4.265273e-07, requested = 1.000000e-07
 shift=8, relative residual: iterated = 9.652807e-08, true = 3.895490e-07, requested = 1.000000e-07
 shift=9, relative residual: iterated = 9.658125e-08, true = 3.588776e-07, requested = 1.000000e-07
 shift=10, relative residual: iterated = 9.682769e-08, true = 3.334104e-07, requested = 1.000000e-07
 shift=11, relative residual: iterated = 9.760398e-08, true = 2.377264e-07, requested = 1.000000e-07
```

I will have to clean up the code and do some more check. 
One thing that might also help is to use the true residual for stopping shifts. I.e. force a reliable update and the use rtrue[j] instead of forcing the reliable update and use rtrue[0]*zeta[j]*zeta[j] ...

**Comment by mathiaswagner** [comment]
After doing some more tests with the stopping criterion and half precision I currently have the impression that the higher shifts don't get significantly better than sloppy precision (About 1e-8, 1e-4 for single and half as sloppy precision). Maybe this is still a bug in my implementation.

But as my the with double/single without reliable updates did not differ significantly from the double / single run with reliable updates I believe that reliable updates currently only work for shift 0 and we need a way to make a reliable update also for the higher shifts. Might be hard / impossible to find that given the restriction of colinear residuals ...

Maybe we can look at James proceedings and find a way how to fix the residuals increasingly violating this condition.

**Comment by mikeaclark** [comment]
When we do a reliable update, we don't do anything special for the shifted systems, we only do a reliable update on the zeroth system, and compute the new `zeta[j]` factors.  This has the effect that the shifted systems don't really see much improvement from the reliable update.

We need to somehow also apply this reliable update on the shifted systems.  While there is no concept of computing the shifted residual exactly, since there is no shifted residual to update, there are the `alpha[j]` factors.  Presently when `zeta[j]` is computed we find the new `alpha[j]` factors in `updateAlphaZeta()`, however, these new `alpha[j]` factors will be erroneous.  An alternative therefore is when doing a reliable update, we instead compute `alpha[j]` exactly from the true shifted reliably updated residual, and also compute `zeta[j]` explicitly, i.e.,
```
   zeta[j] = sqrt( (r[j], r[j]) / (r[0], r[0]) )
```
This should have the effect of improving the accuracy of shifted iterations.  I think this is consistent with what @mathiaswagner showed above that keeping `p[j]` in high precision improved the convergence significantly, since the `alpha[j]` coefficients are responsible for updating the `p[j]` vectors.

**Comment by mathiaswagner** [comment]
I tried that when I looked into this but was not successful. There is an old mw/ branch that has that in. 

I believe it doesn't help with orthogonality of p and r for the shifts. 

But the higher shifts are  something I want to look at again.

**Comment by maddyscientist** [comment]
Closing this issue. We have a robust solver in modern QUDA with a double-single multi-shift solver, early termination and double-half refinement on each pole.
