### ISSUE TITLE
QIO interface is broken.

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#206]
Did anyone test qio interface in the current master? I got a segfault while tried to read a gauge config via qio. As a bypass I replaced qio stuff with that one from multigrid branch. It seems working for me so far (single GPU).

**Comment by mikeaclark** [comment]
It doesn't surprise me that QIO in multigrid is more stable than master, though I QIO support worked on master last time I checked.  You are compiling with QMP support I presume?

**Comment by alexstrel** [comment]
yes I did. On 2 GPUs mutigrid qio stuff is also segfaulting.

**Comment by alexstrel** [comment]
Problem is that test programs (or, at least, invert_test and deflation_test) don't create QMP logical topology. Lines 68-72 in  https://github.com/lattice/quda/blob/multigrid/tests/layout_hyper.c allowed me to bypass this issue for single GPU execution. After similar manipulations I managed to avoid the segfault on 2 GPUs as well. This is not good approach, more robust fix is needed.

**Comment by mikeaclark** [comment]
Alexei, all these issues should now be fixed, including for deflation_test.
