### ISSUE TITLE
Support arbitrary color and spin in the clover field

### ISSUE THREAD

**Issue by mchengcit** [lattice/quda#210]
Add support for arbitrary numbers of color and spin for the clover field and its accessor.  This is useful for the multigrid algorithm where there is an induced clover-like term in the coarse grid Dirac operator, even when one does not exist on the fine lattice.  In general, this "coarse clover" term will not have any special properties and will be a dense color-spin matrix.

**Comment by maddyscientist** [comment]
Closing since not an issue.  We represent the coarse clover field as a scalar matrix field and use the gauge field accessor to this end.
