### ISSUE TITLE
Merge code for construction of wilson/clover coarse grid operator

### ISSUE THREAD

**Issue by mchengcit** [lattice/quda#211]
The code for the construction of the wilson and clover coarse grid operators are nearly identical except for a few dozen lines in order to accomodate the coarsening of the clover term.  These functions can be merged to avoid redundant code.

**Comment by mikeaclark** [comment]
Can you add the commit id here for reference please?

**Comment by mchengcit** [comment]
Implemented in commit 26b7b0e77bb62144b9583c740243f67e39ea9086
