### ISSUE TITLE
Merge code for creation of coarse grid operator and "coarse coarse" operator

### ISSUE THREAD

**Issue by mchengcit** [lattice/quda#212]
The code for the creation of the coarse grid operator from the fine lattice (coarse_op.cu) and the creation of the "coarse coarse" operator for all further coarsenings is very similar and can probably be merged.  

There are two significant differences between the two sets of functions:
1. In order to create the first level coarse operator, a cpuCloverField object is passed, but for the "coarse coarse" operator, a cpuGaugeField is used to store the local color-spin matrix.  This can be fixed by adding support for arbitrary color and spin to the CloverField object.  
2. In the fine->coarse case, we can take advantage of the fact that the spin part of the nearest-neighbor coupling is a spin projector, so we only have to loop over spin one time.  In general, for the "coarse coarse" operator, the spin part is dense, so we have to loop over all parts of the spin matrix.

**Comment by maddyscientist** [comment]
This merge was done sometime ago...closing.
