### ISSUE TITLE
Calculation of near-null vectors in multigrid

### ISSUE THREAD

**Issue by mchengcit** [lattice/quda#215]
Currently, the near-null vectors required for multigrid are not calculated in QUDA, but must be loaded from some external source.  Support for the calculation of these near-null vectors should be added to make the multigrid algorithm in QUDA standalone.

This can be done by following the technique in QOPQDP where a smoother is iteratively applied to a random vector using the even-odd operator, or perhaps employing EigCG to return the required number of eigenvectors to a very low tolerance (since the near-null vectors should ideally span the low eigenspace of the operator, but should not be pure eigenvectors)

**Comment by alexstrel** [comment]
Comments: QUDA already allows to store Ritz vectors computed by eigCG. Currently, this is only parity spinors.
TO DO list (incomplete):
1) extend eigCG for DdaggerD systems, currently it's designed for even-odd preconditioned systems. The only requirement for this is to extend ritz vectors for full spinors. 
2) half precision eigCG code is preferable
3) other options: GMRESDR? (under development)

**Comment by maddyscientist** [comment]
Closing this issue, since it's long since been implemented using BiCGstab on random vectors.  Of course there's scope for improvement, but that's not with in the scope of this issue.
