### ISSUE TITLE
Expose heavy_quark_check parameter in interface

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#243]
This is currently hardcoded to be 10 but for low iteration counts it might be desirable to use a lower value.

**Comment by mathiaswagner** [comment]
I am working on this now and have exposed it as a parameter with default 10. 
However, in cases where we use only a heavy quark residual (L2 residual 0) as with some MILC applications we should probably set it to 1.
Right now as a first step I thought about doing that in the milc interface but we might better move that into QUDA and not a application specific interface?

**Comment by mikeaclark** [comment]
Since you're working on the interface, I thought I'd make a **quick** attempt at formalizing interface conventions: https://github.com/lattice/quda/wiki/Updating-the-QUDA-Interface

**Comment by mathiaswagner** [comment]
:-) :-)
Documentation. You gotta love it. 

I'll have a look before creating a pull request and try to comply with the guidelines.
