### ISSUE TITLE
Remove all legacy Tesla support

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#256]
Going forward we are no longer going to support the Tesla architecture (sm_1x).  There are multiple hacks throughout QUDA that have been necessary to keep Tesla support on life support.  E.g.,
```c++
#ifdef STAGGERED_TESLA_HACK
 // insert Tesla hack here
#endif
```
or
```c++
#if __COMPUTE_CAPABILITY__ >= 200
 // insert Tesla incompatible code here
#endif
```
This is an issue for removing all of these hacks, in the process cleaning up QUDA significantly.

**Comment by mathiaswagner** [comment]
Also remove maxregcount from the nvvc options

**Comment by mathiaswagner** [comment]
I also found occurrences of `__COMPUTE_CAPABILITY__ >= 130`.
They could be removed already now but should definitely be checked when we check for Tesla support at all.

**Comment by maddyscientist** [comment]
As of pull request #406, this has been completed.
