### ISSUE TITLE
Possible duplicate code in gauge tools: plaquette?

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#261]
Among the gauge tools there is a function that computes the plaquette, developed long time ago (file gauge_plaq.cu). Recently, in a feature branch (gauge-fix) a lot of interesting gauge code was added, but among them there was another version of the plaquette code, which is mostly duplicated code.

Even if the original plaquette code was not useful for the purposes of the new feature branch, I think minimal modifications should prevail, and that we should avoid duplicated code as much as possible.

**Comment by mikeaclark** [comment]
Thanks for catching this.  These codes do look very similar and we should clean this up.  It looks like gauge_plaq.cu is the cleaner implementation.  @nmrcardoso, can you comment if your plaquette code can be removed and it's use replaced with gauge_plaq.cu?  Perhaps some features need to be added to gauge_plaq.cu.

We should fix this in the feature/gauge-fix branch before merging in #253.

**Comment by mathiaswagner** [comment]
closed with #253
