### ISSUE TITLE
Use qudamilc_called only in exposed functions of the QUDA interface

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#262]
`qudamilc_called` provided only debug output when entering and exiting quda functions, so we know whether control is within QUDA or MILC.
In the somewhat messed up MILC interface this is just another thing that needs to be cleaned up.

**Comment by mikeaclark** [comment]
Since I didn't implement this, I don't really know what needs to be done here.  @mathiaswagner, what needs to be cleaned up exactly?

**Comment by mathiaswagner** [comment]
I need to have a look at that again.
I remember that I had the impression that some functions did not call it and sometimes (although I had never verified that) functions that are in milc_interface.cpp but are only used internally by other functions in the interface also called it. Maybe I was wrong there but the issue should remind me to check that.

Not something I want to start now but this might be a good task on the plane.

**Comment by mathiaswagner** [comment]
I looked through the file and it looks good.
One thing I thought about is: If we do have all parts that are executing QUDA code (and not MILC code) bracketed in
```
qudamilc_called<true>(__func__);
...
...
qudamilc_called<false>(__func__);
```

to also add a timer that tracks all the time spend in QUDA ?

**Comment by mathiaswagner** [comment]
We could also easily add NVTX like described in 
http://devblogs.nvidia.com/parallelforall/cuda-pro-tip-generate-custom-application-profile-timelines-nvtx/

We still miss what is going on in MILC but that is another beast

**Comment by mathiaswagner** [comment]
![screen shot 2015-06-25 at 10 26 43](https://cloud.githubusercontent.com/assets/4508207/8356673/b9e6785c-1b24-11e5-8e82-7975f9398fe0.png)

might need some configure option and check with Jiri that he doesn't mind us using his code but it looks nice
