### ISSUE TITLE
Potential problem for fused kernels and tuning

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#268]
Investigating the mysterious bugs of twisted-clover with tuning, I found that sometimes the results were wrong ONLY during the tuning process. This fact lead me to investigate more carefully the tuning process, and I found, in the definition of the DslashCuda class

    virtual void preTune()
    {
      if (dslashParam.kernel_type < 5) { // exterior kernel <---- DOES NOT INCLUDE FUSED KERNELS
        saveOut = new char[out->Bytes()]; 
        cudaMemcpy(saveOut, out->V(), out->Bytes(), cudaMemcpyDeviceToHost);
        if (out->Precision() == QUDA_HALF_PRECISION) {
          saveOutNorm = new char[out->NormBytes()];
          cudaMemcpy(saveOutNorm, out->Norm(), out->NormBytes(), cudaMemcpyDeviceToHost);
        }
      }
    } 
      
    virtual void postTune()
    { 
      if (dslashParam.kernel_type < 5) { // exterior kernel <---- DOES NOT INCLUDE FUSED KERNELS
        cudaMemcpy(out->V(), saveOut, out->Bytes(), cudaMemcpyHostToDevice);
        delete[] saveOut;
        if (out->Precision() == QUDA_HALF_PRECISION) {
          cudaMemcpy(out->Norm(), saveOutNorm, out->NormBytes(), cudaMemcpyHostToDevice);
          delete[] saveOutNorm;
        }
      }
    } 

Up to here, everything is ok, but if we enable fused kernels, kernel_type will be 6, as defined in dslash_constants.h. Therefore the spinor is not saved during tuning, and it's filled with garbage. That's why fused kernels failed with twisted-clover. I checked that adding a check for EXTERIOR_ALL in the pre- and postTune routines fixes the issue.

This should affect ALL the fused kernels, so maybe we should create a separate commit. My branch with dynamic clover inversion already features the fix.

**Comment by mikeaclark** [comment]
Excellent find @AlexVaq.  I have no idea why line was put there in the first place, it's likely lost in the mists of time.  We should have this fix in the 0.7.1 release that we hope to push this week, so having a separate pull request for this issue would be good.

**Comment by mathiaswagner** [comment]
Good catch. Having a hard coded 5 there looks like a bad idea in the first place.

**Comment by AlexVaq** [comment]
This gave me a terrible headache, but we can finally close the issue of twisted-clover and fused kernels, even for the dynamic inversion. I'm surprised that nobody else reported problems with the fused kernels, although it's difficult to catch, the problems appear only during tuning, and if the solver doesn't diverge, although the result is wrong, the tuning parameters will be saved, and subsequent inversions will give the right result.

**Comment by mikeaclark** [comment]
Yes, I'm really surprised as well that this hasn't been noticed before also.  It must been dumb luck, I used a tune file that had been used on a dslash_test before running invert_test.

**Comment by mathiaswagner** [comment]
This has been closed with #270 and #269.
