### ISSUE TITLE
Contraction profile shows ~90% time spent on epilogue

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#271]
The contraction code is a really simpel code that preforms a scalar product in color space. Performance is critical, that's why I'm really worried about the profiles I'm getting from the profiler:

Before tuning:

Contraction Kernel

           contractQuda Total time = 1.8793 secs
                  init     = 0.063806 secs (   3.4%), with      252 calls at 2.531984e+02 us per call
               compute     = 0.338372 secs (    18%), with      252 calls at 1.342746e+03 us per call
              epilogue     = 1.477008 secs (  78.6%), with      252 calls at 5.861143e+03 us per call
     total accounted       = 1.879186 secs (   100%)
     total missing         = 0.000114 secs (0.00607%)

There is a 78.6% in epilogue, but since we're tuning it can be acceptable.

After tuning:

Contraction kernel:

           contractQuda Total time = 1.56377 secs
                  init     = 0.081706 secs (  5.22%), with      252 calls at 3.242302e+02 us per call
               compute     = 0.002735 secs ( 0.175%), with      252 calls at 1.085317e+01 us per call
              epilogue     = 1.479216 secs (  94.6%), with      252 calls at 5.869905e+03 us per call
     total accounted       = 1.563657 secs (   100%)
     total missing         = 0.000116 secs (0.00742%)

Tuning improved performance, but the epilogue time remains the same.

The epilogue code included in the contract code is the following:

...
    profile.Start(QUDA_PROFILE_EPILOGUE);
    checkCudaError();

    delete contract;

    profile.Stop(QUDA_PROFILE_EPILOGUE);
...

Even if these lines are removed (introducing a memory leak), the 90% time still appears on epilogue. I think this 90% time comes from epilogue from the tuning framework, but I'm not sure about it, and I don't understand why it should stay after tuning.

**Comment by AlexVaq** [comment]
The code used belongs to feature/contractions, which is mor readable and introduces several improvements.

**Comment by mathiaswagner** [comment]
Is there an easy (QUDA internal) way to reproduce the timings?

**Comment by AlexVaq** [comment]
Although "profileContract", which is the internal timer, is included even in master branch, if you don't contract anything you won't see anything. So what you're asking for is a QUDA contraction test code.

I have code for contractions, non QUDA internal, essentially interfaces. QUDA internal I can't have, until I write an interface to host, because now the contractions are coded only for cudaColorSpinorField.

**Comment by mathiaswagner** [comment]
Ok. Did you see long epilogue times elsewhere?
Or is it just the contractions that are so fast?

Another idea: can you generate an nvprof timeline  for nvvp?

**Comment by AlexVaq** [comment]
For instance, the covariant derivative

             covDevCuda Total time = 3.55402 secs
                  init     = 0.000343 secs (0.00965%), with      144 calls at 2.381944e+00 us per call
              epilogue     = 0.000059 secs (0.00166%), with      144 calls at 4.097222e-01 us per call
         dslash kernel     = 3.532829 secs (  99.4%), with      144 calls at 2.453353e+04 us per call
              constant     = 0.020726 secs ( 0.583%), with        9 calls at 2.302889e+03 us per call
     total accounted       = 3.553957 secs (   100%)
     total missing         = 0.000064 secs (0.0018%)


Each call is 1e4 times faster in the epilogue. The contractions are fast indeed, but it shouldn't be like this.

I'll try to generate the profile, although I never used nvvp.

**Comment by mathiaswagner** [comment]
You can use `nvprof -o` to generate a profile that you can import into `nvvp`.
For profiling MPI applications (in case you can only reproduce or run the code on multiple GPUs) Jiri Kraus hat put together a nice post: http://devblogs.nvidia.com/parallelforall/cuda-pro-tip-profiling-mpi-applications/

Note that we also support nvtx_pmpi (see http://devblogs.nvidia.com/parallelforall/gpu-pro-tip-track-mpi-calls-nvidia-visual-profiler/) with '--enable-mpi-nvtx' in case you want to see also MPI calls.

Hope that helps.

**Comment by AlexVaq** [comment]
I got the profile file. I'm not seeing anything strange in nvvp... How can I share it?

**Comment by mathiaswagner** [comment]
How big is the profile? Small enough for email?
You may also upload it to dropbox or something similar.

**Comment by AlexVaq** [comment]
Ok, my fault. Since operations in the GPU are asynchronous, the QUDA profiler (not nvprof) was showing the computation time as belonging to epilogue, when it shuld belong to computation. Adding a cudaDeviceSynchronize() in the right place solved the issue.

Before I had a mismatch between the timings of nvprof and those of QUDA profiling. Now they more or less agree.

I think we can close the issue.

**Comment by mathiaswagner** [comment]
:+1:
