### ISSUE TITLE
Possibility of using a build dir for QUDA

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#275]
While not really relevant for users it might be nice in the development process to have QUDA build its object files in a build directory. One motivation for that is to have separate build dirs for different configuration, e.g. one for each support SM (we currently support at least SM 2.x, 3.x, 5.x).
So when builds for different SMs are needed separate build dirs can avoid the need for having multiple (identical) source copies (one for each configuration) or if you want to use just one copy need to rebuild QUDA completely overtime you switch the SM.
 
Is this something others would also like to have?
If not it is not worth spending time on this.

**Comment by mikeaclark** [comment]
Yes, definitely something to consider for the future.  Multi-arch support would be highly desirable.

**Comment by mathiaswagner** [comment]
at ORNL we also had some discussion about using cmake. 
This would come with build directories anyway. 
Maybe it is worth switching than investing a lot of work in the current build system that also has some dependency issues (there is a separate issue for that)?

**Comment by mathiaswagner** [comment]
I need to dive into the current Makefiles to see what changes are required but the solution presented in http://make.mad-scientist.net/papers/multi-architecture-builds/ seems feasible for use w/ QUDA.

**Comment by nmrcardoso** [comment]
I think it also would be great that the tune cache file could include
the gpu arch in the filename, it would simplify a lot the testing for
machines with different type of gpu architectures.

**Comment by mathiaswagner** [comment]
We had this discussion a while ago. 
In the end we didn't implement that. Probably we thought it was not important enough. 
When one does this it would ultimately be even better to use the GPU name instead of the architecture.  a k20 might get a different launch configuration than a K40. 


But to avoid the moving and deleting of the tune file when switching architectures adding the architecture to the tunecache name probably does not do any harm. We should create an issue for that. The fix should be simple to implement.

**Comment by mathiaswagner** [comment]
This will be support if we get #323 done.

**Comment by maddyscientist** [comment]
Since we have cmake support now in place, this bug can be closed.
