### ISSUE TITLE
Split the clover code into Fmunu tensor computation and clover computation

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#277]
It can be advantageous to have independent code for the Fmunu tensor, without the Clover parameter dependence, so other potential applications (like the topological charge) don't have to duplicate the Fmunu calculation.

**Comment by AlexVaq** [comment]
I have a topological charge code ready (to be combined with the APE smearing). Since I make use of the Fmunu tensor, I don't know whether I should upload it (as a new feature) before this is done.

What do you think?

**Comment by mikeaclark** [comment]
I can do the file split right now and close this issue.  I'd suggest that topological charge should be a separate issue since it's a feature add.

**Comment by mathiaswagner** [comment]
Can this be closed?
