### ISSUE TITLE
Branch cleaning

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#279]
Maybe I could delete the old discLoop and tmclover-quda branches? Is there any reason why I should keep them? Also, it would be nice if everybody else did some cleaning with the branches they started but that now are obsolete.

**Comment by mikeaclark** [comment]
All of this work has been merged into master or develop hasn't it?  If so, please go ahead and delete these.

Going forward, the pull, review, merge and delete process will prevent the explosion of future branches.  I have it on my to do list to clean up the branches, I'm aware there's a bunch of dead branches out there.

**Comment by mikeaclark** [comment]
I've just cleared up a bunch of branches, so we're in better shape now :)

Doing a comparison between the `discLoop` and `tmclover-quda` branches to `develop` however shows that these branches have commits that develop does not.  Are you sure that these branches are fully merged in?

**Comment by mathiaswagner** [comment]
:+1:

**Comment by mathiaswagner** [comment]
Where do we stand on this?
