### ISSUE TITLE
Support gauge reconstruction with naive staggered fermions

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#281]
Gauge reconstruction is only presently supported with improved staggered fermions (on the long link).  We need to add this support to naive staggered fermions, and perhaps also add the option of gauge reconstruction for the fat link for improved staggered fermions, e.g., where stout smearing is used instead of HISQ / Asqtad.

**Comment by mathiaswagner** [comment]
Sounds good. Probably best to expose this in the interface, so that the user (calling code) decides whether a field can be reconstructed or not.

**Comment by mikeaclark** [comment]
This is already exposed in the interface: `QudaGaugeParam::reconstruct`.  We'd simply be using that.

**Comment by maddyscientist** [comment]
This has long since been implemented in #291.  Closing.
