### ISSUE TITLE
QUDA warnings should not print with verbosity = QUDA_SILENT

### ISSUE THREAD

**Issue by mikeaclark** [lattice/quda#285]
Presently, the warnings are printed out even when QUDA context is set to `QUDA_SILENT`.  This is highly undesirable, as users may not want QUDA's internal warning messages.

**Comment by mathiaswagner** [comment]
So right now all QUDA output macros / functions do not internally check the verbosity level.
Is this something we want or do we want to explicitly guard every call to warningQuda with an if ?

**Comment by mikeaclark** [comment]
That was my thinking.

**Comment by mathiaswagner** [comment]
We could also consider (at some point) to load all the logging off to some library (a quick search found e.g.  https://github.com/easylogging/easyloggingpp ). I put that here as a reminder.

**Comment by mathiaswagner** [comment]
Merged fix in #289.
But b before I close this: Do we now have a lot of code that does the check explicitly before calling `warningQuda` **and** in the macro?

**Comment by mikeaclark** [comment]
I don't think this occurs much, if at all.

**Comment by mathiaswagner** [comment]
Found a second to do a quick (and incomplete) check using grep on the code and I did not find any issues. Just wanted to avoid unnecessary code.
