### ISSUE TITLE
QUDA Fortran interface requires by-hand editing on Cray systems

### ISSUE THREAD

**Issue by mikeaclark** [lattice/quda#286]
When a user compiles their Fortran application using the Cray Fortran compiler, this necessitates the use of the Cray Fortran compiler for the QUDA Fortran interface.  The Makefile presently uses the line
```
	$(F90) -c -fno-range-check $*.f90
```
However, `-fno-range-check` is incompatible with the Cray compiler, and so a by-hand edit to remove this flag is required to compile.  We should remove this flag as it is unnecessary.

**Comment by mathiaswagner** [comment]
closed with #289
