### ISSUE TITLE
MPCG is broken

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#288]
Doing some initial testing of the matrix-powers CG algorithm (s-step), has shown that it is broken and fails to converge.  The matrix-powers BiCGstab algorithm does not have this problem.  I'm not sure if this has ever worked, hopefully @jpfoley can help some here.

**Comment by mathiaswagner** [comment]
Do we already have an internal test for that?

**Comment by mikeaclark** [comment]
Just run invert_test with `--inv_type mpcg`.

**Comment by maddyscientist** [comment]
Closing this issue.  We have the CA-CG solver which replaces the matrix-powers solvers, and is numerically stable when using a Chebyshev basis.  The matrix-powers kernels are deprecated and will be removed from QUDA.
