### ISSUE TITLE
Hypercubic RNG

### ISSUE THREAD

**Issue by mikeaclark** [lattice/quda#29]
In order to have machine independent testing we need to have a hypercubic random number generator, i.e., assign a different random number stream to each site on the lattice.  This means that irrespective of how the lattice is mapped to the machine, we will always be generating the same random number fields.

This is required to further aid debugging and verification within QUDA, to further decouple the testing process from external libraries.  Likely this will also be desired for any canned multigrid solver that we deploy.

**Comment by mathiaswagner** [comment]
closed with #253
