### ISSUE TITLE
Merge 4-d domain-wall dslash and wilson operator

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#297]
There's no reason why these should be separate implementations.  Comparing the performance of dslash4 at Ls=1 with the wilson dslash shows that the wilson dslash is more optimized, having around 5-10% greater performance.  If we merge these two, then we can reuse the dslash4 operator as a multi-src Wilson-dslash for a multi-src solver.

**Comment by mathiaswagner** [comment]
I think the new Dslash framework basically achieved that.
