### ISSUE TITLE
MILC crashes in outer product if BUILD_QDP_INTERFACE=no

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#301]
```
QUDA_MILC_INTERFACE: qudaComputeOprod (called) 
ERROR: QDP interface has not been built
 (rank 6, host nid00264, copy_gauge_inc.cu:403 in copyGauge())
       last kernel called was (name=N4quda5Norm2Id7double2S1_EE,volume=12x24x24x12,aux=vol=82944,stride=89856,precision=8)
```

Probably a dependence in the outer product code on the QDP interface.
We should either check at compilation time or remove the depency.

**Comment by mikeaclark** [comment]
That's less of a crash, and more of a graceful exit.  This is caused by the fact that MILC stores its in QDP order but the gauge field in MILC order.  See #160, this is a known issue.

**Comment by mathiaswagner** [comment]
You're right about that. Closing this as a duplicate. I had forgotten about #160.
