### ISSUE TITLE
provide applications a string of LD options required from QUDA

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#302]
With the use of some features, e.g. NVTX or NVML, a dependency on shared libraries has been added to QUDA.
E.g. for compiling MILC with some options on a Cray we need to specify

```
-L${CUDA_HOME}/lib64 -lcudart -L/opt/cray/nvidia/default/lib64 -lnvidia-ml -lnvToolsExt
```

It would be nice to find a somewhat automated way of getting these LD flags passed on to applications.

Scidac libraries come with an executable like 
`./qio-config --ldflags`.

Not sure what is the best way but might be nice to have something like this.

**Comment by mikeaclark** [comment]
Yes, this is also needed for the gauge fixing (CUFFT) and the random numbers (CURAND) in #235.

**Comment by mathiaswagner** [comment]
Shall we go for 'pkg-config' here?
@bjoo What about using this for other USQCD packages?

**Comment by mathiaswagner** [comment]
WIth #1120 we focus on support for proper cmake export.
