### ISSUE TITLE
gauge fixing in ARM7+MILC 

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#318]
Just for curiosity, I run a test and after a minor tweaks I has able to successfully run it.
Problems running in ARM7:
-> -m32 flags must be removed
-> cudaHostRegister() does not work, in cuda 6.5 toolkit release notes:
"Mapping host memory allocated outside of CUDA to device memory is not
allowed on ARM; because of this, cudaHostRegister() is not supported by the
CUDA driver on ARM platforms. If required, cudaHostAlloc() with the flag
cudaHostAllocMapped can be used to allocate device-mapped host-accessible
memory" 

some specs on a 16^4 lattice volume:
with Overrelaxation:
GPU:            time_GK20A /  time_980GTX
single           ~11.2x
double          ~9.7x
CPU:        time_ARM / time_x86_64
single          ~4.5x
double         ~4.9x
With FFT:
GPU:            time_GK20A /  time_980GTX
single           ~13.7x
double          ~9.6x

the GK20A has 1 MP with 192 cores and the 980GTX has 16 MP with 128 cores/MP. 
Which taking into account the total number of cores in 980GTX ~ 10x GK20A, ignoring for now the 
gpu and memory clocks...

980GTX: using cuda 7.0
GK20A: using cuda 6.5

CPU ARM: ARMv7 Processor rev 3
CPU x86_64: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz

**Comment by mathiaswagner** [comment]
That was on a Tegra K1? What is the performance on a Kepler based GPU?

**Comment by nmrcardoso** [comment]
yes, it's a Tegra K1.
I didn't found the nvidia specs.
For the gauge fixing with OVR I got ~6/14 GFlops for single/double precision

**Comment by mathiaswagner** [comment]
We could check which memory allocations are allowed but I am not sure whether we need that.

**Comment by nmrcardoso** [comment]
I was able to run the QUDA only with the gauge fixing feature branch and cuda 6.5
by changing:
Traditional way:
1) malloc(...);
2) cudaHostRegister(..., cudaHostRegisterDefault);
3) cudaHostGetDevicePointer(...)
4)cudaHostUnregister()
5) free()
In ARM, we need to change to:
1) cudaHostAlloc(..., cudaHostAllocMapped)  
2) cudaHostGetDevicePointer(...)
3) cudaFreeHost()

Everything runs compiles and runs fine except the generation of pure gauge configurations.
For some weird reason, using new FloatNOrder gives wrong results only on this kernel, replaced by the old one FloatNOrder and it runs fine.

I asked if it is possible to install cuda 7.0 on ARM, since cuda 6.5 has a strange way to deal 
with structs... 
I don't understand why the new FloatNOrder makes the cuda compiler behave in a strange way :S

**Comment by nmrcardoso** [comment]
Seems there are no cuda 7.0 for arm.

**Comment by mathiaswagner** [comment]
Can we close this?

**Comment by nmrcardoso** [comment]
I think so. The workaround made for cuda 6.5 compiler bug did not work at 100℅ for arm systems.
