### ISSUE TITLE
Build quda using cmake

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#323]
I am working on a cmake build of quda.

This should come with:
* support for build directories (e.g. different directories for different SM)
* support for different build types (release, debug, ...)
* automatic dependency generation (faster recompilation)

This issue is just to document and track progress, missing features from the current autoconf/make build and discuss issues.

Everything is still in a private branch *mw/cmake*.

Building works but does not support any options from the configure script yet.

**Current configure options** (serves as a todo list)

- <del>enable-cpu-arch=arch  Set CPU arch: x86 or x86_64 (default: x86_64)</del> *Only 64 bit in the future*
- [x] enable-gpu-arch=arch  Set GPU arch: sm_13, sm_20, sm_21, sm_30, sm_35,
                          sm_50, sm_52 (default: sm_35)
- [x] enable-os=os          Set operating system: linux, osx (default: linux)
- [x] enable-host-debug     Enable debugging of host code
- [x] enable-device-debug   Enable debugging for device code
- [x] enable-verbose-build  Display kernel register usage
- [x] enable-qdp-interface  Build the QDP interface (default: enabled)
- [x] enable-milc-interface Build the MILC interface (default: enabled)
- [x] enable-cps-interface  Build the CPS interface (default: disabled)
- [x] enable-qdpjit-interface
                          Build the QDPJIT interface (default: disabled)
- [x] enable-bqcd-interface Build the BQCD interface (default: disabled)
- [x] enable-tifr-interface Build the TIFR interface (default: disabled)
- [x] enable-wilson-dirac   Build Wilson Dirac operator (default: enabled)
- [x] enable-clover-dirac   Build Wilson-clover Dirac operator (default:
                          enabled)
- [x] enable-domain-wall-dirac
                          Build domain wall Dirac operator (default: enabled)
- [x] enable-staggered-dirac
                       Build staggered Dirac operator (default: enabled)
- [x] enable-twisted-mass-dirac
                          Build twisted mass Dirac operator (default: enabled)
- [x] enable-ndeg-twisted-mass-dirac
                          Build non-degenerate twisted mass Dirac operator
                          (default: disabled)
- [x] enable-twisted-clover-dirac
                          Build twisted mass clover Dirac operator (default:
                          disabled)
- [x] enable-staggered-fatlink
                          Build asqtad link-fattening routines (default:
                          disabled)
- [x] enable-hisq-fatlink   Build HISQ link-fattening routines (default:
                          disabled)
- [x] enable-gauge-force    Build 1-loop Symanzik gauge force (default:
                          disabled)
- [x] enable-staggered-force
                          Build asqtad fermion force (default: disabled)
- [x] enable-hisq-force     Build HISQ fermion force (default: disabled)
- [x] enable-gauge-tools    Build auxilary gauge tools: plaquette, gauge
                          evolver, APE, extended gauge routines (default:
                          disabled)
- [x] enable-sstep          Build s-step linear solvers (default: disabled)
- [x] enable-contract       Build bilinear contraction code (default: disabled)
- [x] enable-multi-gpu      Enable Multi-GPU support (default: disabled)
- [x] enable-gpu-direct     Enable CUDA/NIC interop pinned memory (default:
                          enabled)
- [x] enable-gpu-comms      Enable direct CUDA-NIC communication (experimental,
                          default: disabled)
- [x] enable-mpi-nvtx       Enable NVTX markup for profiling MPI API calls in
                          the visual profiler (default: disabled)
- [x] enable-milc-nvtx      Enable NVTX markup for profiling MILC interface
                          calls in the visual profiler (default: disabled)
- [x] enable-device-pack    Enable the packing / unpacking of fields on the
                          device (default: disabled)
- [x] enable-pthreads       Enable pthreads in the multi-GPU dslash build
                          (default: disabled)
- [ ] enable-qdp-jit        Enable QDP-JIT support, requires --with-qdp
                          (default: disabled)
- [x] enable-blas-tex       Enable texture reads for blas (default: enabled)
- [x] enable-fermi-double-tex
                          Enable double-precision texture reads on Fermi
                          (default: enabled)
- [x] enable-numa-affinity  Enable NUMA affinity support (default: enabled,
                          always disabled on osx target)

Optional Packages:
- [x] <del>with-cuda=CUDADIR     Specify CUDA installation directory (default:
                          /usr/local/cuda)</del> *supported by cmake*
- [x] with-python=path      Set python executable used for 'make gen'
- [x] with-mpi=MPIDIR       Specify MPI installation directory
- [x] with-qmp=QMPDIR       Specify QMP installation directory
- [x] with-qio=QIODIR       Specify QIO installation directory
- [x] with-qdp=QDPDIR       Specify QDP++ installation directory
- [x] with-magma=MAGMADIR   Specify MAGMA installation directory

- [x] gitversion support
- [x] correct MPI support
- [x] full magma support
- [x] all generated targets
- [x] quda_fortran

**Comment by rbabich** [comment]
Out of curiosity, did you look at automake?

I think that's the solution used by the other USQCD libraries, and QUDA already uses autoconf for the configure script.

**Comment by mathiaswagner** [comment]
No, not in detail. I had the impression that cmake might be the cleaner approach. 
But I have to admit that this is my very personal view.  I never liked automake very much. Using was fine but writing the build system never convinced me. 

Cmake came up during a presentation at the ORNL user meeting and I discussed with Balint a bit. I just thought it might be worth an evaluation. I am close to having >90% ported to cmake after one day.

If there are benefits from automake I am happy to learn.

**Comment by rbabich** [comment]
Balint is definitely more expert in automake than I am, so if he was in favor of cmake (or indifferent), and you've had success so far, it sounds good to me too.  I had a bad experience with cmake recently, but that was probably user error.

End users of QUDA should never have to run cmake, right?  They'll just use the pre-generated build files?  (One advantage of the GNU buildtools is that they come preinstalled on most linux machines, unlike cmake, but that's not a big deal if it only affects developers.)

**Comment by mathiaswagner** [comment]
With the default setup enduser will have to use cmake. I am not sure whether there is an easy way to work this around. Right now the current build system can co-exist with cmake. But this then requires maintaining two build systems which is not what we are aiming for.

Not quite but I sincerely do hope that end users of quda are capable of using cmake. We can certainly convince Jlab / FNAL to have cmake in their default installation (if it not currently in) and it is a module for the Crays. 

Well try to get some experience. We have a QUDA codefest at FNAL Mon-Wed and will discuss cmake there. We don't have a fixed schedule. If you want to call in for that discussion let us know. We probably can make that work.

**Comment by rbabich** [comment]
That's okay.  I'm mostly just a spectator at this point :-).

It does seem unfortunate to introduce another external dependency, but I understand it may be the lesser evil.

**Comment by bjoo** [comment]
Hi All, 
 I have been meaning to sit down and write a longer reply to this, but here is a quick one. Autoconf/Automake is pretty much similar in function to CMake. With the first you as a user would run

configure --configure-options=...
make

With the other you would run:

cmake CMAKE_OPTION_VARS=...
make 

Apart from that the user would see little difference.

The devil is really in the details. I don't
 have much experience with CMake beyond reading. I have heard that it has good Windows support but supposedly it may need to be supported on your platform or you may start having to write your own toolchain definitions. Support for NVCC aside from the regular CC may be present in recent releases or it can be hacked using the CMAKE variables. Supposedly there is good support for launching tests and providing a dashboard of build progress/test success. Also there is supposed to be good support for combining packages.
 The system is 'all in one' ie a single CMakeLists file as opposed to do separate configure.ac and Makefile.am
The system is mature, well supported and has a strong and large user base. In conversations I have heard that several projects are starting to migrate to it from autotools, for both its Windows support and other features ( dashboard etc )

Automake is more GNU oriented. It separates the configure.ac and Makefile.am allowing you some choices as to how much of the autoconf/automake/libtool chain you need. As Ron mentioned, we us just the autoconf now to configure but do not use automake. You can add very friendly  --enable-option and --with-package options with autoconf. The automake end of it just lets you write simple Makefile you just have targets like:

foo_SOURCES= <list of source files> 

and the automake system generates some GNU standard Makefile targets: make, make install, make clean, make distclean, make check etc. The make check can be hooked to run automatic tests (or you can define your own e.g. Chroma's make xcheck ). There is also a make dist target which will create tarball from the source for distribution.

From my point of view autoconf & automake have been OK and helpful the biggest bugbears being version changes...
I.e. if you make a set of tools work for 1  version of the autotools on a system with different versions things may break and you may need to run autoreconf to recreate everything with locally versioned tools. I do this as a matter of routine these days. Sometimes one needs to maintain the scripts as macros/features get deprecated or change between versions. This can be a pain.

As I mentioned I only looked at CMake briefly for a feature overview. However, I have not cut my teeth on it yet with a real project.  I saw Mathias say he was over 90% with it for QUDA, so I am interested in his experiences as regards defining the make install targets. I would miss the nice --enable-xxx and --with- switches that autoconf gives, in favour of defining CMake variables, but this is a matter of taste,  not really a technical issue.

There is a book out there: 

"Software Build Systems: Principles and Experience" by a Peter Smith which may provide a better comparison.

Hope this is helpful.
Best,
 B

On July 25, 2015 2:40:16 PM EDT, Ron Babich <notifications@github.com> wrote:
>That's okay.  I'm mostly just a spectator at this point :-).
>
>It does seem unfortunate to introduce another external dependency, but
>I understand it may be the lesser evil.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lattice/quda/issues/323#issuecomment-124871321

-- 
Balint Joó, Scientific Computing Group, Jefferson Lab
Email: bjoo@jlab.org Tel: +1 757 269 5339
Sent form my mobile phone

**Comment by mikeaclark** [comment]
From what I understand the cmake / autoconf builds can coexist, and they are not mutually exclusive.  This gives us a chance to better compare the approaches.

I am open to cmake but I definitely echo Ron's comment that we should have a very high bar for introducing external dependencies to QUDA.

**Comment by mathiaswagner** [comment]
@bjoo Thanks a lot for you long explanation. Are you interested to call in when we have a discussion about that? I think you told me that you are still traveling so let us know. We should be flexible in the schedule and would love to have your expertise in the discussion.

**Comment by mathiaswagner** [comment]
We should be able to build a large number of possible configurations now. Not everything has been ported yet (MAGMA, NVTX, generators, ...) but basic build should work.

If we decide to follow that route a lot of testing is necessary.

**Comment by mathiaswagner** [comment]
just a little note: gromacs has switched from autoconf/make to cmake and has a nice documentation on building with cmake: http://www.gromacs.org/Documentation/Installation_Instructions_5.0

**Comment by mathiaswagner** [comment]
Current plan is to switch to CMake and at least for the time being keep the old build system until we gathered some experience with CMake and made sure it has all the features of the current build system.

**Comment by mathiaswagner** [comment]
As it came up in the discussion with @bjoo : http://www.cmake.org/Wiki/CMake_Cross_Compiling

**Comment by mathiaswagner** [comment]
Just a note to myself:
To get the code generators integrated we can probably use things from http://www.cmake.org/Wiki/CMake_FAQ#How_can_I_generate_a_source_file_during_the_build.3F

and to only run them when explicitly requested the `EXCLUDE_FROM_ALL` option might help.

Still might be tricky as we build out of source and in the ling run it might be the cleaner approach to run the code generator every time we build.

**Comment by rbabich** [comment]
> Still might be tricky as we build out of source and in the long run it might be the cleaner approach to run the code generator every time we build.

The code generator requires python 2.7 (not 2.6 and not 3.x).  That's the default version in most recent linux distros, but there's no guarantee on a given machine.  If it's at all avoidable, it would be better if end users didn't have to worry about this kind of stuff.

**Comment by mathiaswagner** [comment]
Thanks, @rbabich. I had not paid attention to that. While I hope 2.6 is not longer widely installed we never know. Making the code generator compatible with python 3.x might be a good idea though. For now we will definitely keep the generated cuda code in git.

**Comment by rbabich** [comment]
I was misremembering...  python 2.5 or later should be fine.  (RHEL/CentOS 5 was probably the last major distro with 2.4 as the default.)

I'd still say it's better to avoid the dependency if possible.

**Comment by mathiaswagner** [comment]
I agree.

If we decide to keep the generated code the only ones ever need to run the generate command are developers. I am not sure what the final solution for running the code generators from cmake will be (not because it is complicated but because I have not started working on it) but if it turns out that this will require a modest amount of being able to follow some instructions beyond typing 'make' we still should be fine.
A user of quda should then never need to follow these steps.

We'll know more once I started working on that.

**Comment by mathiaswagner** [comment]
I had a look at updating the generators to python 3 compatibility.

I used `python-modernize` to update the code. It runs without issues and for the things I quickly checked it still generates identical code for python 2.x. To run it with python 3.x we still need to fix the integer division, see https://docs.python.org/3/howto/pyporting.html for details. That should be a quick fix and result in code that can run with python 2.x (.x probably 2.7) and 3.x.. I created #337 for that.

As we plan to drop support for sm1.3 anyway we can also remove that from the code generators. I will generate a separate issue for that. But that is a step independent from any changes to the build system,

**Comment by mathiaswagner** [comment]
A lot of things work now. MAGMA and qdpjit are still missing.

**Comment by mikeaclark** [comment]
I see that "correct MPI support" is left unchecked above.  What does this represent?

**Comment by mathiaswagner** [comment]
Sorry, I somehow missed to answer here. I think MPI is mostly working now. I have not tried an awful lot of combinations and there might be some edges if you have mip-wrappers in your path but want to use others (but I might work - I just have not had a real chance to try).

**Comment by mathiaswagner** [comment]
We now have cmake in the develop branch. Please give it a try! 
It might be a good idea to generate new issues for things that do not work yet at some point.

I will probably have to add a wiki page on building QUDA with cmake.

**Comment by mikeaclark** [comment]
Wiki page sounds like a great idea :+1:

**Comment by mathiaswagner** [comment]
With the release of 0.8 coming up I am inclined to declare the old build system as deprecated and require a flag to configure (maybe `--iamoversixty`) to make it still generate an output (and only print massive warnings). 
That will hopefully give us some feedback and then we can get rid of the autoconf for 0.9.
That will allow us to do a lot of source file organization much easier.

**Comment by mathiaswagner** [comment]
While there are probably a lot of things that don't work yet we do have most functionality for CMakeLists.txt now in 0.8 and will continue to make this even greater over time.

**Comment by maddyscientist** [comment]
One issue I realized with the way cmake works.  QDPJIT requires that we compile cpp code with c++11, however cmake passes all cpp flags to nvcc.  This will mean that QDPJIT and cmake will require CUDA 6.5 and upwards.  Not a big deal but worth noting.

**Comment by mathiaswagner** [comment]
We can probably work around that. But only if we really need to support pre 6.5.
