### ISSUE TITLE
develop branch broken by blas_magma.cpp

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#334]
Problem with blas_magma.cpp file:
magma functions called outside  #ifdef MAGMA_LIB ... #endif

**Comment by mikeaclark** [comment]
Thanks @nmrcardoso.  Closing this issue, it is a duplicate of #335 that I just filed (more detail is on that bug).

**Comment by alexstrel** [comment]
Thanks for brinning my attention! Creating hotfix branch for the issue. 
@mikeaclark  C99 notations is unavoidable if one uses Lapack C interface( as it is in the current implementation), isn't it?
