### ISSUE TITLE
Modernize the code generators for python 3.x

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#337]
Just a reminder for now as it came up in #323.

Probably all we need to do is use 'python-modernize' and fix integer divisions (https://docs.python.org/3/howto/pyporting.html). And we can easily check the generated code is still the same.

At the same time we can also remove the code generated for SM 1.x

**Comment by mikeaclark** [comment]
Just to note that the code generated for sm_1.3 is actually the one that is being used, and the dslashes labelled Fermi aren't actually used.

**Comment by mathiaswagner** [comment]
Good point. I had not actually looked at the python code but then we should at least think of proper labeling for the future :smile:

**Comment by maddyscientist** [comment]
Code generators are no longer used with the dslash rewrite.  closing.
