### ISSUE TITLE
Invert_test broken in develop

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#338]
I get the error:
```
ERROR: Extended gauge field doesn't exist (rank 0, host cream.physics.indiana.edu, interface_quda.cpp:1742 in checkGauge())
```

Can someone please test this? I am still on a state before we merged in the eigcg branch, i.e. basically right after we merged in Nuno's gauge fixing.

I have to check the release branch.

**Comment by mathiaswagner** [comment]
Sorry, my fault. Build for staggered only this time and had not checked.

**Comment by alexstrel** [comment]
invert_test broken, as I could see for double-half twisted mass cg inversion: the first reliable update gives
WARNING: CG: new reliable residual norm 4.297223e+03 is greater than previous reliable residual norm 2.146612e+03 (total #inc 1)
and then the residual norm exploded in a hundred of iterations. Test was done for blas-magma-issue, but with BUILD_MAGMA=no, so it's not related to the eigcg stuff.

**Comment by alexstrel** [comment]
also, this was observed for multi- and single-GPU tests.

**Comment by mikeaclark** [comment]
@alexstrel, I guess this is the same problem you saw with initCG then?

**Comment by alexstrel** [comment]
initCG is essentially a normal CG, so this is a regular CG problem. (double-half mixed precision CG solver, to be precise)

**Comment by mikeaclark** [comment]
Can you run the blas_test to check that all tests pass?

**Comment by alexstrel** [comment]
yes, I'll do a thorough check, let me recompile develop branch.

**Comment by mikeaclark** [comment]
Ok, I've isolated the issue: half-precision dslash is broken, at least it is for Wilson fermions.  Result from running on 4^4 lattice:

```
Results: CPU = 23914.573185, CUDA=31994.989347, CPU-CUDA = 31994.989303
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from dslash
[ RUN      ] dslash.verify
0 fails = 128
1 fails = 126
2 fails = 128
3 fails = 128
4 fails = 128
5 fails = 128
6 fails = 128
7 fails = 128
8 fails = 128
9 fails = 128
10 fails = 127
11 fails = 128
12 fails = 128
13 fails = 128
14 fails = 128
15 fails = 128
16 fails = 128
17 fails = 128
18 fails = 128
19 fails = 128
20 fails = 128
21 fails = 128
22 fails = 128
23 fails = 128
1.000000e-01 Failures: 3014 / 3072  = 9.811198e-01
1.000000e-02 Failures: 3063 / 3072  = 9.970703e-01
1.000000e-03 Failures: 3069 / 3072  = 9.990234e-01
1.000000e-04 Failures: 3071 / 3072  = 9.996745e-01
1.000000e-05 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-06 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-07 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-08 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-09 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-10 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-11 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-12 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-13 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-14 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-15 Failures: 3072 / 3072  = 1.000000e+00
1.000000e-16 Failures: 3072 / 3072  = 1.000000e+00
dslash_test.cpp:878: Failure
Expected: (deviation) <= (tol), actual: 1 vs 0.1
CPU and CUDA implementations do not agree
[  FAILED  ] dslash.verify (1 ms)
[----------] 1 test from dslash (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] dslash.verify
```

**Comment by mathiaswagner** [comment]
:no_mouth:

**Comment by mikeaclark** [comment]
Ok, I've narrowed this down to the merge of the gauge-fixing branch.  Continuing to bisect....

**Comment by mathiaswagner** [comment]
Just adding to that for staggered_invert_test:
`ERROR: Solver appears to have diverged` for mixed precision with sloppy_precision=half.

**Comment by mathiaswagner** [comment]
Also here the underlying half-precision dslash is completely broken.
(I am not really looking into this right now but wanted to add it to the points)

**Comment by mathiaswagner** [comment]
Looks good to me now with #341.
