### ISSUE TITLE
MILC interface for gauge fixing

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#339]
Now that gauge fixing is in QUDA we should expose this also in the MILC interface.

**Comment by nmrcardoso** [comment]
I have the gauge fixing in milc_interface.cpp/quda_milc_interface.h
void qudaGaugeFixingOVR(...)
void qudaGaugeFixingFFT(...)
@mathiaswagner can you check the code and change if it not the correct way?

**Comment by mathiaswagner** [comment]
Oh, sorry. I missed that. I really should have checked this before creating the issue.

Do we still need to modify MILC so it can actually be used from MILC? Do you have a MILC version that calls the qudaGaugeFixing?

**Comment by weinbe2** [comment]
As of two years ago MILC supports `qudaGaugeFixingOVR` : via https://github.com/milc-qcd/milc_qcd/commit/73c66e0f5985afa541b2f4fa50456873dce3e8ea and clean-up through https://github.com/milc-qcd/milc_qcd/pull/54 , closing
