### ISSUE TITLE
Ask users to send in time profile

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#343]
In an effort to better get to know who is using quda and how the application profile looks like (roughly): 

Might it be useful to ask users to send in the time profile of their runs (a typical sample)?

If yes we could extend the time profile to:
- Include the request to share it with us (motivate it by telling them that this ensures that it might help us identify bottlenecks, etc, ...)
- ask the users to share some experience with the runs
- extend the profile to include a little system information (device info, CPU info)

Thoughts?

**Comment by maddyscientist** [comment]
Closing.  QUDA dumps profile.tsv files that contain this information giving us insight into GPU usage.  Together with the `TimeProfile` output to stdout when QUDA finishes a given instance, we have most (all?) of the information we need.
