### ISSUE TITLE
Fermi support with blas_magma

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#354]
Is develop branch still supporting Fermi? I'm getting problems compiling and having a look at blas_magma.cu it looks like the code assumes cc 300 or above.

**Comment by mathiaswagner** [comment]
Yes, we generally still support Fermi.

**Comment by AlexVaq** [comment]
Then blas_magma.cu fails to compile:

/fhgfs/prometheus/buildsets/eb141014/software/CUDA/5.5.22/bin/nvcc  -O3 -D__COMPUTE_CAPABILITY__=200 -ftz=true -prec-div=false -prec-sqrt=false  -w -DMULTI_GPU -DPTHREADS -DGPU_WILSON_DIRAC -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -g -DHOST_DEBUG -DBUILD_QDP_INTERFACE -DDEVICE_PACK -DGPU_CONTRACT -arch=sm_20                      -I/fhgfs/prometheus/buildsets/eb141014/software/CUDA/5.5.22/include -DMPI_COMMS  -I/include -I../include -Idslash_core -I.   blas_magma.cu -c -o blas_magma_gpu.o
blas_magma.cu(21): error: identifier "__shfl" is undefined

blas_magma.cu(37): error: identifier "__shfl" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000055f5_00000000-6_blas_magma.cpp1.ii".


I'm using CUDA 5.5.22, maybe this is an issue?

**Comment by AlexVaq** [comment]
The title of the issue might be misleading because blas_magma.cu is always compiled, whether we use Magma or not. There are no macros excluding parts of the code if BUILD_MAGMA is set to "no".

**Comment by mathiaswagner** [comment]
OK, we need @alexstrel to look into that and comment.
I have not build for Fermi in a while.

**Comment by alexstrel** [comment]
done in hotfix/magma-fermi,
let me check it before merge.

**Comment by mikeaclark** [comment]
Closed by #356
