### ISSUE TITLE
Staggered fat-link code is extremely brittle

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#358]
The present fat-link generation code (lib/llfat_*) is extremely brittle and needs to be cleaned up:
* it uses a hard coded block size
* doesn't use the Tunable class
* for certain local lattice sizes some kernels can get invalid launch parameters
* for too small a problem size the kernels give the wrong answer, e.g. llfat_test fails at V=6^4 
* llfat_test fails with `--recon 12`

These kernels really need to be updated to use the `Matrix` class and `gauge::FloatNOrder`accessors, though this will necessitate a complete rewrite.

**Comment by mathiaswagner** [comment]
I did fire up some more tests and it looks like with Multi-GPU support enabled the tests seem to pass as long as the dimensions are a multiple of 4. I only did some random tests for now.

**Comment by maddyscientist** [comment]
Fixed with #384.
