### ISSUE TITLE
Develop branch plaquette code and dslash_staggered

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#367]
Hi, I tried to compile (cuda 7.5) the last code in the develop branch and it breaks in files:
1) dslash_staggered.cu
   dslash_core/staggered_dslash_core.h(717): error: no suitable user-defined conversion from "float2" to "float4" exists
2) gauge_plaq.cu
ptxas error   : Entry function '_ZN4quda11computePlaqILi960EfNS_11FloatNOrderIfLi18ELi4ELi8EEEEEvNS_12GaugePlaqArgIT1_EE' uses too much shared data (0xc320 bytes, 0xc000 max)(...)

**Comment by mathiaswagner** [comment]
I think Kate ran into the same or a similar gauge_plaq error when compiling for Fermi. For which architecture did you try to compile?

**Comment by nmrcardoso** [comment]
Hi Mathias, I tried for fermi architecture.
Now I've tested also for kepler and maxwell and this happens only for fermi.
Do you know if there are a workaround for this?

**Comment by mathiaswagner** [comment]
I have not yet looked into this. Maybe @mikeaclark has some more insight already. I am not sure whether anyone ever tried to compile develop for Fermi recently with a different CUDA version.

**Comment by mikeaclark** [comment]
The problem with the plaquette has been fixed in my feature/improved_staggered_rhmc branch.  I will look at the other issue later today and make the fix there so it goes in pull #366.

**Comment by mikeaclark** [comment]
The staggered dslash problem has now been fixed also.

**Comment by nmrcardoso** [comment]
thanks @mikeaclark.
Fixed in #366.
