### ISSUE TITLE
Segmentation Fault on trying to read gauge configuration in ILDG

### ISSUE THREAD

**Issue by kpetrov** [lattice/quda#38]
Good Morning USA!

I get segfault trying to read configuration file in ILDG format [Chroma reads such w/out problems]
maybe i am doing smth wrong, but I guess segfault is not the best answer. recent github pull. qio/qmp recent cvs checkout

Reading symbols from /home/kpetrov/DEVEL/quda/tests/wilson_invert_test...done.
(gdb) set args --xdim 24 --ydim 24 --zdim 24 --tdim 48 --load-gauge landau_conf.1000
(gdb) run
Starting program: /home/kpetrov/DEVEL/quda/tests/wilson_invert_test --xdim 24 --ydim 24 --zdim 24 --tdim 48 --load-gauge landau_conf.1000
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x000000000041d657 in read_gauge_field (filename=0x209a820 "landau_conf.1000", 
    gauge=0x7fffffffdef0, precision=QUDA_DOUBLE_PRECISION, X=0x7fffffffde90, 
    argc=<value optimized out>, argv=<value optimized out>) at gauge_qio.cpp:99
99          lattice_size[d] = QMP_get_logical_dimensions()[d]*X[d];
(gdb) bt
#0  0x000000000041d657 in read_gauge_field (
    filename=0x209a820 "landau_conf.1000", gauge=0x7fffffffdef0, 
    precision=QUDA_DOUBLE_PRECISION, X=0x7fffffffde90, 
    argc=<value optimized out>, argv=<value optimized out>) at gauge_qio.cpp:99
#1  0x0000000000403332 in main (argc=11, argv=0x7fffffffe038)
    at wilson_invert_test.cpp:238
(gdb) quit

**Comment by maddyscientist** [comment]
Closing this issue, as having QIO functionality on a single-GPU build is not something that needs to be done.
