### ISSUE TITLE
Multi-GPU bug

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#388]
Develop branch seems to have a bug when running in multi-gpu mode, at least i'm detecting a lot of nan's in the gauge_alg_test. The determinant and trace codes are reporting nan's, the plaquette seems fine, and the gauge fixing is strange in Landau is reporting nan's and in Coulomb no sign of nan's, but the result is no coherent from a version of develop branch from around 2 months ago.

Is anyone getting strange results in this mode?
I did not yet make any kind of debug...

This is some of the output for the test with
mpirun -n 1 ./tests/gauge_alg_test --sdim 16 --tdim 16  --partition 2

Plaq: 6.1355819695838787e-01 , 6.1359340080699387e-01, 6.1352299310978187e-01
Landau gauge fixing with overrelaxation
Starting Landau gauge fixing...
	Overrelaxation boost parameter: 1.500000
	Stop criterium: 0.000000
	Stop criterium method: theta
	Maximum number of iterations: 100
	Reunitarize at every 10 steps
	Print convergence results at every 10 steps
Step: 0	Action: nan	theta: nan
Step: 10	Action: nan	theta: nan	Delta: nan
Step: 20	Action: nan	theta: nan	Delta: nan
Step: 30	Action: nan	theta: nan	Delta: nan
Step: 40	Action: nan	theta: nan	Delta: nan
Step: 50	Action: nan	theta: nan	Delta: nan
Step: 60	Action: nan	theta: nan	Delta: nan
Step: 70	Action: nan	theta: nan	Delta: nan
Step: 80	Action: nan	theta: nan	Delta: nan
Step: 90	Action: nan	theta: nan	Delta: nan
Step: 100	Action: nan	theta: nan	Delta: nan
Time: 0.224596 s, Gflop/s =   95.0, GB/s =   56.9
Determinant: nan, nan
Determinant: Time = 0.000222 s, Gflop/s =   97.4, GB/s =  106.3
Trace: nan, 4.5083270961210148e-01
Trace: Time = 0.000099 s, Gflop/s =   19.9, GB/s =  238.3
Det: nan:nan
Tr: nan:1.5027756987070048e-01
Time -> 0.624226 s
(...)
Time Monte -> 0.396592 s
Plaq: 6.1355819695838787e-01 , 6.1359340080699387e-01, 6.1352299310978187e-01
Coulomb gauge fixing with overrelaxation
Starting Coulomb gauge fixing...
	Overrelaxation boost parameter: 1.500000
	Stop criterium: 0.000000
	Stop criterium method: theta
	Maximum number of iterations: 100
	Reunitarize at every 10 steps
	Print convergence results at every 10 steps
Step: 0	Action: -3.4439949976482843e-04	theta: 1.0666073984022283e+01
Step: 10	Action: 7.2539617868755557e-01	theta: 3.8906541161333197e-01	Delta: 3.7228236273827431e-03
Step: 20	Action: 7.3934103574117926e-01	theta: 1.4309838772700229e-01	Delta: 5.8768116315255359e-04
Step: 30	Action: 7.4279527267648926e-01	theta: 9.9575616114759777e-02	Delta: 2.2326704088804217e-04
Step: 40	Action: 7.4405975071325281e-01	theta: 8.5188204526560216e-02	Delta: 7.3174504925388462e-05
Step: 50	Action: 7.4457638576962681e-01	theta: 8.0292994971973425e-02	Delta: 4.0843205655005654e-05
Step: 60	Action: 7.4478570763066176e-01	theta: 7.7200748485762916e-02	Delta: 1.2533013553750472e-05
Step: 70	Action: 7.4485325693878823e-01	theta: 7.4931275788081134e-02	Delta: 3.7870831066655342e-06
Step: 80	Action: 7.4493948060472681e-01	theta: 7.3117824422073055e-02	Delta: 1.1802261340454478e-05
Step: 90	Action: 7.4507320070782346e-01	theta: 7.1972325172845728e-02	Delta: 1.4656295752479842e-05
Step: 100	Action: 7.4522814111213742e-01	theta: 7.1357756236322276e-02	Delta: 1.6355517921784468e-05
Time: 0.214893 s, Gflop/s =   95.3, GB/s =   54.0
Determinant: nan, nan
Determinant: Time = 0.000215 s, Gflop/s =  100.6, GB/s =  109.8
Trace: nan, 4.4375345161645086e-01

**Comment by nmrcardoso** [comment]
I think I found the issue, however I did not make any tests yet.
@maddyscientist  please correct me if I'm wrong, the VolumeCB() from cudaGaugeField in multi-gpu mode returns the number of lattice points for one parity including the points in the gauge radius, right?
If this is correct we have to correct this in some codes since it uses this to get the number of cuda threads, at least in the multi-gpu part.

**Comment by nmrcardoso** [comment]
for the gauge determinant and trace this was the issue.
Tomorrow, if I have time I will be changing this and the thinks pointed in #389 and I will create an hotfix.

**Comment by nmrcardoso** [comment]
fixed with 05e44fd1df73a119caa98d1b641c2eadd86eed59

**Comment by mathiaswagner** [comment]
fixed with #390.
