### ISSUE TITLE
Single-precision restriction operators have sub-optimal memory access patterns

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#391]
The memory access patterns of the restriction operators are suboptimal owing to the fact that thread blocks have a one-to-one mapping with aggregates.  Since the aggregates typically are of size `4x4x4x4`, the resulting checkerboarded x-dimension of width 2 is not wide enough to cover a cache line in single precision: `width x sizeof(complex<float>) = 16 < 32 bytes`.

Note this problem does not occur with the prolongator, since in general there is no one-to-one mapping between aggregate and CUDA thread block.  Here the CUDA thread block is free to extend between thread blocks and we have perfectly coalesced memory access patterns.

While this problem occurs for both the load of the input vector and the V rotation matrices, since the bulk of the memory operations correspond to the V rotation matrices, we need only address this problem for V to fix >90% of this.  We can address this problem in one of two ways:
1. Use a block ordering for the V fields.  This will ensure that the V loads will be contiguous across the entire block, instead of strided as is at present.
2. We can use float4 ordering for single precision V fields.  This doubles the size of each memory transaction, and as a result, consumes the entire cache line as is presently the case with double precision.

Option 2.) is much easier to implement, so I will likely go with that.  Having a native block ordered accessor function is clearly desirable though since it will simplify the block orthogonalization routines, and allow us to write them using accessors, which is needed for offloading these to the GPU.

**Comment by alexstrel** [comment]
Option 2 looks more complicated to extend for staggered, while option 1 is more generic

**Comment by maddyscientist** [comment]
I'm only suggesting this for the packed V field, where each space-time point has Ns*Nc*Nvec colors.  Even when Ns=1, as for staggered, Nvec will be >=2, so it shouldn't be an issue for staggered either.  The only constraint would be that Nvec must be even.

**Comment by alexstrel** [comment]
ok, agree. even number Nvec for staggered is not a restriction (one more eigen/null vector makes no significant difference)

**Comment by maddyscientist** [comment]
Closed with #488
