### ISSUE TITLE
Covariant derivative might give wrong result while tuning

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#405]
If the covariant derivative is not tuned, the first run might give wrong results. This reminds me of the bug all the dslash had before.

I'll try to look at it.

**Comment by maddyscientist** [comment]
I presume this isn't as simple as needing to save some state prior to tuning that is overwritten when tuning?

**Comment by AlexVaq** [comment]
Well, I'm not sure. I've just observed the bug, but I didn't have time to look into the details.

I'll try to find out.

**Comment by mathiaswagner** [comment]
@AlexVaq Do you want to get that in for the 0.8.0 release?

**Comment by AlexVaq** [comment]
I don't know how many people are using this, apart from my group. And there is an easy workaround, which is first to tune and then to run, so it's not really blocking anything. I think there is not a big rush here, although definitely is something I should fix soon.

Since the release of the 0.8.0 is imminent, I'd leave as an open issue and add a hotfix later, because I can't promise I'll make it before the deadline.

**Comment by maddyscientist** [comment]
Just taking a quick look at this now.  I presume this is for the CovDevCuda class?

**Comment by maddyscientist** [comment]
And does this problem arise in both single- and multi-GPU builds?

**Comment by AlexVaq** [comment]
Yes, it's that class, and I don't know whether it affects single GPU or not. We saw this while trying to prepare some code for production, and since we're writing a paper in a rush, I couldn't do further testing.

**Comment by AlexVaq** [comment]
I'm spending some time right now on this issue. It seems the covDev is all right, but the contraction kernels are not, and require saving the prior state. This was not an issue with the original contraction kernels, because they were overwriting the previous state anyway, but with the plus and minus options leads to the wrong result.

**Comment by maddyscientist** [comment]
Closed with #422.
