### ISSUE TITLE
Dslash with reconstruction 8 seems to be broken at least for Wilson operator

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#417]
invert_test for CG solver (other solvers did not check) with reconstruction 8 fails with NaN appeared in the source norm already after  the preparation stage. (i.e. Ln 2375 in interface_quda.cpp) This can be traced further to the dslash application , i.e. Ln 195 in dirac_wilson.cpp . Rec 12 and no reconstruction work fine. Also, dslash_test woks fine as well , for all cases including rec 8. Current info related to Wilson operator, although other operators might have same problems. This is a single-GPU test, but code is compiled with QMP enabled.  This bug was introduced after commit 4c9d5b5b1916717a21ca90738f638a6c57ef5e1a .

**Comment by maddyscientist** [comment]
I don't think this is a bug.  There is an issue that you can't use free fields with reconstruct 8, and I see that at least the develop branch defaults to using free field unless you load in a gauge field.

**Comment by maddyscientist** [comment]
I note there is an unavoidable singularity in reconstruct 8, which is triggered when the diagonal elements = 1.  This is fixable by modifying how reconstruct 8 is parametrized, such that the singularity appears on the off-diagonal and not on the diagonal, hence it won't be triggered by free fields.  Doing so may actually improve the precision of reconstruct in the general case.
