### ISSUE TITLE
release/0.8.x has problems with qdp-jit

### ISSUE THREAD

**Issue by fwinter** [lattice/quda#425]
While current master (0.7.2) works release/0.8.x (3450833ac5a7) has problems when called with qdp-jit:

ERROR: (CUDA) unknown error (rank 0, host qcdgpu, cuda_gauge_field.cu:123 in createTexObject())
       last kernel called was (name=,volume=,aux=)
[unset]: aborting job:
application called MPI_Abort(comm=0x84000003, 1) - process 0

I am using the qdp-jit device interface to QUDA.

**Comment by maddyscientist** [comment]
Can you list all the steps needed to reproduce this?  Also, what GPU, CUDA version, host compiler etc?

**Comment by mathiaswagner** [comment]
I assume you still used autoconf / configure as cmake has never been tested with QDPJIT and I would not yet expect it to work.

**Comment by fwinter** [comment]
I did not use cmake.

**Comment by mathiaswagner** [comment]
Just wanted to make sure.

**Comment by maddyscientist** [comment]
This isn't a bug, but arose due to using a Kepler+ build on a Fermi GPU.
