### ISSUE TITLE
Add easy method to change mass/kappa to MG preconditioner 

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#426]
We currently need to rerun the entire setup if we want to change the mass/kappa parameter for the MG preconditioner.  Since the mass parameter is just a diagonal constant, it should be easy make this a trivial change.

**Comment by cpviolator** [comment]
Just pushed to hotfix/delta_mu to address this issue. Three new parameters are added to `include/quda.h`, namely `delta_muMG`, `delta_massMG`, and `delta_kappaMG`. These are multiplicative factors which change the respective values of `mu`, `mass` and `kappa` when going from the finest grid to coarser grids.

Passing values to `delta_XXXMG` from the command line is done with "`--delta-XXXMG <value>`" and the defaults are set to `1.0`.

**Comment by maddyscientist** [comment]
Closing this issue, since more thought by me realized that this isn't actually that easy to solve.  Since we use even/odd preconditioning, the inverse clover matrix is included in the coarse link matrix definition.  Hence the mass is not included as a simple diagonal, and can't be rescaled after the fact.

Regardless, since the coase-link matrix computation has been heavily optimized, this is less of an issue that it once was, especially on Volta.
