### ISSUE TITLE
malloc.cpp:240 in device_free_

### ISSUE THREAD

**Issue by fwinter** [lattice/quda#427]
During propagator calculation with standard Chroma switching from QUDA 0.7.2 to 0.8.x I get an error in device_free_() probably coming from QUDA. (Means with 0.7.2 everything's fine)

K20m, CUDA 7.0, g++ (GCC) 4.8.2
NVRM version: NVIDIA UNIX x86_64 Kernel Module  346.46  Tue Feb 17 17:56:08 PST 2015
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 

Entering quarkProp4
QDP m0,n1@qcd12kmi info:  changing data layout to host format
QDP m0,n1@qcd12kmi info:  changing data layout to host format
CG: Convergence at 37 iterations, L2 relative residual: iterated = 9.955836e-08, true = 9.955836e-08
Cuda Space Required
     Spinor:0.046875 GiB
     Gauge :0 GiB
QUDA_CG_WILSON_SOLVER: time=0.068659 s    Performance=258.154130063065 GFLOPS    Total Time (incl. load gauge)=0.170607 s
QDP m0,n1@qcd12kmi info:  changing data layout to device format
QUDA_CG_WILSON_SOLVER: 37 iterations. Rsd = 7.142545e-08 Relative Rsd = 1.62330567185794e-07
QDP m0,n1@qcd12kmi info:  changing data layout to host format
QDP m0,n1@qcd12kmi info:  changing data layout to host format
ERROR: Attempt to free invalid device pointer (cuda_gauge_field.cu:147 in ~cudaGaugeField())
ERROR: Aborting (rank 0, host qcd12kmi, malloc.cpp:240 in device_free_())
       last kernel called was (name=N4quda22HeavyQuarkResidualNormI7double36float26float4EE,volume=8x16x16x32,aux=vol=65536,stride=65536,precision=4) 

To reproduce this:
1) Get the software

git clone https://github.com/usqcd-software/qmp.git
git clone --recursive https://github.com/fwinter/qdp-jit.git
git clone https://github.com/lattice/quda.git
git clone --recursive https://github.com/JeffersonLab/chroma.git

Run autoreconf in both the chroma and qdpjit directories.

2) Next, build the components in the above order. You can download a build script from here (it might need some adjustments to your build environment. Note that the script creates directories 'build' and 'install' in the directory where you call it) https://userweb.jlab.org/~fwinter/build_chroma.sh

3) Next, use the attached input XML file and run chroma ( https://userweb.jlab.org/~fwinter/in.xml )

~/toolchain/install/chroma-ptx-parscalar-single/bin/chroma -geom 1 1 1 1 -i in.xml

**Comment by maddyscientist** [comment]
Closed with #428.
