### ISSUE TITLE
sm37

### ISSUE THREAD

**Issue by fwinter** [lattice/quda#429]
Guys! I came across an issue with qdp-jit on sm37 hardware (i.e. K80s). Then I wanted to build the Chroma/Quda/Jit triple for this architecture and realized that QUDA too stops counting at sm35. That means huge startup times on sm37. Is there a deeper reason for this?

**Comment by maddyscientist** [comment]
That doesn't sound right: sm_30 and sm_35 are binary compatible with sm_37.  There should be no difference between an sm_37 build and an sm_35 one (there's some tiny differences but none that matter).  Are you sure you're compiling for sm_35 when running on the K80?

**Comment by fwinter** [comment]
Right, I was building for sm20. Building for sm35 removes the huge startup time. Sorry, I got alarmed too quickly because of a parallel issue. but none of that matters to quda.
