### ISSUE TITLE
unpredictable "invalid resource handle" in MPI-parallel application linking against serial QUDA library

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#444]
Dear all,

this is a rather peculiar issue that I'm trying to get my head around. Explaining the context will require a few lines, so let me begin with the error message which occurs when running on the gpu partition of Jureca at JSC in Juelich (75 nodes with two K80s -> four devices per node):

```
# QUDA: ERROR: (CUDA) invalid resource handle (cuda_color_spinor_field.cu:57 in cudaColorSpinorField())
# QUDA:        last kernel called was (name=N4quda10PackSpinorIddLi4ELi3ENS_11FloatNOrderIdLi4ELi3ELi2EEENS_21SpaceSpinorColorOrderIdLi4ELi3EEENS_19ChiralToNonRelBasisIddLi4ELi3EEEEE,volume=32x32x32x64,aux=out_stride=1048576,in_stride=1048576)
```

We (Bonn node of the ETMC) are trying to use the QUDA solvers in (perhaps) a rather peculiar way. Our distillation code is OpenMP/MPI-parallel and a few weeks ago I've begun switching us from a CUDA solver written by Florian Burger to the QUDA library (via an adaptation of Mario Schroeck's QUDA interface for the tmLQCD software package).

For smallish lattices we find that it is most efficient to link this against a "serial" version of QUDA (MultiGPU disabled), run our distillation code with 4 MPI processes on a single node and associate one CUDA device to each MPI task based on the MPI process id (0-3). Of course, we use spin dilution and thus have four sources which need to be inverted for each of the remaining dilution indices. Each process therefore calls invertQuda independently (after doing all the necessary initialisations). Combining this with multiple threads constructing the perambulators in the background results in very low GPU idling and the highest performance per device (so far).

This works very well on our local GPU machine with four K20s per node, but fails in rather unpredictable ways on Jureca and it is unclear to me where the problem originates. I've had instances where the first few inversions go through just fine and then the error occurs and other cases where the error occurs right away. At least it is reproducible in that it always happens (thus far).

Would be grateful for some help in diagnosing and hopefully resolving this issue. I'm using v0.8.0 (checked out via its git tag).  I can obviously provide all kinds of debugging info if it would be helpful.

I will later file a separate issue report because we are also having a problem (albeit a different one) when running in fully MPI-parallel mode with MultiGPU enabled. Sadly, this happens similarly unpredictably...

Cheers,
Bartek

**Comment by kostrzewa** [comment]
I should mention that of course the full gauge field and source are copied to each of the four devices.

**Comment by kostrzewa** [comment]
The relevant calling code can be found here: https://github.com/kostrzewa/tmLQCD/blob/lowmem.subprocess/quda_interface.c#L523

**Comment by mathiaswagner** [comment]
Your usage pattern seem pretty unusual. I am not sure whether anyone has ever tried that before.
You might just hit some issues that only show up in that case.
Maybe you can boil you code down to a single MPI rank first and check whether that succeeds?

**Comment by rbabich** [comment]
I don't think it's that unusual.  We used to use QUDA in a similar mode when running alongside QDP/C and QOPQDP, doing inversions on a single GPU but using multiple MPI processes for contractions, etc.

That was a long time ago, though...

**Comment by mathiaswagner** [comment]
@rbabich: l stand corrected. But at least we probably don't do very extensive testing with this usage pattern these days.

@kostrzewa : Can you report the CUDA (nvcc)and CUDA driver (nvidia-smi) versions?

**Comment by maddyscientist** [comment]
Looking at this bit of code where QUDA is initialized, am I correct in thinking that we're concerned here with sub process mode?

The macro `MPI` is a local one and should therefore not supposed to be defined for this to work?  Is it possible that the MPI on the problem system defines this but your local testing used an MPI that does not?

```c++
  // initialize the QUDA library
#ifdef MPI
  initQuda(-1); //sets device numbers automatically
#else
  // when running in 'subprocess' mode, the external program should have provided us with a unique
  // id in the range 0 to (N-1), where N is the number of NVIDIA devices available (see wrapper/lib_wrapper.c)
  if(subprocess_flag){
    initQuda(g_external_id);
  }else{
    initQuda(0);  //scalar build without subprocess: use device 0
  }
```

**Comment by kostrzewa** [comment]
Dear all, thank you and apologies for taking so long to reply after your quick reactions.

@mathiaswagner 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

I cannot really query the version of nvidia-smi because interactive sessions are not permitted on the gpu compute nodes. On the frontend nodes, which do not have GPUs, the manpage for nvidia-smi gives
```
nvidia-smi 352.68
````

I had already considered trying to reduce the problem to just one MPI rank in the distillation code, but this would involve some substantial changes which I'd like to make only if absolutely necessary to figure out this problem.

Could this be related to the NUMA affinity? I believe that I've tried changing this already without effect, but the version of QUDA that I link against has been compiled with NUMA affinity enabled. However, QUDA reports that it is unable to determine the NUMA affinity. I can try disabling this again if you believe that it might be related to this problem.

On Jureca we also make use of the Intel compiler (rather than GCC as on our local gpu cluster) and I thought that maybe it could be related to this.

@maddyscientist 
Indeed, MPI is disabled within tmLQCD and ```MPI``` is undefined. Essentially in this usage pattern tmLQCD has been reduced to a library of functions for loading the gauge field with our metadata and converting between our ordering (TXYZ) and that used by QUDA. 

The naive parallelisation (from the point of view of inversions) is done in the distillation code. This code passes two pointers to ```invert_quda_direct``` (https://github.com/kostrzewa/tmLQCD/blob/lowmem.subprocess/quda_interface.c#L523) and integrates the resulting propagator into the perambulator when the function returns.

I should note that when running tmLQCD serially (or in MPI mode), hundreds of inversions through Mario's interface on one (or 4) gpu(s) go through without any problems.

**Comment by maddyscientist** [comment]
@kostrzewa While this doesn't solve your issue (I presume it's not fixed yet?), I would like to draw your attention to the fact that we'll shortly be merging in the feature/peer_to_peer branch into the main development branch (`develop`).  This adds support for direct peer-to-peer communication between GPUs on the same PCIe route complex: this drastically improves strong scaling within a node.  Perhaps this improvement in scaling will allow you to move to a more conventional running approach?

E.g., here's some early performance numbers, scaling on quad K80 node (two K80s per CPU socket, so peer-to-peer only between each group of four GPUs), double-half precision, Wilson CG solver, V = 32^4
```
GPUs   w/o p2p    p2p
1        394      394
2        672      731
4        876     1295
8        798     2066
```

**Comment by kostrzewa** [comment]
@maddyscientist That would indeed remove the requirement for the usage of this special mode. That's really good news since I've been unable to resolve the issue. Thanks!

**Comment by maddyscientist** [comment]
@kostrzewa Which Dirac operator and solver do you use?  Let me test that this is working fine, then if you don't mind using a development branch, you could try the feature/peer_to_peer branch.  It seems to be mostly stable, though there are a number issues I need to fix (for example un-improved staggered in half precision is presently broken).  It seems to be stable for all Wilson-type actions.

**Comment by kostrzewa** [comment]
@maddyscientist Thanks! For now we only require degenerate twisted mass and twisted mass + clover with support for inversions of both flavours (+ and - mu).  For the solver we always use CG, usually double-half. The parameters are passed to QUDA as follows for the two relevant cases:

```
 if( optr->mu != 0.0 && optr->c_sw > 0.0 ) {
    inv_param.dslash_type = QUDA_TWISTED_CLOVER_DSLASH;
    inv_param.matpc_type = QUDA_MATPC_EVEN_EVEN;
    inv_param.solution_type = QUDA_MAT_SOLUTION;
    inv_param.clover_order = QUDA_PACKED_CLOVER_ORDER;
    inv_param.mu = fabs(optr->mu/2./optr->kappa);
    inv_param.clover_coeff = optr->c_sw*optr->kappa;

  }
  else if( optr->mu != 0.0 ) {
    inv_param.dslash_type = QUDA_TWISTED_MASS_DSLASH;
    inv_param.matpc_type = QUDA_MATPC_EVEN_EVEN_ASYMMETRIC;
    inv_param.solution_type = QUDA_MAT_SOLUTION;
    inv_param.mu = fabs(optr->mu/2./optr->kappa);
  }
  inv_param.solve_type = QUDA_NORMERR_PC_SOLVE;
```

**Comment by kostrzewa** [comment]
This is solved in develop (I don't know what has changed), but I will close this now.

**Comment by maddyscientist** [comment]
That's for confirming this has closed @kostrzewa.  Has the GPU driver on the system changed at all in the meantime?

Can you very if the hanging is still present as well on Jureca?

**Comment by kostrzewa** [comment]
@maddyscientist Yes, it appears that the driver has been updated: NVIDIA-SMI 352.93     Driver Version: 352.93

As for the hanging, the answer is yes, unfortunately (at least it was two weeks ago). I will run another test and then provide you with the information we discussed at LAT'16.
