### ISSUE TITLE
CMAKE throwing "lib/gitversion.dummy" error

### ISSUE THREAD

**Issue by cpviolator** [lattice/quda#448]
Hi guys,

I'm trying to build a simple 0.8.0 master copy build on Centos. I go through the motions of making a build directory, running `cmake ../quda`, I set the compute mode for 2.0 turn off some Dirac operators builds with `ccmake .` in the build directory, compile then generate, then run `make -j 16`. The error that is thrown is not something I've been able to fix, it goes:

`[howarth@compphys bld_quda]$ make -j 16`
`[  3%] Built target quda_test`
`make[2]: *** No rule to make target "lib/gitversion.dummy", needed by` `"lib/CMakeFiles/quda.dir/version.cpp.o".  Stop.`
`make[1]: *** [lib/CMakeFiles/quda.dir/all] Error 2`
`make: *** [all] Error 2`
`[howarth@compphys bld_quda]$`

The same error gets thrown on Stampede. The now deprecated `./configure` and `make` works fine, but I'd rather get cmake working. Am I missing something spectacularly obvious?

**Comment by maddyscientist** [comment]
What version of cmake, nvcc, and gcc do you have?

This is for @mathiaswagner, he's the cmake expert :wink:

**Comment by maddyscientist** [comment]
One thing though: can you check if the problem also occurs in the develop branch?  There have been a number of minor changes to the cmake build in develop, so it would be good to rule this out as something that hasn't been fixed already.

**Comment by cpviolator** [comment]
GCC: 4.4.7
NVCC: CUDA 6.0
CMAKE: 2.8.12.2
GIT: 1.7.1

**Comment by mathiaswagner** [comment]
Yes, cmake version as well as CMakeLists.txt are helpful. Do you build in source or in a separate build directory?

**Comment by maddyscientist** [comment]
I can see from what @cpviolator has written above, that he's using a separate build directory.

**Comment by cpviolator** [comment]
I build in a separate directory. Here is my `CMakeLists.txt` from my local server. I'll post the TACC Stampede info too.

[CMakeLists.txt](https://github.com/lattice/quda/files/191422/CMakeLists.txt)

**Comment by mathiaswagner** [comment]
Right. I see it now.

**Comment by mathiaswagner** [comment]
Not my morning. I meant CMakeCache.txt. sorry.

**Comment by cpviolator** [comment]
No worries, here's the `CMakeCache.txt` from my local. TACC Stampede data will follow.
[CMakeLists.txt](https://github.com/lattice/quda/files/191427/CMakeLists.txt)

**Comment by maddyscientist** [comment]
(I think you've posted the same file twice: that doesn't look like a CMakeCache.txt file)

**Comment by cpviolator** [comment]
You're right! Not my evening then either :) Here is the `CMakeCache.txt` for my local Centos build:

[CMakeCache.txt](https://github.com/lattice/quda/files/191431/CMakeCache.txt)

**Comment by cpviolator** [comment]
For TACC Stampede,

GCC: 4.4.7
NVCC: CUDA 6.5
CMAKE: 2.8.12.2
GIT: 1.7.1

Same error message as the local one. Here is the `CMakeCache.txt` for TACC Stampede:

[CMakeCache.STAMP.txt](https://github.com/lattice/quda/files/191440/CMakeCache.STAMP.txt)

**Comment by cpviolator** [comment]
The Develop branch does not build on either my local Centos or TACC Stampede; they do not like the `-std=c++11` command line option, but I think a `-std=c++0x` replacehack will fix it.

**Comment by mathiaswagner** [comment]
For the develop branch there are some issues with the `c++11` option in older cmake versions. We probably need to require a newer cmake version for that.
Anyway, we should also figure out what goes wrong with your 0.8 build.

**Comment by mathiaswagner** [comment]
Can you give the hotfix/cmake_gitdummy branch a try? 
I have a first suspicion what _might_ be going on and the branch tries to fix that.

**Comment by cpviolator** [comment]
Thanks, that does the trick! I've attached my `CMakeLists.txt` from the build (a local Centos build) and If I encounter any problems on TACC I'll check back, but I'm pretty sure it will go smoothly on there too.

May I ask, why does adding that boolean on `GITVERSION` solve the problem?
[CMakeLists.txt](https://github.com/lattice/quda/files/193950/CMakeLists.txt)

**Comment by mathiaswagner** [comment]
Closed with #449
