### ISSUE TITLE
Multigrid fails for unpreconditioned clover

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#450]
There seems to be a bug with unpreconditioned clover and the multigrid solver, but to see it one needs to use a smooth configuration and calculate the clover term (these are not default settings of the test). What I see is that the null vectors are poorly computed, and the resulting solver has a really bad performance.

The issue doesn't exists in the preconditioned clover, or in the twisted-clover (preconditioned and unpreconditioned) at mu = 0.0, which is very surprising because twisted-clover is suppose to do the same operations than clover for the unpreconditioned case.

I observed this problem in the feature/multigrid and feature/tm-multigrid branches.

**Comment by maddyscientist** [comment]
Is there a way for me to reproduce this problem using the internal QUDA tests?

**Comment by AlexVaq** [comment]
I'm not sure: in a unit configuration the clover term is irrelevant. I didn't try a totally random configuration, maybe if you just create the clover term there you'll see it.

I'll try tomorrow.

**Comment by maddyscientist** [comment]
@AlexVaq any update on this?

**Comment by AlexVaq** [comment]
Not yet, I'll download the current develop and try again. It's curious that the BiCG solver directly fails...

If the bug is still there, I'll also try to find an easy way to reproduce it.

**Comment by AlexVaq** [comment]
It seems to me that the bug affects clover fermions, and not specifically multigrid. The part that fails is the BiCG solver, and it fails right from the start.

In order to see the bug, with minimal changes in multigrid_invert_test.cpp, one can try this:

1. Change clover_coeff from 1 to 1e-20. This ensures our clover fermions will be like wilson. I mean, we should get the same result with wilson than with clover, but we will enforce QUDA to use clover fermions.

2. Change the unit configuration for a random one. This is achieved by commenting line 432 and uncommenting line 430.

3. Run the following two tests: 

./multigrid_invert_test --dslash-type wilson --sdim 12 --tdim 12 --prec single --prec-sloppy single --precon-type mr --solve-type direct

./multigrid_invert_test --dslash-type clover --sdim 12 --tdim 12 --prec single --prec-sloppy single --precon-type mr --solve-type direct

and compare. Everythin looks normal, but with wilson the solver converges in 10-15 iterations up to 1e-7, and with clover the solver stops after reaching the iteration limit without converging.

invert_test seems to work properly in all cases, although QUDA detects a memory leak when the solver is BiCG, I think I should look into that.

**Comment by AlexVaq** [comment]
Sorry, I forgot to remove the --sdim and --tdim, they are not really necessary, the problem remains for other volumes.

**Comment by maddyscientist** [comment]
Will look into this, but off the top of my head, I wonder if this is because it tries to invert the clover matrix which is close to zero, and so becomes junk.

**Comment by AlexVaq** [comment]
> I wonder if this is because it tries to invert the clover matrix which is close to zero, and so becomes junk.
> 
Well, the preconditioned operator works properly, it's the unpreconditioned one that fails. Also I believe the clover term includes the identity in QUDA, so it would try to invert something close to the identity.

Did you manage to reproduce it? I gave you a clear case you could see it goes wrong, but with other values (clover_coeff ~ 0.1, for instance) it also happens, so I would say MG is not reliable for unpreconditioned clover.

The most puzzling thing is that twisted-clover for mu = 0.0 works properly in the same case...

**Comment by maddyscientist** [comment]
Looking into it now.  The other to note is that multigrid_invert_test actually uses the QUDA clover construction and inversion routines to create the clover field, whereas invert_test is just a hack.

**Comment by AlexVaq** [comment]
> Looking into it now. The other to note is that multigrid_invert_test actually uses the QUDA clover construction and inversion routines to create the clover field, whereas invert_test is just a hack.
> 
I changed that when I tried the invert_test, so QUDA was constructing the clover term from the random configuration in that  case too. You can also reproduce that one and see how wilson and clover coincide. By the way, you need to comment the part that generates the clover term in the CPU, even if you don’t load the clover from CPU, it will modify the random source/configuration generated because it will call a few times the random number generator.

**Comment by maddyscientist** [comment]
Ok, I have reproduced this....no idea what's wrong yet.

**Comment by maddyscientist** [comment]
Looks like a memory initialization bug..still investigating....

**Comment by maddyscientist** [comment]
I have this fixed.  Will push tomorrow.  Problem was smoother was being done with preconditioning but since the outer solver has no preconditioning, no clover inverse was being done.  Basically this is the fault of the hacked MG interface.

**Comment by AlexVaq** [comment]
Glad to see you fixed it! I see, so the smoother needs the inverse clover
term anyway. That definitely would make things go wrong.
