### ISSUE TITLE
Clover issues

### ISSUE THREAD

**Issue by fwinter** [lattice/quda#470]
invertQuda gives me

CALLING QUDA SOLVER
ERROR: Parameter clover_coeff undefined (rank 0, host workstation, check_params.h:365 in checkInvertParam())
       last kernel called was (name=N4quda10CopyCloverIffLi72ENS_6clover11FloatNOrderIfLi72ELi4EEENS1_11QDPJITOrderIfLi72EEEEE,volume=16x16x16x32,aux=out_stride=65536,in_stride=65536)
QMP m0,n1@ error: abort: 1

This comes from an HMC (Chroma) input file that worked before. It's the MdagM clover operator, biCGstab (CG shows the same behavior). I cross-checked pure Wilson and that one works (Bicgstab and CG). Where/when is the quda invert parameter clover_coeff set?

What wonders me is knowing the fact that we checked quda 0.8 against these tests.

**Comment by bjoo** [comment]
Hi Frank,

We came across this in MG work but I thought we fixed it. I think this comes from the fact that we didnt set it at all since we passed the precomputed clover term so we didn't need to. I think at some point Kate tightened up the parameters checking. I can't remember if I set a default value in the Mg branch or whether Kate did it on the MG QUDA branch.

Best,
 B

On May 22, 2016 4:04:36 PM EDT, Frank Winter <notifications@github.com> wrote:
>invertQuda gives me
>
>CALLING QUDA SOLVER
>ERROR: Parameter clover_coeff undefined (rank 0, host workstation,
>check_params.h:365 in checkInvertParam())
>last kernel called was
>(name=N4quda10CopyCloverIffLi72ENS_6clover11FloatNOrderIfLi72ELi4EEENS1_11QDPJITOrderIfLi72EEEEE,volume=16x16x16x32,aux=out_stride=65536,in_stride=65536)
>QMP m0,n1@ error: abort: 1
>
>This comes from an HMC (Chroma) input file that worked before. It's the
>MdagM clover operator, biCGstab (CG shows the same behavior). I
>cross-checked pure Wilson and that one works (Bicgstab and CG).
>Where/when is the quda invert parameter clover_coeff set?
>
>What wonders me is knowing the fact that we checked quda 0.8 against
>these tests.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lattice/quda/issues/470

-- 
Balint Joó, Scientific Computing Group, Jefferson Lab
Email: bjoo@jlab.org Tel: +1 757 269 5339
Sent form my mobile phone

**Comment by maddyscientist** [comment]
This works if you use the quda-multigrid branch of Chroma.  We've increased some interface checking robustness so more parameters need to be explicitly set.  I guess Balint hasn't merged this branch into master yet.

**Comment by fwinter** [comment]
chroma/feature/quda_multigrid gets me a step further, but 

CG: Convergence at 22 iterations, L2 relative residual: iterated = 6.872258e-06, true = 6.872258e-06
Cuda Space Required
	 Spinor:0.0146484375 GiB
	 Gauge :0 GiB
	 InvClover :0 GiB
QUDA_CG_CLOVER_SOLVER: time=1.471436 s	Performance=4.80858746421863 GFLOPS	Total Time (incl. load gauge)=2.793924 s
QUDA_CG_CLOVER_SOLVER: 22 iterations. Rsd = 2922.468 Relative Rsd = 1.00000003903682
QUDA_CG_CLOVER_SOLVER: Total time (with prediction)=2.794021
ERROR: QUDA Solver residuum is outside tolerance: QUDA resid=1.00000003903682 Desired =1e-05 Max Tolerated = 0.0001
SOLVER FAILED: Aborting


and


BiCGstab: Convergence at 12 iterations, L2 relative residual: iterated = 9.648832e-07, true = 9.648832e-07
Cuda Space Required
	 Spinor:0.0205078125 GiB
	 Gauge :0 GiB
	 InvClover :0 GiB
QUDA_BICGSTAB_CLOVER_SOLVER: time=1.495165 s	Performance=2.69356109325727 GFLOPS	Total Time (incl. load gauge)=2.240986 s
Null Predictor Predict X: Leaving guess unchanged
ERROR: Source has zero norm (rank 0, host workstation, interface_quda.cpp:2348 in invertQuda())
       last kernel called was (name=N4quda4blas5Norm2Id6float26float4EE,volume=8x16x16x16,aux=vol=32768,stride=32768,precision=4)


Have we seen this before?

**Comment by fwinter** [comment]
"a step further" here means it obviously passes the parameter check but fails on the first solve.

**Comment by fwinter** [comment]
I got it to work with 0.8 quda release branch and chroma/master. We can leave this issue open for the master branch.

**Comment by mathiaswagner** [comment]
>5 years since last activity. Closing this. Please reopen if still an issue.
