### ISSUE TITLE
Need to be able to specify mapping of GPU to local process

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#473]
With the advent of NVLink, getting the correct node topology is now more complicated than just ensuring correct NUMA placement of processes for their respective GPUs.  For dense GPU systems with multiple NVLinks we need a method to easily map the local process id to GPU device ordinal.  Failing to do so will result in sub-optimal use of peer-to-peer bandwidth and message being unnecessarily routed through CPU memory.

**Comment by mathiaswagner** [comment]
NVML's `setCPUAffinity` does not work? Or is the mapping needed on the `mpirun` level ?

**Comment by maddyscientist** [comment]
Closing this issue, as this required functionality is trivially obtained from the `CUDA_VISIBLE_CONNECTIONS` environment variable (the order that devices are listed in this variable corresponds to the order that the CUDA runtime sees the device).
