### ISSUE TITLE
Undefined clover_coeff in quad-0.8.0 clover_field.cpp?

### ISSUE THREAD

**Issue by detar** [lattice/quda#477]
We are trying quda-0.8.0 with the MILC code for the first time and encountered a new error when calling qudaCloverInvert

ERROR: Parameter clover_coeff undefined (rank 0, host nid00604, /N/u/sg/BigRed2/
quda-0.8.0/quda-0.8.0/lib/check_params.h:365 in checkInvertParam())
       last kernel called was
(name=cudaMemcpyHostToDevice,volume=bytes=452984832,aux=copy,/N/u/sg/BigRed2/quda-0.8.0/quda-0.8.0/lib/clover_field.cpp:247)

The MILC code wrapper is passing a precomputed clover term.  All inverter parameters are passed as they were for quda-0.7.0.

Any suggestions?
Thanks,
Carleton

**Comment by mathiaswagner** [comment]
I just had a quick look at the milc interface code. For eigcg and multi shift clover there is a line
```
  invertParam.clover_coeff = clover_coeff;
```
this seems to be missing for `qudaCloverinvert`.

Can you try if adding this line to `milc_interface.cpp` (line ~ 1460) fixes the issue?

**Comment by AlexVaq** [comment]
Since clover_coeff is not used if the clover term is precomputed, one might just give some random value to the coefficient as a workaround.

**Comment by stevengottlieb** [comment]
Thanks, Mathias.  I will try that and report back.

**Comment by maddyscientist** [comment]
The develop branch introduces more rigorous parameter checking, including whether checking if the clover_coefficient is set or not.  So I think this problem is coming from the develop branch and not the 0.8.0 release.

I'll look into this now.  We should bump the version number in the develop branch so that there is no confusion between develop (what will be 0.9) and 0.8.

**Comment by maddyscientist** [comment]
Ok, I've worked out the source of the bug: the clover coefficient is being set when it comes to downloading the clover field in the `qudaLoadCloverField` function, but it isn't set `invertQuda`, which is when this parameter check takes place.

I'll open a pull to fix this in the next couple of minutes, and also bump develop to 0.9.0.

**Comment by detar** [comment]
Hi Mathias,

Thank you for the speedy diagnosis.  Steve will let us know if that 
fixes the problem.

Best,

Carleton


On 6/1/2016 7:19 AM, Mathias Wagner wrote:
>
> I just had a quick look at the milc interface code. For eigcg and 
> multi shift clover there is a line
>
> |invertParam.clover_coeff = clover_coeff; |
>
> this seems to be missing for |qudaCloverinvert|.
>
> Can you try if adding this line to |milc_interface.cpp| (line ~ 1460) 
> fixes the issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/lattice/quda/issues/477#issuecomment-222989439>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AF_j3lgbVv8HF2-i8AyoY_X_y3OztqmEks5qHYbkgaJpZM4Irhw8>.
>

-- 
Carleton DeTar
Department of Physics and Astronomy
University of Utah

**Comment by stevengottlieb** [comment]
You are correct about my being in the develop branch.  But here is a
stupid question, why is only the develop branch shown?

login2 quda-0.8.0/quda-0.8.0> git branch
* develop

My reading of the help is that all branches should be shown.  Is the
problem that my clone request was too specific?  I guess I can play with
that on my own.

Steve

**Comment by maddyscientist** [comment]
@stevengottlieb git is only displaying the branches you have locally used.  To show the remote branches, use `git branch -r` or `git branch -a` to show all branches.

**Comment by mathiaswagner** [comment]
From gitref.org:
Without arguments, git branch will list out the **local** branches that you have.

The clone behavior is describe at https://git-scm.com/docs/git-clone 

_Develop_ is now the default branch so that a git clone will get you on the development branch by default. This helps with the development process (pull requests will by default be created to pull something into develop) but of course can lead to confusion with people expecting to get master (the latest released version).

**Comment by stevengottlieb** [comment]
Thanks.  I actually figured that out when I started playing.  I guess I
missed the word local when I looked at the output from
git help branch.

Thanks to Mathias for pointing that out.  Maybe time to reread the git
manual Kate referred me to some time ago.

**Comment by AlexVaq** [comment]
Also, I don’t believe you’ll have this problem now, but it’s not a bad idea to refresh the local references to the remote repository by running “git fetch” from time to time. This will update the references to the branches stored locally, so if someone added a new branch, or a branch was updated, you’ll see it in your local machine.
