### ISSUE TITLE
Documentation for QUDA Dslash test

### ISSUE THREAD

**Issue by dipsankarb** [lattice/quda#482]
Hi,

I am trying to run QUDA Dslash test with MPI. When I run with 2 processes (on one node with multiple GPUs) I get this error: Running from test directory inside my build.

$ mpirun -np 2 gpu01 gpu01 ./dslash_test
ERROR: ERROR: Communication grid size declared via initCommsGridQuda() does not match total number of MPI ranks (1 != 2)Communication grid size declared via initCommsGridQuda() does not match total number of MPI ranks (1 != 2) (rank 0, host gpu01.cluster, /home/n01/quda/lib/comm_mpi.cpp:68 in comm_init())
 (rank 1, host gpu01.cluster, /home/n01/quda/lib/comm_mpi.cpp:68 in comm_init())
       last kernel called was (name=,volume=,aux=)
       last kernel called was (name=,volume=,aux=)
[cli_1]: [cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

I have enabled support for multi gpu and GDR while configuring. I think I need to pass some additional parameters to dslash for running it properly with multiple processes. Unfortunately I am unable to locate any documentation for QUDA. The one pointed here : http://lattice.github.io/quda-ref/v0.8.0/
does not exist. Please help.

**Comment by AlexVaq** [comment]
You need to specify the local lattice size with --xdim, --ydim, --zdim and --tdim, and then you should tell QUDA how you are partitioning your lattice with --xgridsize, --ygridsize... As a default, the gridsize is 1 on every dimension, implying you use only 1 gpu, but QUDA binds gpus to MPI processes, so you'll need to set one gridsize to 2.

I suggest you run ./dslash_test --help to understand some of these parameters better.

**Comment by dipsankarb** [comment]
That helps. Thanks a lot.

**Comment by maddyscientist** [comment]
We should fix that bad link.  Thanks for reporting that.  Also, there is documentation on the wiki site

https://github.com/lattice/quda/wiki

Note that GPU direct rdma support doesn't necessarily improve performance and this support is experimental.  In general it's probably best to disable it unless you find a speed up from it `GPU_COMMS=no`.

**Comment by dipsankarb** [comment]
I am not seeing good scaling with the increase in number of GPUs. For example, if I run keeping xdim, ydim, zdim and tdim fixed at 48. Then I run as follows:

$ mpirun -np 2 gpu01 gpu01 ./dslash_test  --xdim 48 --ydim 48 --zdim 48 --tdim 48 --xgridsize 2 --ygridsize 1

Numbers:

xgrid 2 ygrid 1 (2 procs on 1 K80 1 node which is basically 2 GPUs)

endQuda Total time = 0.1826 secs
initQuda-endQuda Total time = 93.1645 secs
QUDA Total time = 3.44325 secs

xgrid 2 ygrid 2 (4 procs 1 node 2 K80s)

endQuda Total time = 0.352839 secs
initQuda-endQuda Total time = 131.197 secs
QUDA Total time = 29.6026 secs

xgrid 4 ygrid 2 (8 procs 2 nodes 4 K80s (2 per node))

endQuda Total time = 0.280718 secs
initQuda-endQuda Total time = 156.035 secs
QUDA Total time = 35.4498 secs

In this context, please let me know if the numbers are making sense. Am I running it correctly
as its supposed to for best performance?

I am using a CUDA aware
MPI and GDR benefits will come into picture only if the communications are CUDA aware i.e; 
the MPI comms are working directly over GPU buffers and are not staged through the host. I can
go into the code and see what is implemented but from initial runs I can see that the communications
are happening over host which does not help with GDR. Please let me know you thoughts/comments
on this.

Also, the documentation in the github wiki is very brief and is not very informative. Will help if I can
get a bit more informative wiki/documentation. If the one that is supposed to be in the broken link is
back up, I can go through it and see if it helps.

Thanks again.

**Comment by AlexVaq** [comment]
I assume you’re keeping the local volume (xdim, ydim…) fixed, but you increase the number of gpus (and hence the total volume) so you’re trying to test weak scaling. In a good environment (inifiniband or equivalent, no serious networking problems and gpus properly configured) the weak scaling of QUDA is extremely good, so I would expect almost perfect weak scaling (same timing even though you’re increasing the volume), even if you don’t see direct MPI comms on gpus and they go through the host (QUDA also overlaps computations and transfers, so depending on the volume you might not get much from this feature).

The only two things that come to my mind are:

- In principle, QUDA is able to assign a different gpu per process, and I’ve never seen this mechanism to go wrong, but you might want to make sure that indeed each gpu has a different process. While running, check nvidia-smi in all the nodes and see if there is only a process per gpu.

- You might want to try partitioning in t and z. Although nowadays QUDA has evolved a lot and it shouldn’t matter that much how you partition your lattice, in principle it’s easier to partition in t, then in z, then in y and finally in x, due to the way the data is internally stored. So you can start with —tgridsize 2, and then try —tgridsize 2 —zgridsize 2.

I agree we should do a big effort to improve the documentation…

Let me know if I can help you with something else. Are you running in JURECA by some chance?

**Comment by maddyscientist** [comment]
Also, when running dslash_test, the metric you should be looking at is GFLOPS, which dslash_test reports per GPU.  The output timing information that you quote includes the QUDA initialization overheads, such as creating the GPU context.  In a real application these overheads are negligible, but in a unit test such as this, they dominate; hence reported kernel performance is more relevant.

**Comment by AlexVaq** [comment]
Yes, definitely @maddyscientist is right. You might want to try ./invert_test, which is more computational intensive, and check the GFlop count there. Warm-up time in a multigpu environment can be high sometimes, depending on the machine.

**Comment by dipsankarb** [comment]
I am running on our local academic cluster which we regularly use for running several HPC 
applications and system software and am confident that all the configurations are correct and
have observed benefits with GDR and MPI in several of our previous works. I have done
nvidia-smi and top to ensure that all unique GPUs are getting selected by QUDA and peer
access is also getting enabled for my multi-gpu build.

Currently I am still seeing a similar behavior with QUDA. I ran invert_test and here are the 
numbers that I am getting.

2 processes: (1 node 2 gpu)
$ mpirun -np 2 -hostfile hf ./invert_test --tgridsize 2 --zgridsize 1

Done: 30 iter / 0.270839 secs = 315.607 Gflops, total time = 1.72 secs

4 procs (1 node 4 gpus)

$mpirun -np 4 -hostfile hf ./invert_test --tgridsize 2 --zgridsize 2

Done: 30 iter / 0.284999 secs = 599.853 Gflops, total time = 1.77 secs

8 procs (2 nodes 8 gpus)

$mpirun -np 8 -hostfile hf ./invert_test --tgridsize 2 --zgridsize 2 --ygridsize 2

Done: 30 iter / 0.257834 secs = 1326.11 Gflops, total time = 4.53 secs

As I see, GFLOPs goes up but the running time does not. Can you please let me know if
this is making sense? If GFLOPs is going up then we must see the execution time improving
as well. In this context, I can see the utilization scaling but not the runtimes. Could you please
let me know if you have any ideas about how to go about it?

**Comment by maddyscientist** [comment]
The benchmark you are running here is weak scaling, so constant execution time is desirable.  You need to decrease the local problem size (`--size`) so that the product with the inter GPU grid (`--grid`) is constant to do a strong scaling test.
