### ISSUE TITLE
remove autoconf support

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#516]
Maintaining autoconf and cmake seems like a waste of time.
The autoconf builds have already been removed from Jenkins.
In a first step I would like to at least remove configure from all documentation for 0.9 and stop shipping the `configure`and maybe renaming the `Makefile` script so that it had to be actively re-enabled.

After shipping 0.9 we should remove all autoconf / make remainders.

**Comment by mathiaswagner** [comment]
remove it fully at some point for 1.0

**Comment by maddyscientist** [comment]
This has long since been done.
