### ISSUE TITLE
Test executables appear to not build

### ISSUE THREAD

**Issue by weinbe2** [lattice/quda#517]
Hey all,

After grabbing a recent version of quda from develop, I've noticed that none of the test executables build after an appropriate ccmake/make -j 16. I didn't have this issue about a week ago (maybe  a3d95c8 is the culprit? not familiar enough with cmake to know). 'libquda.a' still builds and appears in the /lib directory (though I currently have no executable to link against it to attempt to verify it). 

The build is out-of-source. The only QUDA build flags I have 'ON' are QUDA_DIRAC_WILSON, QUDA_INTERFACE_QDP (which has sufficed to get 'invert_test' to automatically build before). The only advanced options I've dug into are changing the default c++ compiler to g++ (from literally c++). I noticed that there's now a new advanced option QUDA_BUILD_ALL_TESTS (which I've left set to the default 'ON'). 

Has anyone else hit this issue?

**Comment by weinbe2** [comment]
Ah, I guess I was a bit confused by the description in commit #514 ---I assumed 'QUDA_BUILD_ALL_TESTS' = 'ON' would explicitly compile and link the tests, as was the old behavior. It appears that setting it to 'ON' it still generates the targets, so an explicit (for example) 'make invert_test' did successfully compile a running version of the test. All good on the eastern front.

**Comment by mathiaswagner** [comment]
Reopened to investigate.

By default all tests should build and by setting `QUDA_BUILD_ALL_TESTS = OFF` the tests should not build but the targets should be generated.
It seems like this is not what happens.

**Comment by mathiaswagner** [comment]
Inconsistent use of `QUDA_BUILD_ALL_TESTS` and `QUDA_BUILDALLTESTS` is never a good idea. Just checking whether my fix now really works as intended.
