### ISSUE TITLE
build quda as shared library

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#524]
It might be desirable to build quda a a shared library in some cases. See e.g. #454 

Currently there are two issues with that:
* The separation into cpp and cu files (introduced to compile cpp files first to catch errors there without having to wait on the longer cuda compilation) doesn't work with a shared library. 

* `covDev.cu` and `llfat_quda.cu` remove function bodies if some feature are removed. This prevent linking. The `ifdef`s need to be modified.

Building as a shared library should be an option in cmake, maybe something like `QUDA_BUILD_SHARED_LIB`.

**Comment by mathiaswagner** [comment]
@viktordick Just pushed some hacks to feature/shared_lib. Do you mind giving it a try?

**Comment by viktordick** [comment]
Sorry, I had no time until now. I just pulled the current version (ca9c3b94) and tried it, but there are still some covdev errors. Maybe I should mention that I built with every non-advanced QUDA_... option OFF except for QUDA_DIRAC_WILSON, QUDA_INTERFACE_MILC, QUDA_INTERFACE_QDP and QUDA_MPI (and QUDA_GPU_ARCH set to sm_35). The errors are
```
/home/viktor/quda/lib/dslash_core/covDev_mu0_core.h(220): error: no instance of function template "quda::covdev::coordsFromFaceIndex" matches the argument list
            argument types are: (int, int, int, int, int, int, int, const int, const int, const int, const int, const int [4])
```
and other similar ones.

**Comment by mathiaswagner** [comment]
Our Jenkins server triggered that as well, see #526.
