### ISSUE TITLE
QUDA doesn't build with cmake 3.7

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#528]
Reported by Carleton and Olaf and I can reproduce it locally:

```
nvcc fatal   : Stray '"' character
```

Workaround is to use cmake 3.6.3 from https://cmake.org/files/v3.6/

I am not sure whether this bug should / can be fixed on the QUDA side or whether it needs to be fixed in cmake but at least want to track it here.

**Comment by mathiaswagner** [comment]
workaround in branch hotfix/cmake37_workaround 

Should not break anything in quda.

@detar If cmake 3.6 is not an option hopefully this will work for you as well. Need to check whether there is a cleaner solution but I want to get this in asap.

**Comment by detar** [comment]
Thanks, Mathias.  For now the old gnu configure/make seems to work for 
me.  If not, I'll try 3.6.

Best,
Carleton

**Comment by mathiaswagner** [comment]
PR #530 should fix this.

**Comment by maddyscientist** [comment]
#530 is merged into develop, so closing this.
