### ISSUE TITLE
Support MAGMA built with CMake

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#534]
If MAGMA is build with CMake, then when trying to set the MAGMA library location with QUDA's CMake build, an error message is given, and compilation fails
```
CMake Error at CMakeLists.txt:215 (message):
  message called with incorrect number of arguments
```

**Comment by cpviolator** [comment]
This is problem I encountered. to solve it I rewrote line 213 of `CMakeLists.txt` to have quotations around the argument:

```c++
 message("${MAGMA_INCLUDEDIR}")
```
and gave the explicit location of `magma.h` at line 17 of `blas_magma.cu`

**Comment by mathiaswagner** [comment]
I believe @cpviolator already has the solution but @maddyscientist do you have MAGMA build with CMake somewhere on your workstation so I can reproduce that?

**Comment by cpviolator** [comment]
@mathiaswagner I used the OPENBLAS version of `make.inc` to build MAGMA in my directory on NVsocal2 (`/scratch/CPviolator/magma-1.7.0`) but there is a build with CMAKE located at `/scratch/CPviolator/magma-1.7.0_CMAKE` File permissions should be good on both.

**Comment by mathiaswagner** [comment]
Is this still an issue?

**Comment by mathiaswagner** [comment]
Closing as nobody complained for a long time.
