### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#539]
Makefile in develop contains a reference to staggered_oprod_new.o but I don't see the corresponding source file. Is it missing?

**Comment by maddyscientist** [comment]
That issue was fixed with #536.

**Comment by alexstrel** [comment]
it seems develop does not reflect changes from https://github.com/lattice/quda/pull/536/commits/e4bd7c044bb1f9047ff36d506773b1b0b42c1cea

**Comment by maddyscientist** [comment]
This is very strange.  @mathiaswagner any idea what's going on here?

**Comment by mathiaswagner** [comment]
Looks weird in the first place. No idea yet.

**Comment by alexstrel** [comment]
In any case, I think it would be helpful if jenkins could also verify any update of the develop, i.e., after each merge.

**Comment by mathiaswagner** [comment]
We don't use configure anymore in Jenkins ...

**Comment by mathiaswagner** [comment]
But the thing is that the merge commit has changed fewer files than the pr showed.

**Comment by maddyscientist** [comment]
Closing since I have just merged #543 .
