### ISSUE TITLE
Presence of staggered_oprod_new.o in lib/Makefile prevents QUDA building without CMake

### ISSUE THREAD

**Issue by bjoo** [lattice/quda#543]
I pulled QUDA this morning and it complained that it couldn't make staggered_oprod_new.o 
Indeed there was no .cu file there in 'develop' and this file didn't seem to appear in CMakeLists.txt.
I have removed this file from lib/Makefile and am doing a test build. Once that is finished, I will pull the fix and create a pull req.

**Comment by alexstrel** [comment]
it was pointed out in https://github.com/lattice/quda/issues/539

**Comment by stevengottlieb** [comment]
I had the same problem last night and got around it by copying
staggered_oprod.o to staggered_oprod_new.o.  I am glad to hear of a more
sensible fix.

**Comment by detar** [comment]
I had this problem with the configure/make build, but not with cmake.

**Comment by bjoo** [comment]
@alexstrel, Indeed and there was a comment that it was fixed, but maybe not yet seemingly, or perhaps only in the CMake version. Anyway, I've submitted the pull, and it passed its testing. Could someone please review and merge?

**Comment by alexstrel** [comment]
no the contrary, it turn out that some of the previous merge processes was broken.

**Comment by maddyscientist** [comment]
This is closed now, but just to comment that @alexstrel's comment is correct.  This issue was fixed with pull #536 which Github reports successively merged without any issues, but it didn't update the lib/Makefile in develop branch when it did the merge.  This is rather troubling, though all other changes from the pull appear to have been applied.  No idea what caused this issue, a bug in git / Github / or something else?

**Comment by bjoo** [comment]
Hi All, 
 Indeed. I tried to pull after Kate’s last message, and got a warning that my version of develop and the repository version have diverged.
So for now I have backed up that directory and recloned… Let me check how this latest pull does.

Best, 
 B
> On Dec 22, 2016, at 6:05 PM, maddyscientist <notifications@github.com> wrote:
> 
> This is closed now, but just to comment that @alexstrel's comment is correct. This issue was fixed with pull #536 which Github reports successively merged without any issues, but it didn't update the lib/Makefile in develop branch when it did the merge. This is rather troubling, though all other changes from the pull appear to have been applied. No idea what caused this issue, a bug in git / Github / or something else?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
