### ISSUE TITLE
Implement Gaussian/Wuppertal smearing

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#546]
We should implement Wuppertal smearing into QUDA.

Notes from @ssyr:
> Wuppertal smearing is repeated application of the nearest-neighbor Laplacian + constant,
> (psi^{N+1})_x = A * (psi^{N})_x + B* \sum_\mu 
> (  U_{x,\mu} * psi^{N})_{x+\mu} + U_{x-\mu,\mu}^\dag * psi^{N})_{x-\mu} )
> for mu=1,2,3(x,y,z) in 3-d case.
>
> It's better to keep coefficients A,B and summation directions \mu as parameters for generality. U is the gauge field (color matrix), psi is at least a color vector, but it may have indices to embarrassingly-parallelize over.

With the generic framework we now have in QUDA, this should be easy to implement.

@ssyr, when you say that psi can have indices, do you mean spin indices, or a flavor/source index.  What are the possible ranges that this index can vary over?  The nature of this index will tell me if this should be implemented as an internal degree of freedom or as an effective fifth space-time dimension.

**Comment by cpviolator** [comment]
CPS has a good Gaussian Smearing routine. When I wrote stout for CPS, transcribing it over to QUDA (minus the bug that was in there) was pretty straightforward. The only major differences was how link variables were fetched.
If I may answer the question you asked, the Gaussian smearing operator has only colour and spacetime indices, and is therefore diagonal in spin-space. A spin-colour diluted point source \phi will, after repeated application of the Gaussian Kernel, smear out to populate only the spacetime and colour components of the original spin index.

If this gets done, one could also consider implementing the Laplace-Heaviside smearing technique. Eigenvectors of the Gaussian Smearing kernel (Laplacian) are used as source vectors, up to some cut-off (Heaviside) in the eigenvalues.

**Comment by maddyscientist** [comment]
As a prototype for implementing this, I implemented a standard 4-d gauge Laplace in 7684193231f23093f9183da333cb11c8177ad91f (using the high-level C++ that I eventually intend to rewrite all Dslash kernels with).  This can be used as skeleton for implementing this feature.

**Comment by kostrzewa** [comment]
@maddyscientist out of curiosity, what is the performance of the high-level C++ Laplacian like?

**Comment by maddyscientist** [comment]
Performance is the same as low-level C code would be:
* Single precision, 12 reconstruct, applying the operator to just one parity: 595 GFLOPS (627 GB/s)
* Single precision, 12 reconstruct, applying the operator to just both parities: 305 GFLOPS (655 GB/s)
* Double precision, 12 reconstruct, applying the operator to just one parity: 595 GFLOPS (627 GB/s)
* Double precision, 12 reconstruct, applying the operator to just both parities: 411 GFLOPS (882 GB/s)

**Comment by sbacchio** [comment]
I did a push to feature/laplace which adds a first implementation of the Wuppertal smearing.
@maddyscientist, I hope is fine I pushed there.

For the next step, shall I create a function in the interface which does "performNWuppertalStep"? something similar to what is done for the APE smearing?

**Comment by maddyscientist** [comment]
Sounds perfect!

**Comment by maddyscientist** [comment]
I should note that I haven't tested the multi-GPU yet for the Laplace operator, should get that done in the next few days......

**Comment by sbacchio** [comment]
Ok, I followed how you constructed the laplace operator, but it is independent from it. Now I will do the function in the interface and then test if at least everything works with single/multi-GPU and if I obtain the same results in the two cases.
Then I should do a cross check with some other code in order to see if everything is implemented correctly.

**Comment by ssyr** [comment]
> I should note that I haven't tested the multi-GPU yet for the Laplace operator, should get that done in the next few days......
does it overlap communications and computing?

**Comment by maddyscientist** [comment]
@ssyr No, it presently does blocking comms.  Not hard to add, but I won't do this until someone actually needs it 😄

**Comment by sbacchio** [comment]
I've had finally time to test it. With the last commits to feature/laplace everything works fine and the results have been crosschecked with our production code.

The function I've done in the interface uses the gaugeSmeared, if created, or gaugePrecise otherwise.

When feature/laplace will be merged to the develop branch, this issue can be closed.
