### ISSUE TITLE
Hisq force prints negative performance / test runs in segfault on large volumes

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#557]
When trying to run on a large local volume (64^3x16) the HISQ force path test segfaults. For 32^3x16 it prints negative performance values.

Might well be integer calculations that overflow and need to be replaced with long.

**Comment by mathiaswagner** [comment]
Probably related:
```
mpirun -np 2 ./llfat_test --xdim 64 --ydim 64 --zdim 32 --ygridsize 1 --zgridsize 2 --tdim 16 --verify false
```

yields
```
ERROR: (CUDA) an illegal memory access was encountered (rank 0, host hsw215, /home/mathiasw/quda/lib/llfat_quda_itf.cpp:168 in llfat_cuda_ex())
       last kernel called was (name=N4quda14ExtractGhostExIdLi18ELi4ELi3ENS_5gauge11FloatNOrderIdLi18ELi2ELi18EEEEE,volume=68x68x36x20,aux=prec=8,stride=1914336,extract=0,dimension=3,geometry=4)
ERROR: (CUDA) an illegal memory access was encountered (rank 1, host hsw215, /home/mathiasw/quda/lib/llfat_quda_itf.cpp:168 in llfat_cuda_ex())
       last kernel called was (name=N4quda14ExtractGhostExIdLi18ELi4ELi3ENS_5gauge11FloatNOrderIdLi18ELi2ELi18EEEEE,volume=68x68x36x20,aux=prec=8,stride=1914336,extract=0,dimension=3,geometry=4)
```

running a smaller local volume
```
mpirun -np 2 ./llfat_test --xdim 64 --ydim 32 --zdim 32 --ygridsize 1 --zgridsize 2 --tdim 16 --verify false
```
or
```
mpirun -np 4 ./llfat_test --xdim 64 --ydim 32 --zdim 32 --ygridsize 2 --zgridsize 2 --tdim 16 --verify false
```

is fine.

**Comment by maddyscientist** [comment]
So the segmentation fault occurs with both the llfat_test (fat and long link creation) as well as the hisq force path test?  I'm wondering it's a texture size limit: 64x64x32x16x9 = 18874368 texels (using double2 or float2 storage) which is greater than the 1-d texture size of 2^27.

However, the textures are split into even and odd components with separate textures, which is leads to 9437184 which is less than 2^27.

Does the problem occur with the gauge force as well?  Note that the gauge force doesn't use textures, so if it works fine then this would point to the textures as being the culprit.

The other that's possible is that it's simply running out of memory and there's some missing error checking?  I see that at half the volume, it consumes 5077.2 MiB, which when doubled should still fit on a 12 GiB card.

**Comment by maddyscientist** [comment]
I did a quick run through cuda-gdb, and the failure in llfat is coming from the long-link computation (line 1049 in llfat_core.h where the field is loaded from memory) and is a simple out of bounds load request.

**Comment by mathiaswagner** [comment]
I'll look into it. Just noted while running some tests and did not want to forget to create an issue.

**Comment by maddyscientist** [comment]
Ok, it is the textures limit as I thought.  The input fields are extended in all dimensions regardless of whether the dimension is partitioned or not.  This is enough to make each parity greater than 2^27 texels.

Two solutions possible: only extend the dimensions that are partitioned (which is how it should have been in the first place) or switch to ldg loads.  Both of these are probably desirable.

**Comment by maddyscientist** [comment]
Just an update that I've fixed the issue in the fat and long link generation.  Will be pushing a branch shortly (it's a complete rewrite of the fat-link code, like has already been done for the gauge force code).

**Comment by stevengottlieb** [comment]
That sounds great, Kate.  I am eager to test and benchmark it.

Steve
