### ISSUE TITLE
Vanillla quda_develop build error.

### ISSUE THREAD

**Issue by cpviolator** [lattice/quda#559]
I'm just adding a few bits to the develop branch and this CMake error is preventing the build

```c++
CMake Error at lib/CMakeLists.txt:142 (install):
   install TARGETS given no ARCHIVE DESTINATION for static library target
   "quda".
 CMake Error at lib/CMakeLists.txt:154 (export):
   export Export set "qudaTargets" not found.
```
Not doing anything fancy, just downloading the latest develop branch, linking to MAGMA, and enabling Multigrid.  Can anyone tell where I'm going wrong? I can't see where in CMake I can even access these variables. Using CMake 3.1.0 on Stampede TACC

**Comment by mathiaswagner** [comment]
No clue yet. When does this error occur? Right after calling cmake in a fresh build dir?

I haven't actually tried cmake 3.1 with the recent changes. Do you have access to a newer cmake version?
I'll give it a try with 3.1 later today.

**Comment by mathiaswagner** [comment]
Just created a pull request #561. Fixes the issues for me (reproduced with cmake 3.2.2)
