### ISSUE TITLE
trouble testing on a node with 4 P100 GPUs

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#569]
In December, I was able to run benchmarks on a node with 4 GPUs without problem using the develop branch.  The output contains this information:
Peer-to-peer enabled for rank 0 (gpu=0) with neighbor 1 (gpu=1) dir=0, dim=2
Peer-to-peer enabled for rank 1 (gpu=1) with neighbor 0 (gpu=0) dir=0, dim=2
Peer-to-peer enabled for rank 2 (gpu=2) with neighbor 3 (gpu=3) dir=0, dim=2
Peer-to-peer enabled for rank 3 (gpu=3) with neighbor 2 (gpu=2) dir=0, dim=2
Peer-to-peer enabled for rank 1 (gpu=1) with neighbor 0 (gpu=0) dir=1, dim=2
Peer-to-peer enabled for rank 2 (gpu=2) with neighbor 3 (gpu=3) dir=1, dim=2
Peer-to-peer enabled for rank 0 (gpu=0) with neighbor 1 (gpu=1) dir=1, dim=2
Peer-to-peer enabled for rank 3 (gpu=3) with neighbor 2 (gpu=2) dir=1, dim=2
QUDA 0.9.0 (git v0.8.0-1411-g4c629b7)
Found device 0: Tesla P100-PCIE-16GB
Found device 1: Tesla P100-PCIE-16GB
Found device 2: Tesla P100-PCIE-16GB
Found device 3: Tesla P100-PCIE-16GB
Using device 0: Tesla P100-PCIE-16GB
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
WARNING: Using device memory pool allocator
WARNING: Using pinned memory pool allocator

I was able to compile the hotfix_hisq_link version of the code, but  things look different and both MPI tasks try to use the same GPU:
QUDA 0.9.0 (git v0.8.0-1550-g4879aed)
QUDA 0.9.0 (git v0.8.0-1550-g4879aed)
Found device 0: Tesla P100-PCIE-16GB
Found device 1: Tesla P100-PCIE-16GB
Found device 2: Tesla P100-PCIE-16GB
Found device 3: Tesla P100-PCIE-16GB
Found device 0: Tesla P100-PCIE-16GB
Using device 0: Tesla P100-PCIE-16GB
Found device 1: Tesla P100-PCIE-16GB
Found device 2: Tesla P100-PCIE-16GB
Found device 3: Tesla P100-PCIE-16GB
Using device 0: Tesla P100-PCIE-16GB
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
ERROR: (CUDA) out of memory (/home/sgindiana/lustre/quda/lib/interface_quda.cpp:485 in initQudaMemory())

I did not think I had configured things differently and wonder why the behavior is different and how I can fix this.

Thanks for your help,
Steve

**Comment by maddyscientist** [comment]
It looks like it's dying immediately.  A couple of things to try:
* if you are able to reset the node, can you do this and retry?
* does running nvidia-smi reveal anything already running on the system that could consuming memory?
* Can you confirm you have compiled for GPU architecture sm60?

**Comment by stevengottlieb** [comment]
Thanks for the quick response.  
a) I cannot reset the node since it is not mine and it is in Illinois.

b) Good call.  There is a batch system on this node and I have been
asked to only use it via the batch system, but I get the impression that
maybe others do not adhere to this practice.  Looks like three of the
nodes don't have much memory available.

[sgindiana@nano7 ~]$ nvidia-smi
Sat Feb 25 22:11:38 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48
|
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile
Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util
Compute M. |
|===============================+======================
+======================|
|   0  Tesla P100-PCIE...  On   | 0000:05:00.0     Off |
0 |
| N/A   40C    P0    46W / 250W |  15609MiB / 16276MiB |    100%
Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 0000:09:00.0     Off |
0 |
| N/A   45C    P0    45W / 250W |  15609MiB / 16276MiB |      0%
Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-PCIE...  On   | 0000:84:00.0     Off |
0 |
| N/A   34C    P0   179W / 250W |  15609MiB / 16276MiB |     41%
Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-PCIE...  On   | 0000:88:00.0     Off |
0 |
| N/A   62C    P0   116W / 250W |    289MiB / 16276MiB |     80%
Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU
Memory |
|  GPU       PID  Type  Process name                               Usage
|
|
=============================================================================|
|    0     19676    C   python
15591MiB |
|    1     19705    C   python
15591MiB |
|    2     19963    C   python
15591MiB |
|    3     23910    C   john-1.8.0-jumbo-1/run/john
289MiB |
+-----------------------------------------------------------------------------+
c)  from a run of ccmake in the build directory:
QUDA_GPU_ARCH                    sm_60

Thanks for the help.

**Comment by cpviolator** [comment]
Steven,

Just some reassurance on this issue. A few months ago I was running into
seemingly random 'out of memory' issues when compiling on the Stampede
login nodes https://github.com/lattice/quda/issues/522. Over the course of
about a month (Sep-Oct), some QUDA pushes would compile, and some would
fail. Recent pushes do not seem to be affected. May I ask, what is the date
of your last QUDA pull?

Dean

**Comment by maddyscientist** [comment]
@stevengottlieb Looks like that this isn't a QUDA problem, and it's just because the GPUs were being swamped by other users.  

I do note however, that the GPU driver used on that system is not a recommended one for P100 systems.  Either use 361.xx or 375 and later.  368 is only supported on non-P100 Pascal systems.

**Comment by stevengottlieb** [comment]
@maddyscientist I agree about it not being a QUDA problem.  Thanks for
the information about recommended drivers.

**Comment by maddyscientist** [comment]
Closing this since this is not a QUDA bug.
