### ISSUE TITLE
Implement correct flop and byte counts for the Dslash kernels

### ISSUE THREAD

**Issue by rbabich** [lattice/quda#57]
For the tuning to print correct performance numbers, all children of Tunable must properly overload Tunable::flops() and Tunable::bytes().  This is going to be tedious for the multi-GPU Dslash kernels.

We'll know we're done when we can make flops() and bytes() pure virtual functions in the base class.

**Comment by mathiaswagner** [comment]
I think given the age of this bug this is also not necessary a thing for 0.7.1 ?

**Comment by mikeaclark** [comment]
It's not necessary, I was just going to spend a cursory 30 minutes thinking if this is something can be added without too much fuss.

**Comment by mathiaswagner** [comment]
Closed with #274.
