### ISSUE TITLE
Investigate double-half CG solver for twisted clover

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#583]
Twisted clover fermions with double-half CG solver is very unstable compared to clover or regular twisted-mass fermions.  Perhaps related to #582.

**Comment by mathiaswagner** [comment]
New or old reliable updates?

**Comment by maddyscientist** [comment]
It's broken either way

**Comment by maddyscientist** [comment]
Note for self, use these lattices for testing:

/scratch/ETMC_gauge_configurations/tmclover_nf2/cA2.60.32

with kappa = 0.1373, mu = 0.006, clover coeff = 1.57551

**Comment by kostrzewa** [comment]
It seems that ```QUDA_DYNAMIC_CLOVER``` helps (i.e., it works then). This is an improvement from a few months ago. 

Tested with 65a2b78b5c3efd041e19d1b88367faf5f0a2dac8 of feature/multigrid

**Comment by kostrzewa** [comment]
@maddyscientist had an argument for this, noting that storing and loading in half precision, leads to some loss of precision. This could be especially severe for twisted-clover because we have [ (1+C_ee)^2 + \mu^2 ]^-1, rather than just the inverse itself.

**Comment by kostrzewa** [comment]
stability confirmed up to 64c128

**Comment by maddyscientist** [comment]
@kostrzewa can you test this with the develop branch enabling @mathiaswagner's new reliable update scheme (enabled with `QUDA_ALTRELIABLE=ON`).  Would be good to see iteration count differences for pure double, double-single and double-half using the old mechanism and the new one.

**Comment by kostrzewa** [comment]
will do

**Comment by maddyscientist** [comment]
Closed with #776
