### ISSUE TITLE
Ghost zones for individual elements in a composite container 

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#588]
Currently all elements of the composite spinor field container share a common ghost zone (derived for the whole container). This is not a problem for current algorithms in QUDA, but may result in the incorrect behaviour for some exotic scenarios (e.g., application of the dslash on a number of individual components within multi-threaded workflow)

**Comment by weinbe2** [comment]
Effectively addressed by multi-rhs support and ghost-only `ColorSpinorField`s: https://github.com/lattice/quda/pull/1333 for `QUDA_GHOST_FIELD_CREATE`, and I imagine various extensions in https://github.com/lattice/quda/pull/1465 ,
