### ISSUE TITLE
dslash_test fails with segfault for clover

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#598]
Not sure what the root cause is yet but before I forget:

```
[mathiasw@hsw215 qudabqcd_mvapich]$ mpirun -np 1 ./tests/dslash_test --dslash-type clover --prec double --recon 12 --dim 48 48 48 48 --gridsize 1 1 1 1
running the following test:
prec    recon   test_type     matpc_type   dagger   S_dim         T_dimension   Ls_dimension dslash_type    niter
double   12       0              even-even    0     48/ 48/ 48         48             16           clover   100
Grid partition info:     X  Y  Z  T
                         0  0  0  0
Randomizing fields... [hsw215:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)

```

**Comment by sbacchio** [comment]
Could it be an out of memory? A 48^4 lattice maybe doesn't fit on one node..

**Comment by mathiaswagner** [comment]
It does fit.

`$ mpirun -np 1 ./tests/invert_test --dslash-type clover --prec double --recon 12 --dim 48 48 48 48 --gridsize 1 1 1 1` runs fine. 
I guess it is an overflow in randomizing the fields.

**Comment by sbacchio** [comment]
I checked the code and actually could be due to that.
Indeed just before "Randomizing fields..." you have the following
```
  spinor = new cpuColorSpinorField(csParam);
  spinorOut = new cpuColorSpinorField(csParam);
  spinorRef = new cpuColorSpinorField(csParam);
  spinorTmp = new cpuColorSpinorField(csParam);
```
which allocates 4 spinor field on the cpu's that in double precision for a 48^4 lattice are 15.2 GB. I don't know the memory of your node, but this can make run out of memory. 
I just gave a quick look, but such a heavy allocation seems to not be done in invert_test for the cpu.

**Comment by cpviolator** [comment]
`dslash_invert_test.cpp` looks like it has outdated code compared to `invert_test.cpp` For example, in `dslash_test`
```c++
// construct input fields
  for (int dir = 0; dir < 4; dir++) hostGauge[dir] = malloc(V*gaugeSiteSize*gauge_param.cpu_prec);
```
but in `invert_test`
```c++
size_t gSize = (gauge_param.cpu_prec == QUDA_DOUBLE_PRECISION) ? sizeof(double) : sizeof(float);
...
for (int dir = 0; dir < 4; dir++) {
    gauge[dir] = malloc(V*gaugeSiteSize*gSize);
  }
```
