### ISSUE TITLE
tmclover-nondeg testing

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#610]
Issue to collect possible problems with new tmclover-nondeg operator by @AlexVaq

**Comment by kostrzewa** [comment]
Compilation results in warnings of the type:
```
/homec/hbn28/hbn288/code/quda-ndclover/lib/tmc_ndeg_dslash_def.h:433:0: warning: "READ_ACCUM_FLAVOR" redefined
 #define READ_ACCUM_FLAVOR READ_ACCUM_FLAVOR_HALF_TEX
 ^
```
Haven't seen this before, so I thought I'd mention it to begin with.

**Comment by kostrzewa** [comment]
There is probably still an issue in the dagger operator. First test:

1) invert using the NONDEG_DOUBLET (without clover). Confirm that this works and that the parameters are passed correctly.
2) switch on clover term but with csw=0.00001 and the same parameters as in 1.
    * solve diverges

I'll try to figure out what's going on.

**Comment by kostrzewa** [comment]
Interesting development: when I run this with just one process, the solver does not diverge, but the final residual is wrong.

**Comment by kostrzewa** [comment]
3. Setting epsilon to zero nodes not help.

**Comment by kostrzewa** [comment]
4. csw=0.000001, mu=0.000001, epsilon=0.02, kappa set to give a largish, positive PCAC mass does not help (solver converges, this is sort of a doublet of plain wilson quarks, after all, but the final residual is wrong)

**Comment by kostrzewa** [comment]
@AlexVaq is it normal that the "fused exterior" kernel is an empty file?

https://github.com/lattice/quda/blob/feature/nondeg-tmclover/lib/dslash_core/tmc_ndeg_fused_exterior_dslash_core.h

**Comment by kostrzewa** [comment]
Between ```tmc_core.h.old``` and ```tmc_core.h```, it seems that some of the Macros have been shortened (backslashes here and there have been removed). Was this intended?

**Comment by kostrzewa** [comment]
The corresponding tmclover (degenerate) operator converges fine and the residual is correct, so I'm guessing there's no problem there.

**Comment by AlexVaq** [comment]
No, hell, multigpu is not implemented yet, now I remember.

**Comment by AlexVaq** [comment]
Yes, I think that was intended. I'll try to find some time today to look into this. I'll review all the input you sent me first, thanks for doing this!

**Comment by kostrzewa** [comment]
Okay, sounds good. In the meantime, I compiled a single-GPU version of everything and I still find that the final residual is not correct for the tmclover-nondeg operator, even with mu=0.000001, muepsilon=0.000001, csw=0.000001 and a kappa value corresponding to a large, positive PCAC mass. For the same parameters, the corresponding standard non-degenerate operator gives the correct residual.

However, it's possible that there's also a problem on our end when checking the residual:

**tmclover-nondeg:**
```
# QUDA: CG: 0 iterations, <r,r> = 5.000000e-01, |r|/|b| = 1.000000e+00
# QUDA: CG: 1 iterations, <r,r> = 5.195678e-02, |r|/|b| = 3.223563e-01
# QUDA: CG: 2 iterations, <r,r> = 1.126367e-02, |r|/|b| = 1.500911e-01
# QUDA: CG: 3 iterations, <r,r> = 3.649150e-03, |r|/|b| = 8.543009e-02
# QUDA: CG: 4 iterations, <r,r> = 1.465928e-03, |r|/|b| = 5.414662e-02
# QUDA: CG: 5 iterations, <r,r> = 6.279729e-04, |r|/|b| = 3.543933e-02
# QUDA: CG: 6 iterations, <r,r> = 2.896888e-04, |r|/|b| = 2.407027e-02
# QUDA: CG: 7 iterations, <r,r> = 1.339482e-04, |r|/|b| = 1.636754e-02
# QUDA: CG: 8 iterations, <r,r> = 6.132145e-05, |r|/|b| = 1.107443e-02
# QUDA: CG: 9 iterations, <r,r> = 2.785905e-05, |r|/|b| = 7.464455e-03
# QUDA: CG: 10 iterations, <r,r> = 1.304747e-05, |r|/|b| = 5.108321e-03
# QUDA: CG: 11 iterations, <r,r> = 6.126405e-06, |r|/|b| = 3.500401e-03
# QUDA: CG: 12 iterations, <r,r> = 2.878901e-06, |r|/|b| = 2.399542e-03
# QUDA: CG: 13 iterations, <r,r> = 1.328796e-06, |r|/|b| = 1.630212e-03
# QUDA: CG: 14 iterations, <r,r> = 6.146954e-07, |r|/|b| = 1.108779e-03
# QUDA: CG: 15 iterations, <r,r> = 2.835097e-07, |r|/|b| = 7.530069e-04
# QUDA: CG: 16 iterations, <r,r> = 1.291092e-07, |r|/|b| = 5.081520e-04
# QUDA: CG: 17 iterations, <r,r> = 5.943964e-08, |r|/|b| = 3.447887e-04
# QUDA: CG: 18 iterations, <r,r> = 2.705007e-08, |r|/|b| = 2.325943e-04
# QUDA: CG: 19 iterations, <r,r> = 1.245889e-08, |r|/|b| = 1.578536e-04
# QUDA: CG: 20 iterations, <r,r> = 5.728359e-09, |r|/|b| = 1.070361e-04
# QUDA: CG: 21 iterations, <r,r> = 2.641217e-09, |r|/|b| = 7.268035e-05
# QUDA: CG: 22 iterations, <r,r> = 1.231507e-09, |r|/|b| = 4.962877e-05
# QUDA: CG: 23 iterations, <r,r> = 5.741610e-10, |r|/|b| = 3.388690e-05
# QUDA: CG: 24 iterations, <r,r> = 2.685939e-10, |r|/|b| = 2.317731e-05
# QUDA: CG: 25 iterations, <r,r> = 1.243666e-10, |r|/|b| = 1.577128e-05
# QUDA: CG: 26 iterations, <r,r> = 5.704737e-11, |r|/|b| = 1.068151e-05
# QUDA: CG: 27 iterations, <r,r> = 2.611062e-11, |r|/|b| = 7.226426e-06
# QUDA: CG: 28 iterations, <r,r> = 1.205770e-11, |r|/|b| = 4.910744e-06
# QUDA: CG: 29 iterations, <r,r> = 5.569817e-12, |r|/|b| = 3.337609e-06
# QUDA: CG: 30 iterations, <r,r> = 2.561639e-12, |r|/|b| = 2.263466e-06
# QUDA: CG: 31 iterations, <r,r> = 1.183362e-12, |r|/|b| = 1.538416e-06
# QUDA: CG: 32 iterations, <r,r> = 5.498945e-13, |r|/|b| = 1.048708e-06
# QUDA: CG: 33 iterations, <r,r> = 2.562015e-13, |r|/|b| = 7.158233e-07
# QUDA: CG: 34 iterations, <r,r> = 1.192874e-13, |r|/|b| = 4.884411e-07
# QUDA: CG: 35 iterations, <r,r> = 5.522111e-14, |r|/|b| = 3.323285e-07
# QUDA: CG: 36 iterations, <r,r> = 2.564353e-14, |r|/|b| = 2.264665e-07
# QUDA: CG: 37 iterations, <r,r> = 1.186777e-14, |r|/|b| = 1.540634e-07
# QUDA: CG: 38 iterations, <r,r> = 5.474087e-15, |r|/|b| = 1.046335e-07
# QUDA: CG: 39 iterations, <r,r> = 2.519870e-15, |r|/|b| = 7.099113e-08
# QUDA: CG: 40 iterations, <r,r> = 1.149171e-15, |r|/|b| = 4.794102e-08
# QUDA: CG: 41 iterations, <r,r> = 5.278817e-16, |r|/|b| = 3.249251e-08
# QUDA: CG: 42 iterations, <r,r> = 2.434790e-16, |r|/|b| = 2.206713e-08
# QUDA: CG: 43 iterations, <r,r> = 1.116175e-16, |r|/|b| = 1.494105e-08
# QUDA: CG: 44 iterations, <r,r> = 5.095717e-17, |r|/|b| = 1.009526e-08
[...]
# Inversion done in 44 iterations, squared residue = 4.453177e-01!
```

**tm-nondeg:**
```
# QUDA: CG: 0 iterations, <r,r> = 5.000000e-01, |r|/|b| = 1.000000e+00
# QUDA: CG: 1 iterations, <r,r> = 5.195678e-02, |r|/|b| = 3.223562e-01
# QUDA: CG: 2 iterations, <r,r> = 1.126367e-02, |r|/|b| = 1.500911e-01
# QUDA: CG: 3 iterations, <r,r> = 3.649150e-03, |r|/|b| = 8.543009e-02
# QUDA: CG: 4 iterations, <r,r> = 1.465928e-03, |r|/|b| = 5.414662e-02
# QUDA: CG: 5 iterations, <r,r> = 6.279729e-04, |r|/|b| = 3.543933e-02
# QUDA: CG: 6 iterations, <r,r> = 2.896888e-04, |r|/|b| = 2.407026e-02
# QUDA: CG: 7 iterations, <r,r> = 1.339482e-04, |r|/|b| = 1.636754e-02
# QUDA: CG: 8 iterations, <r,r> = 6.132144e-05, |r|/|b| = 1.107442e-02
# QUDA: CG: 9 iterations, <r,r> = 2.785904e-05, |r|/|b| = 7.464454e-03
# QUDA: CG: 10 iterations, <r,r> = 1.304747e-05, |r|/|b| = 5.108320e-03
# QUDA: CG: 11 iterations, <r,r> = 6.126403e-06, |r|/|b| = 3.500401e-03
# QUDA: CG: 12 iterations, <r,r> = 2.878900e-06, |r|/|b| = 2.399542e-03
# QUDA: CG: 13 iterations, <r,r> = 1.328795e-06, |r|/|b| = 1.630212e-03
# QUDA: CG: 14 iterations, <r,r> = 6.146951e-07, |r|/|b| = 1.108779e-03
# QUDA: CG: 15 iterations, <r,r> = 2.835096e-07, |r|/|b| = 7.530068e-04
# QUDA: CG: 16 iterations, <r,r> = 1.291091e-07, |r|/|b| = 5.081517e-04
# QUDA: CG: 17 iterations, <r,r> = 5.943957e-08, |r|/|b| = 3.447885e-04
# QUDA: CG: 18 iterations, <r,r> = 2.705002e-08, |r|/|b| = 2.325941e-04
# QUDA: CG: 19 iterations, <r,r> = 1.245885e-08, |r|/|b| = 1.578534e-04
# QUDA: CG: 20 iterations, <r,r> = 5.728352e-09, |r|/|b| = 1.070360e-04
# QUDA: CG: 21 iterations, <r,r> = 2.641212e-09, |r|/|b| = 7.268029e-05
# QUDA: CG: 22 iterations, <r,r> = 1.231505e-09, |r|/|b| = 4.962872e-05
# QUDA: CG: 23 iterations, <r,r> = 5.741599e-10, |r|/|b| = 3.388687e-05
# QUDA: CG: 24 iterations, <r,r> = 2.685932e-10, |r|/|b| = 2.317728e-05
# QUDA: CG: 25 iterations, <r,r> = 1.243663e-10, |r|/|b| = 1.577126e-05
# QUDA: CG: 26 iterations, <r,r> = 5.704718e-11, |r|/|b| = 1.068150e-05
# QUDA: CG: 27 iterations, <r,r> = 2.611053e-11, |r|/|b| = 7.226414e-06
# QUDA: CG: 28 iterations, <r,r> = 1.205767e-11, |r|/|b| = 4.910738e-06
# QUDA: CG: 29 iterations, <r,r> = 5.569798e-12, |r|/|b| = 3.337603e-06
# QUDA: CG: 30 iterations, <r,r> = 2.561631e-12, |r|/|b| = 2.263462e-06
# QUDA: CG: 31 iterations, <r,r> = 1.183359e-12, |r|/|b| = 1.538414e-06
# QUDA: CG: 32 iterations, <r,r> = 5.498928e-13, |r|/|b| = 1.048707e-06
# QUDA: CG: 33 iterations, <r,r> = 2.562007e-13, |r|/|b| = 7.158222e-07
# QUDA: CG: 34 iterations, <r,r> = 1.192869e-13, |r|/|b| = 4.884403e-07
# QUDA: CG: 35 iterations, <r,r> = 5.522088e-14, |r|/|b| = 3.323278e-07
# QUDA: CG: 36 iterations, <r,r> = 2.564343e-14, |r|/|b| = 2.264660e-07
# QUDA: CG: 37 iterations, <r,r> = 1.186774e-14, |r|/|b| = 1.540632e-07
# QUDA: CG: 38 iterations, <r,r> = 5.474071e-15, |r|/|b| = 1.046334e-07
# QUDA: CG: 39 iterations, <r,r> = 2.519861e-15, |r|/|b| = 7.099100e-08
# QUDA: CG: 40 iterations, <r,r> = 1.149167e-15, |r|/|b| = 4.794095e-08
# QUDA: CG: 41 iterations, <r,r> = 5.278803e-16, |r|/|b| = 3.249247e-08
# QUDA: CG: 42 iterations, <r,r> = 2.434784e-16, |r|/|b| = 2.206710e-08
# QUDA: CG: 43 iterations, <r,r> = 1.116173e-16, |r|/|b| = 1.494104e-08
# QUDA: CG: 44 iterations, <r,r> = 5.095701e-17, |r|/|b| = 1.009525e-08
[...]
# Inversion done in 44 iterations, squared residue = 5.095701e-17!
```

The similarity of the two solves suggests to me that they are doing exactly the same thing, as they should. Yet, the results seem to be inconsistent.


Or, perhaps, there is a problem with the reconstruction of the solution on the QUDA side?

**Comment by kostrzewa** [comment]
Adding non-zero values for mu and epsilon then leads to larger differences between the two solves. I still haven't gotten around to writing the test harness for the operators themselves, I'm afraid...

**Comment by AlexVaq** [comment]
Oh no, I'm aware that the dagger operator has a problem. I'd like to see a dslash test (not an inversion) of the non-daggered operator.

Also, the unpreconditioned operator (dagger, non-dagger) should be working. Did you try the CG on that one?

**Comment by AlexVaq** [comment]
I'm looking (a bit) into this now. So far I can only say that the unpreconditioned operator should work. The preconditioned operator is giving me some trouble, and requires further debugging. The compilation warning you saw before I think it's related to the dynamic clover inversion, but I'm not sure.

I think the way to go right now is to test the CG with the unpreconditioned operator. I'm really interested to see if that works. If you don't have an unpreconditioned solver in the tmLQCD library, you can always prepare the spinor, solve it with the preconditioned CG and then reconstruct the solution.

If that test fails, I'll kill myself...

**Comment by AlexVaq** [comment]
If you were not using the dynamical clover inverter, then the preconditioned operator was bound to fail, because in the calculation of the inverse clover the epsilon term was not taken into account. I'll push a fix for that.

**Comment by kostrzewa** [comment]
I will try to test the unpreconditioned inversion in the coming days. We don't have an implementation of the unpreconditioned operator, unfortunately. I was always using dynamical clover, on account of the finding that it is more stable.

As for the operator test harness, I still haven't gotten around to implementing it...

**Comment by AlexVaq** [comment]
Ok, now I tested non-dynamical clover and seems to agree with twisted mass non-degenerated in the dslash test. The preconditioned operator looks good, so maybe you want to have a look at that one.

My first test would be with a very small (negligible) clover coefficient (but not exactly 0 because then QUDA might throw it away and use twisted mass) and see if there is agreement. Then you can switch on the clover term and see what happens.

I'll look into the dynamical inversion now. I understood that the solver diverged there...
About the inversion test you did, I guess you are right about the reconstruction of the solution. I didn't look into that deeply, so it might be completely wrong.

Can't you try preconditioned solve with a preconditioned solution (no reconstruction)?

**Comment by AlexVaq** [comment]
In the inversion test (the one you show that iteration per iteration it seems that twisted-mass and twisted-clover are doing the same):
- Which kind of preconditioning are you using, symmetric or asymmetric?
- Is the source prepared, or you prepare directly the halfspinor and the solution is only reconstructed?

**Comment by kostrzewa** [comment]
superceded by #1121
