### ISSUE TITLE
QUDA tests get stuck for a long time with CUDA-aware OpenMPI

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#613]
Following [Multi-GPU QUDA Wiki](https://github.com/lattice/quda/wiki/Multi-GPU-Support), we have been experimenting with CUDA-aware MPI versions (OpenMPI 2.0.2). While performance seems good or better than without support compiled in, the resulting applications show slightly odd behaviour:

1) When launched on a given CPU (as seen via top) a process might move to another CPU dynamically. I guess this is an important optimisation, but it seems to wreak havoc when it comes to terminating said process, as doing ```ctrl-c``` keeps the process running sometimes. The latter is true, for instance, when the MPI runtime is told to bind to a particular core through ```--cpu-set``` or similar arguments.

2) Before the actual computation starts, there is a long waiting period where the application will just sit there and apparently not do much (CPU usage is high, but the GPU is idle). For instance, for ```dslash_test```, it will just sit there at this point:

```
QUDA_RESOURCE_PATH=$HOME/quda_tune_bind0_p2p1_cuda_aware /opt/openmpi/bin/mpirun -np 1 ./dslash_test --Lsdim 1
running the following test:
prec    recon   test_type     matpc_type   dagger   S_dim         T_dimension   Ls_dimension dslash_type    niter
single   18       0              even-even    0     24/ 24/ 24         24              1           wilson   100
Grid partition info:     X  Y  Z  T
                         0  0  0  0
Randomizing fields... done.
QUDA 0.9.0 (git v0.8.0-1638-gaf0db9b-sm_35)
Found device 0: Tesla P100-PCIE-16GB
Found device 1: Tesla P100-PCIE-16GB
Found device 2: Tesla P100-PCIE-16GB
Found device 3: Tesla P100-PCIE-16GB
Found device 4: Tesla P100-PCIE-16GB
Found device 5: Tesla P100-PCIE-16GB
Found device 6: Tesla P100-PCIE-16GB
Found device 7: Tesla P100-PCIE-16GB
Using device 0: Tesla P100-PCIE-16GB
```

Is this expected behaviour? I'm not 100% certain that I'm interpreting the things in (1) correctly, but (2) definitely seems to be what happens.

**Comment by mathiaswagner** [comment]
What happened to all of us here is that we compiled for the wrong GPU arch and this is the point where JIT compilation takes place. Did you check that you compiled for sm_60 ?

**Comment by mathiaswagner** [comment]
Just realizing in your output `git v0.8.0-1638-gaf0db9b-sm_35` is compiled for Kepler.

**Comment by kostrzewa** [comment]
Oh dear, indeed, sorry about that! I'll recompile and test again and will close as soon as I see it working.

**Comment by kostrzewa** [comment]
Of course, this was the problem. Sorry for wasting your itme @mathiaswagner

**Comment by mathiaswagner** [comment]
Happy to help.

Actually the reason the `-sm_35` is in place was because of myself repeatedly failing at setting the right architecture for a fresh build. Do the results look good now?

**Comment by kostrzewa** [comment]
Absolutely, things are working great. Still testing P2P over Infiniband.
