### ISSUE TITLE
tuning problem on SummitDev

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#622]
I am finally getting back to SummitDev and able to launch multiple GPU job using the develop branch of QUDA.  However, I am running into a problem.  Here is how a typical job ends:

CONGRAD5: time = 2.279687e-02 (multicg_offset_QUDA D) masses = 7 iters = 35 mflops = 8.238043e+03
 OK converged final_rsq= 6.6e-27 (cf 2.5e-17) rel = 1.2e-24 (cf 0) restarts = 0 iters= 35
ERROR: Failed to clear error state an illegal memory access was encountered
 (rank 0, host summitdev-r0c0n14, /ccs/home/gottlieb/quda/lib/tune.cpp:615 in tuneLaunch())
       last kernel called was (name=N4quda17PackFaceStaggeredI7double2dEE,volume=4x8x8x8,aux=vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

The job launch commands look like this:
   mpirun -MXM -n $nodes --hostfile $LSB_DJOB_HOSTFILE --bind-to core --map-by ppr:2:socket ./$EXE <params${nodes}.$ns  >out_np$nodes.$ns.pretune
   mpirun -MXM -n $nodes --hostfile $LSB_DJOB_HOSTFILE --bind-to core --map-by ppr:2:socket ./$EXE <params${nodes}.$ns  >out_np$nodes.$ns

There is a tune file and a non-empty file tunecache.tsv.  I searched for the name of the last kernel called in the tunecache.csv file and this is what I find:

grep N4quda17PackFaceStaggered tunecache.tsv
   10x20x20x20x1        N4quda17PackFaceStaggeredI7double2dEE   vol=80000,stride=80000,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  480     1       1       100     1       1       1638511       1       1       5.5264e-05      # 0.00 Gflop/s, 83.38 GB/s, tuned Sun Jun 11 16:16:31 2017
   10x20x20x20x1        N4quda17PackFaceStaggeredI7double2dEE   vol=80000,stride=80000,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      448     1       1       54      1       1       16385   1    11       1       8.56533e-06     # 0.00 Gflop/s, 268.99 GB/s, tuned Sun Jun 11 16:16:31 2017
   12x24x24x24x1        N4quda17PackFaceStaggeredI7double2dEE   vol=165888,stride=165888,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        864     1       1       96      1       1    01       1       1       1       9.26293e-05     # 0.00 Gflop/s, 85.96 GB/s, tuned Sun Jun 11 16:17:42 2017
   12x24x24x24x1        N4quda17PackFaceStaggeredI7double2dEE   vol=165888,stride=165888,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    256     1       1       162     1       1       9831    1    11       1       9.30133e-06     # 0.00 Gflop/s, 428.04 GB/s, tuned Sun Jun 11 16:17:42 2017
   14x28x28x28x1        N4quda17PackFaceStaggeredI7double2dEE   vol=307328,stride=307328,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        608     1       1       217     1       1    24577    1       1       1       1       0.000144736     # 0.00 Gflop/s, 87.36 GB/s, tuned Sun Jun 11 16:19:50 2017
   14x28x28x28x1        N4quda17PackFaceStaggeredI7double2dEE   vol=307328,stride=307328,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    480     1       1       138     1       1       12289   1    11       1       1.56373e-05     # 0.00 Gflop/s, 404.30 GB/s, tuned Sun Jun 11 16:19:50 2017
   16x32x32x32x1        N4quda17PackFaceStaggeredI7double2dEE   vol=524288,stride=524288,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=        640     1       1       308     1       1    01       1       1       1       0.00021376      # 0.00 Gflop/s, 88.30 GB/s, tuned Sun Jun 11 16:23:35 2017
   16x32x32x32x1        N4quda17PackFaceStaggeredI7double2dEE   vol=524288,stride=524288,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=    352     1       1       280     1       1       9831    1    11       1       2.29653e-05     # 0.00 Gflop/s, 410.93 GB/s, tuned Sun Jun 11 16:23:34 2017
       4x8x8x8x1        N4quda17PackFaceStaggeredI7double2dEE   vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=    64      1       1       48      1       1       1228911       1       1       9.54667e-06     # 0.00 Gflop/s, 30.89 GB/s, tuned Sun Jun 11 16:15:13 2017
       4x8x8x8x1        N4quda17PackFaceStaggeredI7double2dEE   vol=2048,stride=2048,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=        32      1       1       48      1       1       8193    1    11       1       8.672e-06       # 0.00 Gflop/s, 17.00 GB/s, tuned Sun Jun 11 16:15:12 2017
    6x12x12x12x1        N4quda17PackFaceStaggeredI7double2dEE   vol=10368,stride=10368,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  96      1       1       108     1       1       1638511       1       1       1.6608e-05      # 0.00 Gflop/s, 59.93 GB/s, tuned Sun Jun 11 16:15:29 2017
    6x12x12x12x1        N4quda17PackFaceStaggeredI7double2dEE   vol=10368,stride=10368,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      192     1       1       27      1       1       6145    1    11       1       9.696e-06       # 0.00 Gflop/s, 51.33 GB/s, tuned Sun Jun 11 16:15:29 2017
    8x16x16x16x1        N4quda17PackFaceStaggeredI7double2dEE   vol=32768,stride=32768,precision=8,Ns=1,Nc=3,comm=0011,kernelPackT,nFace=3,location=  288     1       1       86      1       1       8193 11       1       1       3.1072e-05      # 0.00 Gflop/s, 75.93 GB/s, tuned Sun Jun 11 16:15:51 2017
    8x16x16x16x1        N4quda17PackFaceStaggeredI7double2dEE   vol=32768,stride=32768,precision=8,Ns=1,Nc=3,comm=0011,nFace=3,location=      256     1       1       48      1       1       16385   1    11       1       8.29867e-06     # 0.00 Gflop/s, 142.15 GB/s, tuned Sun Jun 11 16:15:50 2017

Would be happy to send any more desired information to diagnose this issue.

**Comment by mathiaswagner** [comment]
The error might not be triggered from the last kernel called. It might be useful to try running the job within cuda-memcheck to point down where the illegal access occurs. Launching the job like

`mpirun -MXM -n $nodes --hostfile $LSB_DJOB_HOSTFILE --bind-to core --map-by ppr:2:socket cuda-memcheck ./$EXE <params${nodes}.$ns >out_np$nodes.$ns.pretune`

I noticed that you have two mpiruns. If you can pin down the issue to the first or the second call it's sufficient to add cuda-memcheck to that. The runtime will be significantly slower when running with cuda-memcheck.

How many GPUs are required to run the job? If this is sufficiently small I'd be happy to try to set that up locally (but would need the required input files).
