### ISSUE TITLE
Use a proper parser for command line options of tests

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#637]
I admittedly love python's argparse for that but as we don't have something like that in C++ directly a quick google search turned up with:

https://github.com/Taywee/args

Seems to be close to argparse and is header only and under MIT license.

Thoughts?

**Comment by mathiaswagner** [comment]
alternative here might be gflags: https://github.com/gflags/gflags

**Comment by j-stephan** [comment]
https://github.com/philsquared/Clara/

https://github.com/muellan/clipp

I've read about both a few days ago, never used them. Both require C++11.

Then there's the nuclear option:

http://www.boost.org/doc/libs/1_65_1/doc/html/program_options.html

Used that in the past, worked pretty will but has a messy syntax. Should be compatible with C++03 though.

**Comment by mathiaswagner** [comment]
fixed about a year ago
