### ISSUE TITLE
Enable selective GDR support for asymmetric node topologies 

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#643]
I've been thinking about how to enable GDR on the FNAL K40 system, which is asymmetric with respect to NIC and GPU placement.  E.g.,
```
CPU 0 - - - - - - QPI - - - - - - CPU 1
* GPU 0                         * GPU 2
* GPU 1                         * GPU 3
* NIC
```
How about I expose yet another env arg

```bash
export QUDA_ENABLE_GDR=1
export QUDA_ENABLE_GDR_RANK="0,1"
```

This would only enable GDR for the processes listed in the `QUDA_ENABLE_GDR_RANK` env arg.  The default, if `QUDA_ENABLE_GDR_RANK` is not enabled, would be to enable GDR for all ranks (if `QUDA_ENABLE_GDR` is set).

Internally in QUDA, when it autotunes the policy, when a process that has GDR disabled, it would just run the corresponding non-GDR dslash policy; I don't see any reason why we couldn't have this asymmetric policy like this enabled since all each process would see would be a MPI send/recv.

Thoughts from anyone on this?  Hopefully, node topologies like this will be a thing of the past, but it would be good to maximize performance on existing systems.

**Comment by mathiaswagner** [comment]
While there is hope I am afraid that with more and more fat nodes the topology will become a bigger pain. It is probably good to have something like this but I am wondering whether there is a way to let the autotuner figure out whether GDR is available for that GPU.

**Comment by maddyscientist** [comment]
My first thought indeed was to enable this with the autotuner as you suggest.  The problem is that the node topology isn't available in general to CUDA unless we introduce an external dependency to QUDA, e.g., Hwloc.  Enabling this with an envarg enables this much easier to implement, and at least test the potential improvement from this.

**Comment by mathiaswagner** [comment]
I agree. Maybe implement this and add a follow-up issue which we 
a) might fix if some better solution shows up
b) have open forever
c) decide that we don't need to worry anymore.

**Comment by drossetti** [comment]
MPI should be able to do this kind of decisions.
Are there issues/bugs opened with major MPI implementations, e.g. Open MPI, MVAPICH2, Spectrum MPI, regarding improving the intra-node performance so that you can drop your special handling in QUDA?

**Comment by maddyscientist** [comment]
@drossetti my experience has been that it wants to use the same strategy for all processes, and not have special per process handling for each process.  The tuning handles in MVAPICH and OpenMPI do not for example, allow me to have some processes doing GDR for some and others not doing GDR.

Moreover, even if MPI could do a good job of identifying which processes should use GDR and which should route through CPU memory, MPI handling the routing through host memory is much slower than QUDA handling it manually due to the additional CUDA API calls inside MPI (it's for this reason that GPU pointers should only ever be passed to MPI if they are going to GDR else it's better to let QUDA handle it).

It would be great if MPI could handle it all, but my experience has been extremely disappointing in the regime we care about, e.g., 100 KiB - 1 MiB range.
