### ISSUE TITLE
CMake 3.9.2 configuration fails

### ISSUE THREAD

**Issue by bjoo** [lattice/quda#645]
Hi, 
 I was trying to build the recent QUDA (feature/multigrid branch, commit c1f0f29975731161a1ae6431d6ef77753de70182 ) and using CMake 3.9.2 on 
SummitDev (recent upgrade from 3.6.1). The CMake command failed with:

```
-- Found MPI_C: /ccs/home/bjoo/openmpi_gcc5.4.0/lib/libmpi.so  
-- Found MPI_CXX: /ccs/home/bjoo/openmpi_gcc5.4.0/lib/libmpi.so  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "quda" in directory /lustre/atlas/scratch/bjoo/csc244/package-9-8-17-gpu/src/quda/lib

-- Configuring incomplete, errors occurred!
```

This was a surprise, because this build has built for me before. In the end I reverted to the older 
CMake 3.6.1 and the problem went away. For now I can build with CMake 3.6.1, but we should figure this out at some point.

**Comment by mathiaswagner** [comment]
Thanks for the report. Starting from cmake 3.8 we use cmake's native support for CUDA (instead of relying solely on FindCUDA) which seems to have issues locating the libraries on summitdev.

**Comment by bjoo** [comment]
Hi Mathias, 
 Yes, this could actually be an issue with CMake… How to progress this? 
Unfortunately right now I have not too much time to dig deep Since I can
move forward with 3.6.1 I am more or less happy. If SummitDev tests work out
I will likely try to build on our local K80 node. I can try to install CMake 3.9.2 there, 
to see if the problem is SummitDev specific, or whether it seems related to CMake.

Best, 
B
> On Oct 3, 2017, at 9:27 AM, Mathias Wagner <notifications@github.com> wrote:
> 
> Thanks for the report. Starting from cmake 3.8 we use cmake's native support for CUDA (instead of relying solely on FindCUDA) which seems to have issues locating the libraries on summitdev.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by mathiaswagner** [comment]
I'll have a look at some point later this week as I don't have time to dig into it right now at all.

**Comment by alexstrel** [comment]
I guess for now one needs to set -DCUDA_cublas_LIBRARY explicitly.

**Comment by mathiaswagner** [comment]
I had a look a what we do. We use a specific FIndCudaWrapper and FindCudaLibs in the cmake directory. 
I could reproduce the issue locally on my machine and see what we can do to fix it.

**Comment by mathiaswagner** [comment]
@bjoo Can you please give the branch `hotfix/cmake_native_cudalibs` a try?

**Comment by mathiaswagner** [comment]
This still seems to pop up when using -DCUDA_TOOLKIT_ROOT_DIR ...

**Comment by mathiaswagner** [comment]
It's probably best to not use `DCUDA_TOOLKIT_ROOT_DIR=` anymore.
