### ISSUE TITLE
GCC 6.3 compatibility

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#647]
Just a question on gcc 6.3 compatibility. We would like to upgrade the OS on our GPU cliuster and need to make sure that our toolset will continue working. The new default compiler would be gcc 6.3 and we would like to avoid having to install another gcc toolchain if possible. Info would be very much appreciated!

**Comment by maddyscientist** [comment]
CUDA 9.0 introduces GCC 6.x compatibility, so that solves that problem.  Having said that, CUDA 9.0 requires a few changes to QUDA, these changes are covered by #642 (which should be merged into develop soon).

FWIW, all my local development is done using CUDA 9 and GCC 6.3.

**Comment by kostrzewa** [comment]
@maddyscientist Thanks a lot for the quick info! One more question: we have Tesla K20m's mixed with P100's. I tried to find info on CUDA 9 support for K20s but unfortunately came up short, could you enlighten us?

**Comment by mathiaswagner** [comment]
Cuda 9 supports Kepler so K20 is fine. 

Support for Fermi (SM2.x) was dropped.

**Comment by mathiaswagner** [comment]
@kostrzewa We have merged #642. I guess we can close this issue?

**Comment by kostrzewa** [comment]
Indeed, thanks a lot for the info! Closing.
