### ISSUE TITLE
Proposal to make the build more modular

### ISSUE THREAD

**Issue by jpfoley** [lattice/quda#65]
Due to the number of actions and tasks that QUDA now supports, the time required to compile the code from scratch has become pretty significant. Oftentimes, particularly when debugging, we only want to use a small number of routines, but find that we need to call a routine in interface_quda.cpp , for example, and therefore need to compile all the associated dependencies. I propose to begin to change the code to make the build more modular. An easy starting point would be to start to split interface_quda.cpp up, so that we don't need to compile clover-specific functions when only the staggered inverter is required, or compile inverter code if we only wish to test the gauge force. Comments?

**Comment by mathiaswagner** [comment]
As I am looking in the Makefiles I wanted to bring up the discussion of generating dependencies again: Was there any reason why this has never been implemented?

**Comment by mikeaclark** [comment]
It's never been a top priority.  Happy to get this done though.

**Comment by mathiaswagner** [comment]
This should come with #323.

**Comment by mathiaswagner** [comment]
While we still might need to introduce some hierarchical structure in the code in a big cleanup I guess all dependencies are now done with #364 (#323)
