### ISSUE TITLE
Potential memory leaks in lib/interface_quda.cpp:loadGaugeCuda()

### ISSUE THREAD

**Issue by j-stephan** [lattice/quda#658]
* `cudaGaugeField *precise` is always allocated (line 652), but only deleted under certain circumstances (only instance of `delete` in line 676).
* `cudaGaugeField *sloppy` is sometimes allocated (line 696) but never deleted
* `cudaGaugeField *precondition` is sometimes allocated (line 712) but never deleted
* `cudaGaugeField *extended` is sometimes allocated (line 726) but never deleted

As this is part of the work in #626 I suggest we use `unique_ptr` for the cleanup.

**Comment by j-stephan** [comment]
Ah, I should've read more thoroughly. Everything is fine.

**Comment by maddyscientist** [comment]
At some point, the resident gauge fields in QUDA, that are defined in interface_quda.cpp will be cleaned up - the code as it currents stands is not exactly cleanly put together.  This aspect of QUDA is legacy code that hasn't really been touched in years.  Indeed, we intend to introduce more use of `unique_ptr` in QUDA as part of this.
