### ISSUE TITLE
Unify all CPU and CUDA fields

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#66]
With the advent of unified memory address spaces, there seems to be little point in keeping around separate cpu and cuda fields, since a cpu field can be mapped into the device memory address space.  I think it would be sensible to unify the cpu and cude fields into a single field, which can reside in either the host or device memory.

This isn't a simple modification, rather a long-term design objective.  It would vastly simplify he high-level design of the library, something which I think will become increasingly important with multigrid.

**Comment by maddyscientist** [comment]
One concept that has been introduced in QUDA, is to allocate a CUDA field with a different memory type
```c++
  typedef enum QudaMemoryType_s {
    QUDA_MEMORY_DEVICE,
    QUDA_MEMORY_PINNED,
    QUDA_MEMORY_MAPPED,
    QUDA_MEMORY_INVALID = QUDA_INVALID_ENUM
  } QudaMemoryType;
```

This could be extended to include a `QUDA_MEMORY_HOST` for a regular CPU fields.  For SHMEM, I don't we need to worry: there we would be using a custom allocator for the halo region, not for the entire field.  For CUDA IPC, we already introduced `device_pinned_malloc` for this purpose.

**Comment by j-stephan** [comment]
You're right. The halo exchange can be done with a special policy (dslash_policy.cu). I'm currently working on this, so far this does not (and should not) require any changes to the fields or the kernels.

**Comment by weinbe2** [comment]
Closed by https://github.com/lattice/quda/pull/1384 , https://github.com/lattice/quda/pull/1217 , and https://github.com/lattice/quda/pull/1213 .
