### ISSUE TITLE
Native cmake build does not propagate CXX flags to NVCC

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#687]
This is only a problem with recent cmake versions: this continues to work fine with older versions of cmake.  The main result of this is that warnings are suppressed compared to compiling with older versions of cmake, leading to unexpected failures in Jenkins.

**Comment by mathiaswagner** [comment]
looking into this I think it is now up to us to propagate flags if we want to. So we need to give this some thought whether we want to use a big hammer here.
which flags would you want to propagate? Any example?

**Comment by mathiaswagner** [comment]
@maddyscientist ping

**Comment by maddyscientist** [comment]
The flags that are most needed are the warnings.  Since the warning flags are not passed to NVCC, the *.cu files are compiled without issuing warnings that would be indicated when compiling *.cpp files.

**Comment by mathiaswagner** [comment]
So passing the CXX flags to -Xcompiler by default should be fine. 
We can set this as the default. Do we want to expose this in the cache so that the user can change it or do we just always pass them (that is what FindCUDA does for cmake < 3.8 unless you disable the propagation completely).

**Comment by maddyscientist** [comment]
Happy to always pass them, but if it's quick enough for you to expose this as an option which can be disabled that sounds fine.

**Comment by mathiaswagner** [comment]
The other option would be to pre-populate the Cuda flags with -Xcompiler $CXX_FLAGS but then in ccmake the Cuda and cxx flags would be independent. I.e. any change to CxX_FLAGS would not propagate to the XCompiler option. 

That gives the user the most control but not sure that is ever needed as this is also the case if we propagate the flags (and can turn it off).

**Comment by mathiaswagner** [comment]
Should be addressed in #689
