### ISSUE TITLE
cudaEventSynchronize in future::wait: an illegal memory access was encountered

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#693]
Trying to run a three-level MG (64c128 lattice, twisted clover with dynamic clover inversion, GCR double-single, everything else half precision as recommended, GCRNKrylov=20, no multiblas (pipeline=0) )

On "any" number of cards below 128 (I tried 16, 32, and 64), I encounter the following error:

```
MG level 1 (GPU): Tuned block=(32,1,1), shared=0, aux=(0,0,0,0) giving 604.61 Gflop/s, 220.43 GB/s for N4quda23TwistedCloverDslashCudaI6short4S1_S1
_EE with policy,comm=0111,reconstruct=8,Xpay,dagger,topo=1248
MG level 1 (GPU): PostTune N4quda23TwistedCloverDslashCudaI6short4S1_S1_EE
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  cudaEventSynchronize in future::wait: an illegal memory access was encountered
srun: error: nid03679: task 0: Aborted
srun: Terminating job step 7355455.0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: nid05031: task 42: Killed
srun: error: nid06267: task 61: Killed
srun: error: nid06265: task 59: Killed
srun: error: nid04508: task 18: Killed
```

Irrespective of whether gauge compression is enabled or not. Is 1 TB of device memory simply not enough for a 3-level MG on 64 P100 cards for this lattice size? Am I doing something stupid?

The multigrid parameters are set here: https://github.com/kostrzewa/tmLQCD/blob/566bb1726874e5c6ceb9f92ef73ac6e00c012540/quda_interface.c#L1080

@sbacchio : Have you ever seen this?

**Comment by maddyscientist** [comment]
@kostrzewa this should not be happening, and indeed things should fit on 64 GPUs.  Out of contact for the next week, but I will try on Piz Daint and an internal cluster when I return.

**Comment by maddyscientist** [comment]
Closing this old bug.  This issue was fixed with https://github.com/lattice/quda/commit/c86497cc8ff87fee6e8f4de10b3e54edca28e561.
