### ISSUE TITLE
QUDA MG setup re-use for opposite twisted mass flavour?

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#709]
Is there currently an easy way to re-use the MG setup generated with +mu for an inversion with -mu? Simply setting the outer solver parameters accordingly and re-using the setup naively does not seem to work...

This fails for both plain twisted and twisted clover.

What does work is to re-use the setup generated for a particular mu with a larger mu, as one would expect.

**Comment by kostrzewa** [comment]
@sbacchio ever tried this?

**Comment by maddyscientist** [comment]
@kostrzewa I think what will work is to run the setup as normal, then when it comes to flipping mu, use the `updateMultigridQuda()` interface that we use in HMC.  This is what we use to change the masses for the different mass contributions for the determinant.  The same should just work for changing mu (famous last words). 

@cpviolator I recall you looked at this, but I may have imagined it.

**Comment by kostrzewa** [comment]
@maddyscientist thanks, will this cost something?

**Comment by maddyscientist** [comment]
Yes, it will result in the re-computation of the coarse link field elements, but this is relatively cheap since this is well optimized.  Put it this way: in HMC, the cost of calling this and running the subsequent MG is still cheaper than using standard Krylov solver on very heavy quark mass.

**Comment by cpviolator** [comment]
One possibility (if you’re set on using a single MG object) is to just use
a plain Wilson(clover) construction. You will likely see a performance hit
for physical pion masses though.

**Comment by maddyscientist** [comment]
One other thing: since we typically use even-odd preconditioning throughout, this means that re-computing the coarse-link field is the correct thing to do.  E.g., the inverse of the clover matrix which absorbs the mass and twist (or the equivalent on coarser grids) means that we cannot directly relate the coarse-link field from different masses or twists.  However, reusing the null-space fields does seem to work well.

**Comment by kostrzewa** [comment]
@maddyscientist @cpviolator Thanks a lot for the info. It works fine and it's not too expensive, although for the case in question it's more of a matter of correctness of program flow, one would not organise the calculation like that in practice.

As for the setup working with masses of different magnitudes: this even worked without running the setup update and gave the correct residual.
