### ISSUE TITLE
QIO and QUDA disagree on process topology

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#712]
When QUDA uses "column" as the default Cartesian rank ordering (`--rank-order col`), QIO assumes the rank order is "row" ordered `--rank-order row`.  This means that I/O gives junk if we partition more than 1 dimension, unless we explicitly pass `--rank-order row` to QUDA.  We need to set QIO's rank order to match QUDA's.

**Comment by maddyscientist** [comment]
Moving to 0.9.1.  For now, in commit e522c8e6394fc51cbc67476df8114360bec662e5, I've added a check if column rank ordering is use, together with QIO, and QUDA will error with a sensible error message telling the user to rerun with `--rank-order row`.  This unblocks the 0.9.0 release.

**Comment by mathiaswagner** [comment]
Is there a PR ?

**Comment by weinbe2** [comment]
Addressed by merging #723.
