### ISSUE TITLE
BiCGStab solver not always converging with QOP/QDP

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#72]
Message from Michael Cheng.

> I've started inversions of the lighter pion mass clover ensemble at 
> JLab.  I'm finding that in many cases the CG has trouble converging to a 
> solution.  I am using a mixed single/half solver with defect correction 
> on the host for full double precision.  The residual I am using is 
> 1e-8.  The symptom of the problem is that the solver will get stuck 
> iterating for a very long time, 10000+ iterations with very little or no 
> change in the residual:
> 
> source color 0 spin 2 norm2 = 1
> iters = 1196  secs = 42.041791  mflops = 222167 rsq = 2.26134e-11
> QUDA warning: Exceeded maximum iterations 10000
> iters = 11196  secs = 407.986216  mflops = 218136 rsq = 2.26134e-11
> QUDA warning: Exceeded maximum iterations 10000
> iters = 21196  secs = 772.165411  mflops = 218172 rsq = 2.26133e-11
> QUDA warning: Exceeded maximum iterations 10000
> iters = 31196  secs = 1136.866908  mflops = 218132 rsq = 2.26133e-11
> 
> This occurs in maybe 15% of the inversions that I have been doing on 
> this ensemble.  Most of the time, it seems like the inversions 
> eventually converge after iterating for 10000+ trajectories.  However, 
> there are some cases, like above, where the 30 minute time limit on the 
> debug queue expires before convergence.  So far, testing with one source 
> per configuration, this has occured on 11 out of 17 configurations that 
> I have tested.  I anticipate that, if I go to 32 sources per 
> configuration, virtually all my configurations will be affected.  I 
> guess this is similar to the problem that Oliver ran into, although it 
> looks like it may be more severe when calculating double precision 
> propagators.
> 
> Any suggestions on things I can tune with regards to the inverter to see 
> if I can get this to work better?  I will try using the double/half 
> precision inverter on bungee (which has enough memory) to see if I see 
> the same problem.

This is a long standing bug that has plagued the disco project, and as a result drastically reduces the effectiveness of using GPUs for this project.  The strange thing is that it doesn't affect Chroma which uses the same configurations.  

Michael: could this be a mixed-precision issue that only affects the disco project because of the type of source spinors used?  IS it possible to investigate whether the issue goes away with different types of sources.

Everyone else: any ideas welcome.

**Comment by mathiaswagner** [comment]
Is this still something we want to get in 0.7.1 ?

I think the possibility to restart a solver is important. It is something that is in the CG for solves with a hard to satisfy fermilab residual. Although the situation might be different here. Anyhow, as I think also Alexei needs some restarts it might be good to implement that consistently in all solvers. 
But I do believe this is more a 0.8 task.

**Comment by mikeaclark** [comment]
Agreed it for 0.8, I just ran out of time yesterday going through the bugs :)

**Comment by maddyscientist** [comment]
Moving to 0.9, though I'm not sure this is really an ongoing issue that we need concern ourselves with.

**Comment by maddyscientist** [comment]
Closing this issue.  Nothing to worry about anymore since we have improved stability in mixed precision solvers, improved half precision accuracy and modern GPUs have plenty of memory for double-half precision solvers
