### ISSUE TITLE
quda 0.9.0 nppi library 

### ISSUE THREAD

**Issue by mpdeka** [lattice/quda#733]
I am in the process of compiling quda 0.9.0 with cuda 9.2 and cmake 3.12 . I would like to mention one (minor) issue regarding the nppi library. Recently, (most likely from cuda 9.0 onward) nppi library is replaced with a few sub-libraries in order to improve load time and runtime startup. As a result, I had to needed to modify in FindCUDALibs.cmake under cmake/ sub-directory in the following way:

find_cuda_helper_libs(nppi)

is replaced by 

  find_cuda_helper_libs(nppial)
  find_cuda_helper_libs(nppicc)
  find_cuda_helper_libs(nppicom)
  find_cuda_helper_libs(nppidei)
  find_cuda_helper_libs(nppif)
  find_cuda_helper_libs(nppig)
  find_cuda_helper_libs(nppim)
  find_cuda_helper_libs(nppist)
  find_cuda_helper_libs(nppisu)
  find_cuda_helper_libs(nppitc)

Similarly, the following line 
set(CUDA_npp_LIBRARY "${CUDA_nppc_LIBRARY};${CUDA_nppi_LIBRARY};${CUDA_npps_LIBRARY}")

is replaced with

set(CUDA_npp_LIBRARY "${CUDA_nppc_LIBRARY};${CUDA_nppial_LIBRARY};${CUDA_nppicc_LIBRARY};${CUDA_nppicom_LIBRARY};${CUDA_nppidei_LIBRARY};${CUDA_nppif_LIBRARY};${CUDA_nppig_LIBRARY};${CUDA_nppim_LIBRARY};${CUDA_nppist_LIBRARY};${CUDA_nppisu_LIBRARY};${CUDA_nppitc_LIBRARY};${CUDA_npps_LIBRARY}")

This seems to working fine. However, I am not sure whether quda 0.9.0 needs all the npp sub-libraries. Could you please check whether the number of calling libraries can be reduced. Thanks.

**Comment by mathiaswagner** [comment]
Thanks for reporting. 
We don't use nppi so we should be able to just remove that part from FindCUDALibs.cmake. This script is there historically for compatibility reasons when we switched from FindCUDA to native support in cmake.

I'll have a look at what we can do for cleanup here.

**Comment by mpdeka** [comment]
Thank you Mathias.

**Comment by mathiaswagner** [comment]
Hi @mpdeka 
Could you please check whether 
https://github.com/lattice/quda/tree/hotfix/cmake_npp_libs
resolves your issues?

**Comment by mathiaswagner** [comment]
@mpdeka Did you have a chance to look at that?

**Comment by mathiaswagner** [comment]
Closing this. Reopen if still a thing.
