### ISSUE TITLE
non-degenerate twisted clover operator has disappeared?

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#738]
When I try to create a two-flavour twisted clover (non-degnerate) operator, it seems that this is no longer supported. I thought this was implemented during the Juelich hackathon?

**Comment by kostrzewa** [comment]
I see, it seems this was never merged... https://github.com/lattice/quda/tree/feature/nondeg-tmclover

**Comment by maddyscientist** [comment]
Hi @kostrzewa.  Yes, it was never merged.  I don't think that @AlexVaq got it quite finished.

As I think I told you, I've been planning on ripping out the Dslash code for all stencils and rewriting it from scratch in the high-level C++ framework that QUDA has now.  I'm pleased to say I have *finally*  started on this, and I now have a Wilson dslash plain in the new framework (https://github.com/lattice/quda/commit/a272bffe484aa6ffbc58903fefb87f98e675ec6e).  I'm hoping to get the rewrite complete by the end of the month.  In the new framework, adding support for the non-degenerate twisted-clover operator should be trivial.

**Comment by mathiaswagner** [comment]
is being worked on in #1121

**Comment by weinbe2** [comment]
Closed by https://github.com/lattice/quda/pull/1198
