### ISSUE TITLE
Release versions of QUDA contain hard-coded hash values for Eigen that can change

### ISSUE THREAD

**Issue by weinbe2** [lattice/quda#740]
The `CMakeLists.txt` file in the main directory of QUDA has a hard-coded hash value for Eigen that gets checked when its source tarball gets downloaded. Because Eigen is out of our control, this hash can change (even for fixed versions of Eigen) if for, whatever reason, the developers upload a new tarball. While it's easy enough to work around, we should have a better solution for release versions going forward.

Workaround:

- Run `cmake` (which triggers the issue)
- Manually go to the QUDA source directory, `cd /external/`, and untar `Eigen`. Take note of the path to Eigen's root source directory.
- Configure your QUDA build as normal via `ccmake`, with the following two additional configuration changes (which are "advanced", so press `t` in the `ccmake` menu to expose them): 

1. Set `QUDA_DOWNLOAD_EIGEN` to `NO`
2. Set `EIGEN_INCLUDE_DIRS` to the path to Eigen's root source directory.

Build as normal (assuming there isn't an issue with another part of the setup!)

**Comment by mathiaswagner** [comment]
Will be fixed through #1125

**Comment by agsunderland** [comment]
I'm getting problems with the Eigen hash value with Quda 1.0.0. I've tried this workaround but still get problems:CMake Error at CMakeLists.txt:267 (message):
  QUDA requires Eigen (http://eigen.tuxfamily.org).  Please either set
  EIGEN_INCLUDE_DIRS to path to eigen3 include directory, e.g.
  /usr/local/include/eigen3 or set QUDA_DOWNLOAD_EIGEN to ON to enable
  automatic download of the necessary components.externals/eigen/eigen-3.3.7
This is with setting EIGEN_INCLUDE_DIRS to the path to what I consider Eigen's root source directory (i.e. /externals/eigen-eigen-3.3.7).

**Comment by mathiaswagner** [comment]
The following worked for me:
Download https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.bz2 and unpack (I just downloaded and unpacked to my home directory, you might need to change the paths below according to your location)

```
cmake -DQUDA_DOWNLOAD_EIGEN=OFF -DEIGEN_INCLUDE_DIR=${HOME}/eigen-3.3.9/ ~/quda/release/1.0.x/
```

If that does not help can you share the full error message here?

**Comment by agsunderland** [comment]
Thanks. This worked.

**Comment by weinbe2** [comment]
FYI I copied these instructions here for future reference: https://github.com/lattice/quda/wiki/QUDA-Build-With-CMake#specifying-a-separate-eigen-installation-if-absolutely-necessary

**Comment by agsunderland** [comment]
Thanks Evan,

I've run into another problem with the Quda installation. Could you please advise the best place I should raise this query?

Regards,
Andy

________________________________

**Comment by maddyscientist** [comment]
@agsunderland just make a new issue
