### ISSUE TITLE
Optionally add a twisted mass to the even-odd-preconditioned Wilson-Clover Dirac operator

### ISSUE THREAD

**Issue by bjoo** [lattice/quda#745]
It may be handy for implementing Hasenbusch terms in their original way, to add a twisted mass term onto the even-odd preconditioned Wilson-Clover Dirac operator ie.  to go from: 

       1 - A^{-1}_oo D_oe A^{-1}_ee D_eo   to  1 + i gamma_5 mu - A^{-1}_oo D_oe A^{-1}_ee D_eo

and as appropriate for the Hermitian conjugate. This was already envisaged in Chroma (tho the recent symmetric preconditioning does not yet implement it). I could implement it in Chroma and be able to check against QUDA.

**Comment by maddyscientist** [comment]
Implemented by #850
