### ISSUE TITLE
warning and error compiline MILC update_u.c

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#754]
I am working on Ascent at ORNL.  Just cloned quda and MILC.   I am working in develop branch of QUDA and master of MILC.  My compilation fails with following warning and error. 

update_u.c:47:31: warning: passing argument 3 of 'qudaUpdateU' from incompatible pointer type [-Wincompatible-pointer-types]
   qudaUpdateU(PRECISION, eps, momentum, gauge);
                               ^~~~~~~~
In file included from ../include/generic_quda.h:7:0,
                 from update_u.c:18:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:649:8: note: expected 'QudaMILCSiteArg_t * {aka struct <anonymous> *}' but argument is of type 'Real * {aka double *}'
   void qudaUpdateU(int precision,
        ^~~~~~~~~~~
update_u.c:47:3: error: too many arguments to function 'qudaUpdateU'
   qudaUpdateU(PRECISION, eps, momentum, gauge);
   ^~~~~~~~~~~
In file included from ../include/generic_quda.h:7:0,
                 from update_u.c:18:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:649:8: note: declared here
   void qudaUpdateU(int precision,
        ^~~~~~~~~~~

I then switched to the develop branch of MILC.  In that case, the compilation also fails, but this these complaints:

mpicc -c -O3 -std=c99 -DMPI -DCGTIME -DFFTIME -DFLTIME -DGFTIME -DREMAP -DPRTIME -DIOTIME  -DCG_OK -DREMAP_STDIO_APPEND    -DDBLSTORE_FN -DFEWSUMS -DD_FN_GATHER13   -DKS_MULTICG=HYBRID  -DKS_MULTIFF=FNMAT   -DCL_CG=BICG      -DC_GLOBAL_INLINE  -DPRECISION=2    -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE       -I.  -DHAVE_QUDA -DUSE_CG_GPU -DUSE_GF_GPU -DUSE_FL_GPU -DUSE_FF_GPU -DSET_QUDA_SUMMARIZE  -DFN -DINT_ALG=INT_3G1F -DHISQ_REUNIT_ALLOW_SVD -DHISQ_REUNIT_SVD_REL_ERROR=1e-8 -DHISQ_REUNIT_SVD_ABS_ERROR=1e-8 -DHISQ_FF_MULTI_WRAPPER -DHISQ_FORCE_FILTER=5.0e-5    -I/ccsopen/home/gottlieb/build.1/include -I/lib -I/ccsopen/home/gottlieb/build.1/tests -ILCF_CUDA_ROOT/include   ../generic_ks/fermion_force_hisq_multi.c
../generic_ks/fermion_force_hisq_multi.c: In function 'fn_fermion_force_multi_hisq_wrapper_mx_gpu':
../generic_ks/fermion_force_hisq_multi.c:2267:76: error: incompatible type for argument 4 of 'qudaHisqForce'
 isqForce(MILC_PRECISION, n_order_naik_total, n_orders_naik_current, coeff, (void**)multi_x,
                                                                     ^~~~~
In file included from ../generic_ks/fermion_force_hisq_multi.c:2005:0:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:611:8: note: expected 'double' but argument is of type 'double **'
   void qudaHisqForce(int precision,
        ^~~~~~~~~~~~~
../generic_ks/fermion_force_hisq_multi.c:2267:83: warning: passing argument 5 of 'qudaHisqForce' from incompatible pointer type [-Wincompatible-pointer-types]
 e(MILC_PRECISION, n_order_naik_total, n_orders_naik_current, coeff, (void**)multi_x,
                                                                     ^
In file included from ../generic_ks/fermion_force_hisq_multi.c:2005:0:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:611:8: note: expected 'double **' but argument is of type 'void **'
   void qudaHisqForce(int precision,
        ^~~~~~~~~~~~~
../generic_ks/fermion_force_hisq_multi.c:2268:17: warning: passing argument 6 of 'qudaHisqForce' from incompatible pointer type [-Wincompatible-pointer-types]
                 level2_coeff, fat7_coeff, W_unitlink, V_link, U_link, momentum);
                 ^~~~~~~~~~~~
In file included from ../generic_ks/fermion_force_hisq_multi.c:2005:0:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:611:8: note: expected 'void **' but argument is of type 'double *'
   void qudaHisqForce(int precision,
        ^~~~~~~~~~~~~
../generic_ks/fermion_force_hisq_multi.c:2268:43: warning: passing argument 8 of 'qudaHisqForce' from incompatible pointer type [-Wincompatible-pointer-types]
                 level2_coeff, fat7_coeff, W_unitlink, V_link, U_link, momentum);
                                           ^~~~~~~~~~
In file included from ../generic_ks/fermion_force_hisq_multi.c:2005:0:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:611:8: note: expected 'const double *' but argument is of type 'fsu3_matrix * {aka struct <anonymous> *}'
   void qudaHisqForce(int precision,
        ^~~~~~~~~~~~~
../generic_ks/fermion_force_hisq_multi.c:2267:3: error: too few arguments to function 'qudaHisqForce'
   qudaHisqForce(MILC_PRECISION, n_order_naik_total, n_orders_naik_current, coeff, (void**)multi_x,
   ^~~~~~~~~~~~~
In file included from ../generic_ks/fermion_force_hisq_multi.c:2005:0:
/ccsopen/home/gottlieb/build.1/include/quda_milc_interface.h:611:8: note: declared here
   void qudaHisqForce(int precision,
        ^~~~~~~~~~~~~
make[1]: *** [fermion_force_hisq_multi.o] Error 1
make[1]: Leaving directory `/autofs/nccsopen-svm1_home/gottlieb/milc_qcd/ks_imp_rhmc'
make: *** [su3_rhmd_hisq] Error 2

If anyone knows a quick fix, it would be appreciated.

**Comment by maddyscientist** [comment]
Hi @stevengottlieb.  The issue here is that you are working on the master branch of MILC, and not the develop branch.  As far as I'm aware, the master branch of MILC hasn't been updated in more than a year, so it lags behind the changes made to the develop branch of MILC.  Switching to the develop branch of MILC will fix your issue.

(Actually, there is an open pull against MILC that needs to be closed to compensate for the latest changes to QUDA: https://github.com/milc-qcd/milc_qcd/pull/22.  Hopefully @detar will close this soon since it is a trivial change to the interface (but necessary to enable force monitoring in MILC HMC when running with QUDA: https://github.com/lattice/quda/pull/753).

**Comment by stevengottlieb** [comment]
Hi @maddysientist.  I will compile without the fermion force until
@detar closes the issue.

Steve

**Comment by maddyscientist** [comment]
Closing this issue since it's long since been resolved.
