### ISSUE TITLE
inv_type undefined

### ISSUE THREAD

**Issue by detar** [lattice/quda#774]
I am trying to start the QUDA clover inverter on Summit via the MILC interface.  It has been a while since I used it, so some conventions may have changed.  I am using a QUDA branch that was very recently forked from develop: 4ed1c90defd551574a7b7f0426532cc86b86e006. 

It fails at the outset.  checkInvertParam quits with "inv_type is undefined".  Just to be sure, I added "inv_args.solver_type = QUDA_BICGSTAB_INVERTER" to the MILC call to qudaCloverInvert.  This change should have ensured that invertParam.inv_type was then set to  QUDA_BICGSTAB_INVERTER in milc_interface.cpp:1639, but I got the same error.  Have you seen this before?

**Comment by cpviolator** [comment]
Is it just failing with `QUDA_BICGSTAB_INVERTER` or any explicit inverter type?

**Comment by maddyscientist** [comment]
This was a bug I introduced with over zealous parameter checking in the `loadCloverQuda` function.  I fixed it about about a month ago with a more targeted parameter checking which fixes this.  Closing this issue.
