### ISSUE TITLE
Delete legacy dslash kernels

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#786]
Once all the other issues have been completed on milestone [20](https://github.com/lattice/quda/milestone/20), we can delete all the legacy dslash kernels, macros and python code generators.

**Comment by ybyang** [comment]
It is a great news that we are very close to the new dslash kernel without macros. I would like to check whether the QUDA smearing works now in chroma. What are the recommended working branch (I guess it is feature/dwf-rewrite?) and the cmake command? Do we need to specify something for jitify?

Best,

Yi-Bo

**Comment by weinbe2** [comment]
Does this include removing `dslash_pack.cu`, too?

**Comment by maddyscientist** [comment]
@weinbe2 files that will be deleted:
* lib/dslash_core/*
* lib/dslash_pack.cu
* lib/dslash_textures.h
* lib/*dslash*def.h
* lib/io_spinor.h
* lib/read_gauge.h
* lib/read_clover.h
And also we will rename all the dslash4_*.cu file to dslash_*.cu, replacing all the current dslash_*.cu files.

As well as removal of all mention of these respective functions from the headers.

**Comment by maddyscientist** [comment]
Closed with #848
