### ISSUE TITLE
possible regression: tmclover multinode MG (OpenMPI)

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#798]
On the K20m partition of our local cluster, it seems that current head commit (as of today) of the ```develop``` branch leads to an incorrect residual and unreliable updates in GCR for twisted clover. This is running with ```QUDA_DYNAMIC_CLOVER=ON```.

The cluster runs OpenMPI 2.0.2a1 with GDR support, although the problem appears irrespective of whether this is in use. QUDA and tmLQCD have been compiled using GCC 5.4.0

1) single node works fine for CG and MG, both twisted and twisted clover work
2) multi-node CG works for twisted and twisted clover
3) multi-node MG works only for twisted but *not* for twisted clover

```
# 2 kappa mu = 0.000840387000, kappa = 0.140064500000, c_sw = 1.740000000000
# Using even/odd preconditioning!
# QUDA: Using single prec. as sloppy!
# QUDA: Using MG!
# QUDA: Using EO preconditioning!
# QUDA: Clover field and inverse already loaded for gauge 0
# QUDA: mu = 0.003000000000, kappa = 0.140064500000, csw = 1.740000000000
# QUDA: MG setting coarse mu scaling factor on level 0 to 1.000000
# QUDA: MG level 0, extent of (xyzt) dim 0: 32
# QUDA: MG aggregation size set to: 4
# QUDA: MG level 0, extent of (xyzt) dim 1: 32
# QUDA: MG aggregation size set to: 4
# QUDA: MG level 0, extent of (xyzt) dim 2: 16
# QUDA: MG aggregation size set to: 4
# QUDA: MG level 0, extent of (xyzt) dim 3: 16
# QUDA: MG aggregation size set to: 4
# QUDA: MG setting coarse mu scaling factor on level 1 to 1.000000
# QUDA: MG level 1, extent of (xyzt) dim 0: 8
# QUDA: MG aggregation size set to: 4
# QUDA: MG level 1, extent of (xyzt) dim 1: 8
# QUDA: MG aggregation size set to: 4
# QUDA: MG level 1, extent of (xyzt) dim 2: 4
# QUDA: MG aggregation size set to: 2
# QUDA: MG level 1, extent of (xyzt) dim 3: 4
# QUDA: MG aggregation size set to: 2
# QUDA: MG setting coarse mu scaling factor on level 2 to 20.000000
# QUDA: Reusing MG Preconditioner Setup for gauge 0
# QUDA: time spent in reorder_spinor_toQuda: 0.060250 secs
WARNING: GCR: new reliable residual norm 1.783603e+02 is greater than previous reliable residual norm 1.722932e+02 (total #inc 1)
WARNING: GCR: new reliable residual norm 1.961242e+02 is greater than previous reliable residual norm 1.783603e+02 (total #inc 2)
WARNING: GCR: solver exiting due to too many true residual norm increases
GCR: Convergence at 100 iterations, L2 relative residual: iterated = 3.107700e-02, true = 3.107700e-02 (requested = 3.162278e-10)
# QUDA: Done: 100 iter / 20.2215 secs = 839.673 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.050952 secs
# Inversion done in 100 iterations, squared residue = 2.889637e+04!
```

**Comment by maddyscientist** [comment]
Hi @kostrzewa.  Thanks for the report, but sorry to hear you're having this issue.  A few things:
* does it occur with non-dynamic clover?
* are you running with MG verify switched on (and I presume it passing the verification test if it's on?)
* can I get access to your cluster?  If I can reproduce this, I should be able to work out what the problem is much easier.
* can you reproduce the problem using just `multigrid_invert_test` ?
* does it occur with tuning and / or p2p disabled?

We've had another bug report from @ckallidonis at BNL on their Kepler cluster, where MG (with regular clover) is misbehaving for them.  I have been unable to reproduce that issue at all, though I've only got access to Pascal and Volta systems.  I'm wondering if there's some subtle Kepler specific bug lurking in there somewhere.  For that bug (and one with MILC that only appears on ~1024 GPUs) I've got a hotfix branch where I've been working (hotfix/milc-bnl) to helper work this out, though without direct access to a Kepler box I've not isolated that issue yet.

One of the features of this branch so far is that QUDA's solvers are now completely deterministic when driven through multigrid_invert_test / invert_test (hyper-cubic RNG is used in the internal tests now, not just the library internally**), and moreover if you set the env arg `QUDA_DETERMINISTIC_REDUCE=1` all the mpi reductions will be done deterministically regardless of the rank order or rank placement over nodes.  If you switch to this branch, and for example compare runs between using a constant number of processes, and 4 GPUs in a node and 1 GPU per node over 4 nodes, then the result will be identical.  Tuning can be enabled for this, but does require that you force the dslash policy choice for determinism e.g., `QUDA_ENABLE_DSLASH_POLICY=0` (or disable autotuning).  Anyway, the hope is that this should help isolate issues and work out exactly where something goes wrong.

**Note this requires either using a unit gauge or loading a gauge field from disk - I've yet to move the test code that creates a gauge field to the hyper-cubic RNG - will get this done in the next day or two.

Anyway, hopefully we can track this down....

**Comment by kostrzewa** [comment]
Hi @maddyscientist 

> Hi @kostrzewa. Thanks for the report, but sorry to hear you're having this issue. A few things:
> 
>     * does it occur with non-dynamic clover?

Yes, it fails there too.

>     * are you running with MG verify switched on (and I presume it passing the verification test if it's on?)

Should probably get into the habit of turning this on at least for the first few verification runs. It does *not* seem to pass MG verify:

```
MG level 1 (GPU): ERROR: failed, deviation = 4.492080e-01 (tol=5.000000e-02) (rank 0, host lnode06, /qbigwork2/bartek/code/bleeding_edge/quda_deve
lop/lib/multigrid.cpp:627 in verify())
MG level 1 (GPU):        last kernel called was (name=N4quda4blas5Norm2Id6float2S2_EE,volume=8x8x4x4,aux=vol=1024,stride=512,precision=4,Ns=2,Nc=2
4,TwistFlavour=1)
# My mpi_time_rank = 1, g_proc_coords = (0,0,0,1), g_cart_id = 1
# My mpi_z_rank = 0, g_proc_coords = (0,0,0,1), g_cart_id = 1
# My mpi_SV_rank = 0, g_proc_coords = (0,0,0,1), g_cart_id = 1
# My mpi_ST_rank = 1, g_proc_coords = (0,0,0,1), g_cart_id = 1
[...]
```

What I find a bit strange, however, is that unless I crank up the verbosity, the verification seems to pass. I would have expected verification to be done (and to error out) if ```run_verify``` is set to ```QUDA_BOOLEAN_YES``` irrespective of the various verbosity levels.

>     * can I get access to your cluster?  If I can reproduce this, I should be able to work out what the problem is much easier.

See email, our admin should get back to you, hopefully :)

>     * can you reproduce the problem using just `multigrid_invert_test` ?

I'm a bit swamped right now and would need to find some time to actually get this set up with QIO & co to run tests without tmLQCD.

>     * does it occur with tuning and / or p2p disabled?

It seems to be independent of P2P and the verification fails when tuning is disabled. On the other hand, when tuning is enabled, it seems that the verification passes (if it was actually run, it's a bit hard to tell to be honest) but the solver still does not converge.

> We've had another bug report from @ckallidonis at BNL on their Kepler cluster, where MG (with regular clover) is misbehaving for them. I have been unable to reproduce that issue at all, though I've only got access to Pascal and Volta systems. I'm wondering if there's some subtle Kepler specific bug lurking in there somewhere. For that bug (and one with MILC that only appears on ~1024 GPUs) I've got a hotfix branch where I've been working (hotfix/milc-bnl) to help work this out, though without direct access to a Kepler box I've not isolated that issue yet.
> 
> One of the features of this branch so far is that QUDA's solvers are now completely deterministic when driven through multigrid_invert_test / invert_test (hyper-cubic RNG is used in the internal tests now, not just the library internally**), and moreover if you set the env arg `QUDA_DETERMINISTIC_REDUCE=1` all the mpi reductions will be done deterministically regardless of the rank order or rank placement over nodes. If you switch to this branch, and for example compare runs between using a constant number of processes, and 4 GPUs in a node and 1 GPU per node over 4 nodes, then the result will be identical. Tuning can be enabled for this, but does require that you force the dslash policy choice for determinism e.g., `QUDA_ENABLE_DSLASH_POLICY=0` (or disable autotuning). Anyway, the hope is that this should help isolate issues and work out exactly where something goes wrong.
> 
> **Note this requires either using a unit gauge or loading a gauge field from disk - I've yet to move the test code that creates a gauge field to the hyper-cubic RNG - will get this done in the next day or two.
> 
> Anyway, hopefully we can track this down....

On our side it's not terribly urgent, although it would be nice to have. I can always use an older version on the Kepler nodes as we don't need the recent features.

**Comment by kostrzewa** [comment]
Below a sit rep from a scan that I completed yesterday/today. MG inversion of twisted clover on a 32c64 lattice on two nodes with 4 K20m each.

I test the pre-```hotfix/milc-bnl``` (compiled at commit 54b503f25b9f5bb22de83370b9ce6950804f8564) noted in the top-level report as well as ```hotfix/milc-bnl``` which I had compiled at commit 4df6a29bcfbc8e16558a2c9214955db29639b5d8

I enable run_verify throughout and test all combinations of GDR \in [0,1], P2P \in [0,1,3]

Each combination has its own (empty) tunecache at the start of these runs. As a reminder, we run OpenMPI 2.0.2a1 and I attach the output of ```ompi_info``` for reference: [ompi_info.log](https://github.com/lattice/quda/files/3182695/ompi_info.log)


GDR | P2P | pre-```hotfix/milc-bnl``` (at 54b503f25b9f5bb22de83370b9ce6950804f8564) | ```hotfix/milc-bnl``` (at 4df6a29bcfbc8e16558a2c9214955db29639b5d8 )
-------|-----|-----------------------------------|-----------------
0 | 0 | fails ```run_verify``` | fails ```run_verify```
0 | 1 | passes ```run_verify```, but r^2 ~ 1e+4 | passes ```run_verify```, but r^2 ~ 1e+4
0 | 3 | passes ```run_verify```, but r^2 ~ 1e+4  | passes ```run_verify```, but r^2 ~ 1e+4
1 | 0 | works correctly | works correctly
1 | 1 | passes ```run_verify```, but r^2 ~ 1e+4 | works correctly
1 | 3 | works correctly | works correctly

So it seems that I should have tested all combinations to begin with and that the situation has improved minimally with ```hotfix/milc-bnl```, but further issues seem to remain.

**Comment by maddyscientist** [comment]
Hi @kostrzewa.  Just to update you: I did some tests on your K20m system today, and I can report that I have reproduced badness on the cluster when running QUDA unit tests with a 32^3x64 clover (no twist) lattice (with 1x1x2x4 topology).  I also see the failures in verify when p2p=0.

Debugging this issue directly now, hopefully I'll get this nailed in the next day or so.

**Comment by maddyscientist** [comment]
Update here @kostrzewa.   Still working on isolating this bug, though I have determined that the issue only arises I think when the clover field is computed on the device, and if this isn't done then the error seems to go away.  Consistent with the MG bug as reported by the @ckallidonis @ BNL, the issue only occurs if we have the the rank order running fastest for the Z dimension and slower for the T dimension (in QUDA test language, `--rank-order row` fails, but `--rank-order col` works).

Also, I've managed to reproduce the case where the verification test passes, but the solver diverges.    This appears to be a hole in the verification testing: if the link on the exchanged forward coarse link is  corrupted but the backward one is exchanged fine, then the test `Dc - R D P` will pass correctly, but the dagger equivalent which is not tested would fail.  I'll plug this hole to ensure that such an error is caught.

More as I find it.

**Comment by kostrzewa** [comment]
There seems to be another issue in that the MG setup breaks somewhat after an update (change of twisted quark mass) even for cases where it works correctly initially.  This is what happens:

```
GCR: Convergence at 59 iterations, L2 relative residual: iterated = 1.219124e-11, true = 1.219124e-11 (requested = 1.794680e-11)
# QUDA: Done: 59 iter / 4.366 secs = 1093.26 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.053611 secs
# Inversion done in 59 iterations, squared residue = 3.300686e-17!
# Inversion done in 1.80e+01 sec. 
#
# 2 kappa mu = 0.000840387000, kappa = 0.140064500000, c_sw = 1.740000000000
# Using even/odd preconditioning!
# QUDA: Using single prec. as sloppy!
# QUDA: Using MG!
# QUDA: Using EO preconditioning!
# QUDA: Clover field and inverse already loaded for gauge 4
# QUDA: mu = 0.003000000000, kappa = 0.140064500000, csw = 1.740000000000
# QUDA: Reusing MG Preconditioner Setup for gauge 4
# QUDA: time spent in reorder_spinor_toQuda: 0.061644 secs
GCR: Convergence at 58 iterations, L2 relative residual: iterated = 1.506233e-11, true = 1.506233e-11 (requested = 1.794433e-11)
# QUDA: Done: 58 iter / 4.30295 secs = 1092.28 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.054359 secs
# Inversion done in 58 iterations, squared residue = 5.030569e-17!
# Inversion done in 1.79e+01 sec. 

# [correlators] Working on source / propagator set 2 of 4
#
# 2 kappa mu = 0.004930270000, kappa = 0.140064500000, c_sw = 1.740000000000
# Using even/odd preconditioning!
# QUDA: Using single prec. as sloppy!
# QUDA: Using MG!
# QUDA: Using EO preconditioning!
# QUDA: Time for loadCloverQuda: 1.3649e-01
# QUDA: mu = 0.017599998572, kappa = 0.140064500000, csw = 1.740000000000
# QUDA: Updating MG Preconditioner Setup for gauge 4
MG level 1 (GPU): Updating operator on level 1 of 3 levels
# QUDA: MG Preconditioner Setup Update took 4.103 seconds
# QUDA: time spent in reorder_spinor_toQuda: 0.061689 secs
WARNING: GCR: new reliable residual norm 5.517715e-05 is greater than previous reliable residual norm 4.189328e-05 (total #inc 1)
WARNING: GCR: new reliable residual norm 5.590204e-05 is greater than previous reliable residual norm 4.773099e-05 (total #inc 2)
WARNING: GCR: new reliable residual norm 4.967951e-05 is greater than previous reliable residual norm 4.680344e-05 (total #inc 3)
WARNING: GCR: new reliable residual norm 5.430590e-05 is greater than previous reliable residual norm 4.468853e-05 (total #inc 4)
WARNING: GCR: new reliable residual norm 4.606496e-05 is greater than previous reliable residual norm 4.515481e-05 (total #inc 5)
WARNING: GCR: new reliable residual norm 6.419434e-05 is greater than previous reliable residual norm 4.370302e-05 (total #inc 6)
WARNING: GCR: new reliable residual norm 5.245882e-05 is greater than previous reliable residual norm 4.857511e-05 (total #inc 7)
WARNING: GCR: new reliable residual norm 5.556140e-05 is greater than previous reliable residual norm 4.656229e-05 (total #inc 8)
WARNING: GCR: new reliable residual norm 5.118869e-05 is greater than previous reliable residual norm 4.506603e-05 (total #inc 9)
WARNING: GCR: new reliable residual norm 3.952458e-05 is greater than previous reliable residual norm 3.587458e-05 (total #inc 10)
WARNING: GCR: new reliable residual norm 3.772122e-05 is greater than previous reliable residual norm 3.716146e-05 (total #inc 11)
WARNING: GCR: solver exiting due to too many true residual norm increases
GCR: Convergence at 1217 iterations, L2 relative residual: iterated = 6.770209e-08, true = 6.770209e-08 (requested = 1.794801e-11)
Saving 439 sets of cached parameters to /qbigwork2/bartek/misc/quda_resources/kepler_134756255435ce0f7f476140eb07ff195706c0fb_gdr1_p2p3/tunecache.tsv
# QUDA: Done: 1217 iter / 56.3467 secs = 959.029 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.052520 secs
# Inversion done in 1217 iterations, squared residue = 1.192913e-09!
# Inversion done in 1.12e+02 sec. 

# [correlators] Working on source / propagator set 3 of 4
#
# 2 kappa mu = 0.006162838000, kappa = 0.140064500000, c_sw = 1.740000000000
# Using even/odd preconditioning!
# QUDA: Using single prec. as sloppy!
# QUDA: Using MG!
# QUDA: Using EO preconditioning!
# QUDA: Time for loadCloverQuda: 1.3605e-01
# QUDA: mu = 0.022000000000, kappa = 0.140064500000, csw = 1.740000000000
# QUDA: Updating MG Preconditioner Setup for gauge 4
MG level 1 (GPU): Updating operator on level 1 of 3 levels
# QUDA: MG Preconditioner Setup Update took 4.093 seconds
# QUDA: time spent in reorder_spinor_toQuda: 0.062038 secs
GCR: Convergence at 37 iterations, L2 relative residual: iterated = 1.219844e-11, true = 1.219844e-11 (requested = 1.794826e-11)
Saving 440 sets of cached parameters to /qbigwork2/bartek/misc/quda_resources/kepler_134756255435ce0f7f476140eb07ff195706c0fb_gdr1_p2p3/tunecache.tsv
# QUDA: Done: 37 iter / 3.62584 secs = 582.238 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.053093 secs
# Inversion done in 37 iterations, squared residue = 3.316924e-17!
```

I need to check if the current develop is similarly affected...
