### ISSUE TITLE
occasional crashes in exchangeGhost() in MG

### ISSUE THREAD

**Issue by kostrzewa** [lattice/quda#802]
I get these kinds of crashers from time to time and was wondering if this was observed elsewhere. If not, I would be happy to flesh out the report with more details. This is tmclover MG on a 32c64 lattice running on 4 P100.

```
MG level 2 (GPU): ERROR: cuCtxSynchronize returned error CUDA_ERROR_LAUNCH_FAILED (cuda_color_spinor_field.cpp:1374 in exchangeGhost())
 (rank 2, host lnode13.cluster.hiskp, /qbigwork2/bartek/code/bleeding_edge/quda_develop/lib/quda_cuda_api.cpp:316 in qudaDeviceSynchronize_())
MG level 2 (GPU):        last kernel called was (name=N4quda24GenericPackGhostLauncherIfLb1ELi2ELi2ELi24ELi2ENS_12PackGhostArgINS_11colorspinor12FieldOrderCBIfLi2ELi24ELi1EL16QudaFieldOrder_s2EfsLb0ELb0ELb0EEEEEEE,volume=4x8x8x4,aux=GPU-offline,vol=1024,stride=1024,precision=4,Ns=2,Nc=24,TwistFlavour=1,comm=0001,topo=1114,order=4567,dest=00000011)
```

**Comment by kostrzewa** [comment]
```
MG level 1 (GPU): ERROR: cuStreamSynchronize returned error CUDA_ERROR_LAUNCH_FAILED (rank 0, host lnode15.cluster.hiskp, /qbigwork2/bartek/code/bleeding_edge/quda_develop/lib/quda_cuda_api.cpp:278 in qudaStreamSynchronize())
MG level 1 (GPU):        last kernel called was (name=N4quda27TwistedCloverPreconditionedIsLi4ELi3ENS_16TwistedCloverArgIsLi3EL21QudaReconstructType_s18ELb1EEEEE,volume=16x32x32x16,aux=policy_kernel=interior,comm=0001,commDim=0001)
```

**Comment by kostrzewa** [comment]
```
MG level 2 (GPU): ERROR: cuCtxSynchronize returned error CUDA_ERROR_LAUNCH_FAILED (cuda_color_spinor_field.cpp:1374 in exchangeGhost())
 (rank 1, host lnode13.cluster.hiskp, /qbigwork2/bartek/code/bleeding_edge/quda_develop/lib/quda_cuda_api.cpp:316 in qudaDeviceSynchronize_())
MG level 2 (GPU):        last kernel called was (name=N4quda24GenericPackGhostLauncherIfLb1ELi2ELi2ELi24ELi2ENS_12PackGhostArgINS_11colorspinor12FieldOrderCBIfLi2ELi24ELi1EL16QudaFieldOrder_s2EfsLb0ELb0ELb0EEEEEEE,volume=4x8x8x4,aux=GPU-offline,vol=1024,stride=1024,precision=4,Ns=2,Nc=24,TwistFlavour=1,comm=0001,topo=1114,order=4567,dest=00000011)
```

**Comment by kostrzewa** [comment]
This was running with ```QUDA_ENABLE_P2P=3``` and the 4 P100 (8 per node) are all on the same machine.

**Comment by kostrzewa** [comment]
Happens in about 10% of runs, each of which has 1240 inversions.

**Comment by maddyscientist** [comment]
@kostrzewa I've never seen this issue before.  What version of MPI are you using and are you running with `QUDA_ENABLE_GDR=1`?  One thing that we recently released what that both MVAPICH and older versions of OpenMPI have buggy handling of CUDA IPC (inter-process inter-GPU communication over PCIe/NVLink) in that they don't correctly handle the case where a host application may use IPC on the same buffers that are passed to MPI.  This can lead to undefined behaviour as a result.

The issue only arises if `QUDA_ENABLE_GDR=1` is enabled (which enables the use of CUDA-aware MPI) and if QUDA is also doing direct GPU to GPU communication.

While I have filed bugs against OpenMPI and MVAPICH to get these issues resolved, the simple work around is to disable the use of CUDA-aware MPI for intra-node transfers if QUDA is also doing this, or vice versa.  With this in mind we now default to disabling CUDA-aware MPI for intra-node MPI if GDR is enabled (this is equivalent to `QUDA_ENABLE_P2P=7`), though it can be overridden by the user.  If you are running with GDR enabled, can you check if unsetting `QUDA_ENABLE_P2P` fixes the issue for you?

**Comment by maddyscientist** [comment]
@kostrzewa Can I ask you to test the `hotfix/milc-bnl` branch when you have a chance to if this issue persists?  I have been fixing various issues that I have found since I introduced [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) to QUDA (and I am now a huge proponent of this, since I found issues I would never have found otherwise), and made some of the behaviour more robust which could vary depending on the MPI library one is using.  For example, when allocating communications handles that reuse the statically allocated ghost buffers, I now ensure that we have a global barrier, to ensure all outstanding communications are complete.

**Comment by kostrzewa** [comment]
This is with OpenMPI-2.0.2a1 with GDR support, although I run with ```QUDA_ENABLE_GDR=0``` currently because I had some problems with incorrect residuals which I did not have time to investigate in detail. I guess this might be the issue that you're describing.

As for the synchronisation problems, they also arise in this run (which has ```QUDA_ENABLE_GDR=0```) so I'm nto sure that this is the culprit. I have ```QUDA_ENABLE_P2P=3``` but I can test others of course.

I'm currently trying to reproduce the issue with a clean test case (rather than a complex application as before). It might well be that this arose because of some strange interactions as there were 2 copies of the program running on each node (each using 4 out of 8 P100s) and the nodes were under further load by other jobs (not using GPUs).

If I can reproduce it, I will start testing the ```hotfix/milc-bnl``` branch.

**Comment by mathiaswagner** [comment]
Is this still an issue?

**Comment by kostrzewa** [comment]
I guess I should close this, it'll be hard to wire up a reproducer for this now. I don't think this is still an issue, at least not as far as I can tell.
