### ISSUE TITLE
Fix plaquette calculation for recon 9 and 13 in staggered tests

### ISSUE THREAD

**Issue by weinbe2** [lattice/quda#835]
Right now, passing in `--recon 13` breaks the staggered inversion tests because the plaquette tests aren't compiled with recon 13 support. There are two possible trivial fixes: either template in recon 13 and 9 in the plaquette calculation code, or have the gauge field get loaded via recon 18 for the plaquette check then re-loaded in 13 afterwards.

This is more a reminder to myself than anything else.

**Comment by maddyscientist** [comment]
I think best to just support recon-13 and recon-9 directly.  I have a plan to remove the compilation overhead for the plaquette (no need to instantiate all block size templates).  So we shouldn't to worry about the compilation overhead.

**Comment by weinbe2** [comment]
Sounds good---I noticed we also need to add it in the fat link construction, too.

**Comment by maddyscientist** [comment]
Closed by #843
