### ISSUE TITLE
Stability of mixed-precision CG for heavy-quark solves

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#854]
#853 disables mixed precision for heavy-quark solves as they are sometimes unstable. 
This is a reminder to look into this.
One idea is to just iterate in mixed precision until L2 breakdown and then continue in full precision.

**Comment by weinbe2** [comment]
Closed by https://github.com/lattice/quda/pull/853 , refined further by https://github.com/lattice/quda/pull/1111 and https://github.com/lattice/quda/pull/1387
