### ISSUE TITLE
Investigate staggered dslash kernel which involves less memory traffic

### ISSUE THREAD

**Issue by jpfoley** [lattice/quda#86]
At the moment, the staggered Dslash kernel is implemented as follows. Each thread is assigned to a site x, and that thread computes
p(x) = sum_{mu} [U[mu](x)q(x+mu) + U[-mu](x)q(x-mu) + L[mu](x)q(x+3mu) + L[-mu](x)q(x-3mu)].
Therefore, each thread reads 16 color matrices and 16 spinors and writes a single spinor. Assuming 18 reconstruct for the links, each thread read/writes 390 floating point numbers. 
This figure can be reduced if we get the thread at x to compute part of p at a number of sites.
For example, thread x could do something like
1) p(x) = sum_{mu} [U[mu](x)q(x+mu) + L[mu](x)q(x+3mu)]
2) p(x+mu) += Conj(U[mu](x))q(x)
3) p(x+3mu) += Conj(L[mu](x))q(x)
As Mike pointed out, the output from steps 2) and 3) may have to be written to temporary fields to avoid
race conditions, and a kernel could be written which sums the fields. There's probably a clever way to do this, so it requires further thought. The upshot is that we exchange half the color matrix reads for additional spinor reads and writes. Because the staggered quark field spinor doesn't actually have a spin index, we end up reducing the IO. We estimate the number of reads and writes needed by the new dslash kernels is 312, which breaks down as follows
4_18(fat) + 4_18(long) +  9x6(reading q fields) + (9x6 + 10*6)(p-field output + summation) = 312. 
So it looks promising.  Of course, it is unlikely that this approach will help with other actions, because of the additional quark-field spin index. Also, I haven't thought how this fits with the communication routines in the multi-gpu code.

**Comment by maddyscientist** [comment]
Closing this issue, since it isn't applicable to using the even odd decomposition as well as having race conditions
