### ISSUE TITLE
Default arguments in staggered_eigensolve_test.cpp

### ISSUE THREAD

**Issue by cmcneile** [lattice/quda#886]
Hello,
         Just a suggestion.

When  I use

mpirun -npernode $mpi_tasks_per_node -np $np  /home/cmcneile/Wilkes2-gpu/production_runs/exec/staggered_eigensolve_test \
--dim 12 12 24 64 --gridsize 2 2 1 1 \
--load-gauge ./l2464f211b600m0102m0509m635a-coul.1000_ildg 
--dslash-type asqtad --mass 1e-16 --compute-fat-long true --tadpole-coeff 1.0 --test 3 \
--prec double --recon 18 \
--eig-nConv 16 --eig-nEv 18 --eig-nKr 32 --eig-tol 1e-4 \
--eig-use-normop false --eig-use-poly-acc true --eig-poly-deg 300 \
--eig-amin 1.0 --eig-amax 24

I didn't notice that the \ was missing after the gauge configuration name. This means that the default parameters were used and these parameters didn't allow any the eigensolver to be used

Creating TR Lanczos eigensolver
spectrum SR
tol 1.0000e-06
nConv 16
nEv 16
nKr 32
polyDeg 100
a-min 0.100000
a-max 4.000000

I know it was a stupid bug in my script, but it would be perhaps better to call an error if argument is missing.

Thanks,  Craig

**Comment by mathiaswagner** [comment]
I see your point and we are busy rewriting QUDA's parameter parser anyway.
Still not sure what you are suggesting here: Error out if any parameter that the test requires is not explicitly given on the command line? This will become quite annoying as the you will need to specify everything just to be able to run a test (and in some cases even parameters that are only needed if others are given and make no sense for the test you want to run ...).
So forcing users to specify ALL allowed parameters is not what want (IMHO). Requiring some parameters to be given explicitly is something we can think about.

**Comment by mathiaswagner** [comment]
we now use CLI for parsing arguments
