### ISSUE TITLE
BatchInvertMatrix with Eigen on CPU

### ISSUE THREAD

**Issue by ybyang** [lattice/quda#923]
I find a subtle issue on the function BatchInvertMatrix used in the multigrid setup. @maddyscientist 

We tried to use the function inverse() in the library Eigen to replace the role of cublas, to do the batched inversion of the matrices on CPU. It doesn’t really matter since it just need to be called once during the entire the multigrid setup, and use ~1s for 24 vectors on a 24^4 lattice. 

Our code is the following:

```
      gettimeofday(&start, NULL);
      void *A_h = location == QUDA_CUDA_FIELD_LOCATION ? pool_pinned_malloc(size): A;
      void *Ainv_h = pool_pinned_malloc(size);
      if (location == QUDA_CUDA_FIELD_LOCATION) qudaMemcpy(A_h, A, size,hipMemcpyDeviceToHost);

      if (prec == QUDA_SINGLE_PRECISION) {

        std::complex<float> *A_eig=(std::complex<float> *)A_h;
        std::complex<float> *Ainv_eig=(std::complex<float> *)Ainv_h;

#pragma omp parallel for
        for(int i=0;i<batch;i++)
        {
                Eigen::MatrixXcd res=Eigen::MatrixXcd::Zero(n,n),inv;
                for(int j=0;j<n;j++)
                for(int k=0;k<n;k++)
                        res(j,k)=A_eig[i*n*n+j*n+k];
                inv=res.inverse();
                for(int j=0;j<n;j++)
                for(int k=0;k<n;k++)
                        Ainv_eig[i*n*n+j*n+k]=inv(j,k);
        }
      }
      else {
        errorQuda("%s not implemented for precision=%d", __func__, prec);
      }

     gettimeofday(&stop, NULL);
     long dsh = stop.tv_sec - start.tv_sec;
     long dush = stop.tv_usec - start.tv_usec;
     double timeh = dsh + 0.000001*dush;

        printfQuda("CPU: Batched matrix inversion completed in %f seconds with GFLOPS = %f\n", timeh, 1e-9 * batch*FLOPS_CGETRI(n) / timeh);

        void *Ainv_ref_h = location == QUDA_CUDA_FIELD_LOCATION ? my_pinned_malloc(size): Ainv;
        if (location == QUDA_CUDA_FIELD_LOCATION) cudaMemcpy(Ainv_ref_h, Ainv, size,cudaMemcpyDeviceToHost);

        double diff=0.0,norm=0.0;
        float *Ainv_c=(float *)Ainv_h, *Ainv_g=(float *)Ainv_ref_h;
        for(int i=0;i<2*n*n*batch;i++)
        {
                diff+=pow(Ainv_c[i]-Ainv_g[i],2);
                norm+=pow(Ainv_g[i],2);
        }
        printfQuda("BatchInvertMatrix: relative difference=%e, norm = %e\n",
                sqrt(diff/norm),sqrt(norm));

        if (location == QUDA_CUDA_FIELD_LOCATION)
                my_pinned_free(Ainv_ref_h);

      if (location == QUDA_CUDA_FIELD_LOCATION) {
        qudaMemcpy(Ainv, Ainv_h, size, hipMemcpyHostToDevice);
        pool_pinned_free(Ainv_h);
        pool_pinned_free(A_h);
      }

```

We wrote an independent code to check consistency of our code and they are the same as that from cublas (diff~1e-5). But when the same code is inserted in the function BatchInvertMatrix, and used in the multigrid_benchmark_test (with default parameters), the relative difference defined in the code above is O(0.1). We printed out the matrices and confirmed that the CPU Eigen result is the same as that from python. However, the final result of the mg inverter seems to be the same with either the cublas or Eigen version of BatchInvertMatrix. Maybe this inversion doesn’t have to be very precise?

Best,

Yi-Bo

**Comment by maddyscientist** [comment]
Hi @ybyang.  I would be surprised that a deviation of 0.1 would not cause solver degradation.  Perhaps this is an artifact of using fake data though in the multigrid benchmark.  Do so see the same deviation when using a real gauge field?

Also, are you comparing the absolute deviation or relative deviation?  Only the latter makes sense here, and a deviation of 0.1 with an absolute comparison doesn't say anything.

If you like, we could include this alternative code path in QUDA.  Could you file a pull request with this addition in there?  Perhaps using CUBLAS or not could be a cmake configuration option.

**Comment by ybyang** [comment]
Hi @maddyscientist,

      I haven't try to compare the difference with the real gauge field yet. The deviation is the relative one, I just sum the deviations in square, and divide the sum of the square of cpu result. 

      A pull request is drafted.

**Comment by ybyang** [comment]
The comparison with the real gauge field is done through Chroma. I used a 24^3x64 MILC configuration, 24 NULL vectors, and the relative difference I got is 1.085209e-01. The definition of the relative difference is:
diff=sqrt(\sum_{i<2*n*n*batch} (CPU[i]^2-GPU[i]^2)/\sum_{i<2*n*n*batch} GPU[i]^2)).

**Comment by maddyscientist** [comment]
I don't think this is the correct measure to use here.  Specifically, the relative deviation should be measured per matrix as opposed to computing this over the entire lattice.  The deviation is a local quantity and not extensive.

The appropriate measure would be something like the following I think, where _X_ is a given matrix and _N_ is the number of matrices.  Perhaps instead of the L2 norm the Linfinity norm might be more appropriate.

<a href="https://www.codecogs.com/eqnedit.php?latex=\sum&space;\frac{1}{N}\frac&space;{||&space;X_{CPU}&space;-&space;X_{GPU}&space;||_2&space;}{||&space;X_{GPU}&space;||_2&space;}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum&space;\frac{1}{N}\frac&space;{||&space;X_{CPU}&space;-&space;X_{GPU}&space;||_2&space;}{||&space;X_{GPU}&space;||_2&space;}" title="\sum \frac{1}{N}\frac {|| X_{CPU} - X_{GPU} ||_2 }{|| X_{GPU} ||_2 }" /></a>

**Comment by ybyang** [comment]
Solved. As tested by cpviolator, the input matrix should be copied to CPU before the BLAS functions.
