### ISSUE TITLE
TRLM: upper bound of operator should be optionally found using Raleigh quotient

### ISSUE THREAD

**Issue by maddyscientist** [lattice/quda#932]
At present the user must estimate the upper and lower bounds of the spectrum to include in the polynomial acceleration.  We could make this process a bit easier for the user, such that if the upper bound is found automatically using a Raleigh quotient method in the same way that the CA-CG with Chebyshev basis does at present if the user doesn't specify the bound.

**Comment by cpviolator** [comment]
Closed with #933
