### ISSUE TITLE
Full parity TRLM failing for MDWF 

### ISSUE THREAD

**Issue by cpviolator** [lattice/quda#966]
As far as I can tell, wilson(clover) and twisted(clover) type fermions convergence in the eigensolver for both full parity and single parity fields. The same is true for domain-wall and domain-wall-4d. For mobius, only the single parity solution types will converge.

Any ideas?

**Comment by cpviolator** [comment]
Update:

Using the following command, a direct CG solve also shows lack of convergence:
```./invert_test --dslash-type mobius --dim 24 24 24 16 --Lsdim 8 --mass 0.0102 --gridsize 1 1 1 4 --rank-order row --niter 5000 --prec double --tol 1e-8 --verbosity verbose --reliable-delta 0.1 --inv-type cg --inv-deflate false --prec-sloppy single --prec-precondition single --m5 -1.2 --b5 1.5 --c5 0.5 --solve-type direct --solution-type mat```

Should be reproducible on smaller partitions. Note that `--solve-type direct-pc` also fails. `--solve-type normop` and `--solve-type normop-pc` work fine.

**Comment by walkloud** [comment]
@cpviolator is your solver test failing on a real QCD field or a weak-field?  @maddyscientist might recall - some time ago, with MDWF solves, I found non-convergence problems with weak-fields but when I changed the topology or switched to a real QCD field, no problem - we never got to the bottom of it

**Comment by cpviolator** [comment]
@walkloud Both.

**Comment by maddyscientist** [comment]
This isn't a bug: the problem is that you are requesting to solve the linear system using a direct solve using CG.  This can't work because the fermion matrix isn't HPD, and needs to be solved using the normal operator.  E.g., using `--solve-type normop-pc --solution-type mat` would solve the full matrix using the preconditioned normal op CG solver.
