### ISSUE TITLE
QUDA_BUILD_ALL_TESTS=OFF should imply QUDA_INSTALL_ALL_TESTS=OFF 

### ISSUE THREAD

**Issue by bjoo** [lattice/quda#998]
@mathiaswagner asked me to submit a problem report (no pull-req yet, sorry). 
I found on recent develop, that having QUDA_BUILD_ALL_TESTS=OFF threw an error on installation. QUDA_INSTALL_ALL_TESTS=OFF fixes the install problem. But it would be nice if QUDA_BUILD_ALL_TESTS=OFF were to automatically imply/enforce QUDA_INSTALL_ALL_TESTS=OFF.

**Comment by mathiaswagner** [comment]
@bjoo You are most likely the only one who regularly _installs_ QUDA. I have a fix that went into #995 .

As this is a significant rewrite and obviously cannot test all build configurations for QUDA I'd appreciate if you could verify that the branch fixes install (and doesn't break anything else).
